### ISSUE TITLE
UCSD Baseline Results Transformation

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1024]
# Story
As UCSD, so that our EHR can ingest results messages from ReportStream, I need a variety of fields removed, modified, or swapped based on our technical scoping research.

## Pre-conditions
- These transformations should only be applied to either UCSD or CDPH.
- The transformations have been implemented in the RS staging environment

## Acceptance Criteria
- [x] Result messages delivered to UCSD are transformed based on https://docs.google.com/spreadsheets/d/1E7-ARoZ7Eb_8-N25XT3Fb77aybmsHHrD/edit#gid=1250549121

### Research
- [x] Update CA results spreadsheet to include which transformation are specific to UCSD and which are potentially needed by additional CA hospitals receiving CDPH ORUs. (also a task in #955)

###  Engineering
- [x] Transformation Engine
  - [x] Design transformation rule engine
  - [x] Refactor validation rule engine to reuse code for transformation engine
  - [x] Implement transformation engine
    - [x] Decide where to house custom methods (a folder w/1 file per method that implements the `CustomFhirTransformation` interface?) @basiliskus 
    - [x] Implement `TransformationRule.runRule`: get method by name and evaluate with args 
    - [x] Fix `TransformRule` mapping from json file
    - [x] Refactor to use transformation engine instead of current conversion
      - [x] In `ConvertAndSendDemographicsUsecase` replace `OrderConverter` with `transformationEngine.runRules`
      - [x] In `SendOrderUseCase` replace `OrderConverter` with `transformationEngine.runRules`
        - [x] Remove `OrderConverter` interface
        - [x] Turn `HapiOrderConverter` into a class with static methods. Remove singleton and dependency injection
        - [x] Fix tests  
      - [x] In `SendResultUseCase` replace `ResultConverter` with `transformationEngine.runRules`
        - [x] Remove `ResultConverter` interface
        - [x] Remove `HapiResultConverter`
        - [x] Fix tests  
      - [x] Fix e2e tests
      - [x] Add test coverage 
    - [x] Move current transformations to engine
      - [x] `HapiOrderConverter.convertToOrder`  @saquino0827 
      - [x] `HapiOrderConverter.convertToOmlOrder`  @luis-pabon-tf 
      - [x] `HapiOrderConverter.addContactSectionToPatientResource` @luis-pabon-tf 
      - [x] `HapiOrderConverter.addEtorProcessingTag` @jorg3lopez 
  - [x] Further refactoring 
    - [x] Refactor logic in the converter helper classes (`HapiMessageConverterHelper` and `HapiOrderConverterHelper`) @basiliskus 
      - [x] Refactor `convertToOmlOrder` to make it more generic: `ConvertToOrderType `
      - [x] Move relevant logic to transformation methods
    - [x] Use Enum instead of magic strings in addEtorProcessingTag and addContactSectionToPatientResource @basiliskus
    - [x] Add exception handling for remaining transformations @basiliskus
- [x] Add transformations to engine:
  - [x] MSH-4 @luis-pabon-tf 
    - [x] Update sending facility to reflect value of `CDPH`
  - [x] MSH-5 @luis-pabon-tf 
    - [x] Update Receiving Application (MSH-5) to literal value: "EPIC"
    - [x] Strip content from MSH-5.2 and MSH-5.3 @basiliskus 
  - [x] MSH-6 @basiliskus 
    - [x] Update Receiving Facility (MSH-6) to value in ORC-21.10 ("R797" or "R508")
    - [x] Strip content from MSH-6.2 and MSH-6.3 
  - [x] MSH-9
     [Note: prime-router/src/main/resources/metadata/hl7_mapping/resources/MessageHeader/MSH.yml]
    - [x] Strip content from Message Type (MSH-9). Remove MSH-9.3  - @tjohnson7021
  - [x] PID-3 @jherrflexion 
    - [x] Strip content from Patient Identifier (PID-3). Remove PID-3.4 and PID-3.5 @jorg3lopez 
  - [x] PID-5  @saquino0827 
    - [x] Strip content from Patient Name. Remove PID-5.7  @saquino0827 
  - [x] ORC-2/ORC-4 -  Effectively, we're swapping ORC-2 for ORC-4 and vice versa
     [ Note: ORC-2 here comes from ServiceRequest; **FHIR to HL7**In FHIRPath.java, **HL7 to FHIR**: prime-router/metadata/HL7/catchall/hl7/message/ORU_R01.yml ] @luis-pabon-tf 
     [ Note: ORC-2 here comes from ServiceRequest; **FHIR to HL7**In FHIRPath.java
    - [x] Update ORC-2 with content from ORC-4 in the ORU result message.
    - [x] Replace ORC-2.1 with content of ORC-4.1.
    - [x] Replace ORC-2.2 with content of ORC-4.2
    - [x] Replace content in ORC-4 with content from ORC-2 in the ORU result messsage. @jorg3lopez 
    - [x] Replace ORC-4.1 with content of ORC-2.1. @jorg3lopez 
    - [x] Replace ORC-4.2 with content of ORC-2.2 @jorg3lopez 
    - [x] Effectively, we're swapping ORC-2 for ORC-4 and vice versa
  - [x] OBR-2 @luis-pabon-tf 
    - [x] Update OBR-2 with content from ORC-4 in the ORU result message.
    - [x] Replace OBR-2.1 with original content of ORC-4.1.
    - [x] Replace OBR-2.2 with original content of ORC-4.2
  - [x] OBR-4 @luis-pabon-tf 
    - [x] Update OBR-4.3 and OBR-4.4 in the ORU result message where the OBR-4.1 = '54089-8'
    - [x] Update OBR-4.3 (Univeral Service ID - Name of Coding System) with literal value: "LN"
    - [x] Update OBR-4.4 (Universal Service ID - Alternate ID) with literal value: "CDPHGSPEAP"
  - [x] Refactor FHIRPath.java to MappingPath.java and add the HL7v2 segments to their corresponding FHIR path. - @tjohnson7021 
  - [x] Add exception handling @basiliskus 
- [x] Test end-to-end flow from initial HL7 to final HL7 

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder) - @tjohnson7021 
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [ ] ~~Testing tasks completed~~
  - [ ] ~~Load tests passed~~ : to be resolved by #1121
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
Note: For MSH-9.3, if we find this is problematic (because RS keys on this value), then we may need a new story to capture that specific transformation.

**Comment by luis-pabon-tf** [comment]
MSH-9: Maps to `MessageHeader.eventCoding`, example:
```
"eventCoding": {
          "system": "http://terminology.hl7.org/CodeSystem/v2-0003",
          "code": "R01",
          "display": "ORU^R01^ORU_R01"
}
```
I believe trimming out the last segment of the `display` string will satisfy the transformation requirements.

**Comment by luis-pabon-tf** [comment]
PID-3: Maps to `Patient.identifier`. Inside it, there's `type` and `assigner` objects which seem to match the elements we want to remove.

**Comment by luis-pabon-tf** [comment]
PID-5: Maps to `Patient.name`. This is a `HumanName` object, in which `PID-5.7` is mapped to `use`. Stripping that out should handle the requirement.

**Comment by basiliskus** [comment]
Moved pending refactoring tasks to story #1109

**Comment by jorg3lopez** [comment]
Load test is currently failing, we will address this issue in a separate ticket.

**Comment by JohnNKing** [comment]
> Load test is currently failing, we will address this issue in a separate ticket.

Specifically, that's #1121
