### ISSUE TITLE
Failed Sending Result not Marking Metadata as Failed

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#1041]
# Bug

## Describe the Bug

We were only marking metadata as failed for orders if they failed to send.  Results that failed to send weren't being marked as failed.

## Expected Behavior

Metadata is marked as failed for failing to send results.

**Comment by JohnNKing** [comment]
Was this intended for stream 1? We didn't have context during Planning.

**Comment by halprin** [comment]
> Was this intended for stream 1? We didn't have context during Planning.

I worked on this with @jherrflexion, so it could be lumped in with either stream.
