### ISSUE TITLE
Load Tests Broken

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1044]
# Bug

## Describe the Bug

As identified while reviewing #621, load tests are not working correctly.  They were passing at some point.  Consider walking back in history to see if there is an obvious culprit.  The purpose of this ticket is to fix the load tests, as they are architected today.  Out of scope, for example, is to have the load tests run against a deployed environment.

## Notes

- See [Slack](https://flexion.slack.com/archives/C06CP7E3NAF/p1713987260530329) for some details.
- [x] Fix load tests stream1/1044/e2eTests
  - [x] Fix non-db implementation for metadata
- [x] Fix e2e tests

**Comment by jcrichlake** [comment]
Going through the history this works as of commit 68c767aa45ea4ebc7a16d524d2de7959a9a3b218
