### ISSUE TITLE
Prepare for May 2024 ETOR Retreat

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#1056]
# Backlog Task

Add a title and description here

## Completion Criteria

- [x] What is the criteria for calling this task complete?

## Tasks
- [x] Create slides
- [x] Attend meeting on 05/03/2024

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by scleary1cs** [comment]
Scott shared "CDC Intermediary Quarterly Review - 05-03-2024"
