### ISSUE TITLE
SFTP Read file from external service and copy to internal Azure blob storage

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1077]
# Story
As a CA, so that my messages can be delivered to a hospital, I need the SFTP service to read from an _external_ SFTP site.

## Pre-conditions
- [x] #1075, and #1076 are complete. 
- [x] CA SFTP URL and creds (non-prod) etc are known

## Acceptance Criteria
- [x] Be able to connect to an external SFTP server using public/private key pairs and password (the code is there, but we need additional setup from our partners on their end. That external setup will be documented elsewhere)
- [x] We copy files from the SFTP server to our Azure Container Storage.

## Non-Acceptance Criteria
- [X] We **don't** support ZIP files.
- [X] Scheduled polling happens in a later story.

### Research
- [x] *Research work needed to complete the story*
- [x] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [x] Setup for local testing - local SFTP server URL, creds, and destination location
- [x] Using URL and keys/passwords, connect to external SFTP site and list file(s)
- [x] For each file, download it from the SFTP site and upload it to the specified destination in our storage blob container
- [x] Create a dummy SFTP server in Docker Compose - @halprin 

Tasks moved from #1075 
- [x] Refactor `context` out of QueueHandler struct
- [x] Add more tests for `report_stream_sender`

Blocked until we have connection info from CA:
- [x] Setup keys and passwords in Terraform
  - [x] Update keys and passwords in Terraform once resources are created in each environment:
    - [x] dev
    - [x] internal
    - [x] staging
- [x] TF for external SFTP site URL
- [x] TF for a destination location in our storage blob container
- [x] In TF, allow outbound calls to CA SFTP site
- [x] In code, potential updates based on CA's actual file structure - there's [a screenshot of the file structure in notion](https://www.notion.so/flexion-cdc-ti/CA-SFTP-questions-concerns-fun-7a0d98df4b35444394fc49da7639c13e?pvs=4#46a5acd209584379ac5fcb7a907ce1b7)
- [x] Test Staging environment 

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/693ff5f9-c289-4585-9e74-a7f5abb36d69/edit?invitationId=inv_24d83a2b-b0fe-436d-8bd2-027b17beeb33) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*
- If we hit their test/staging environment repeatedly, will we get locked out? What's the limit? @JohnNKing 
  - I'm unsure, and staging may differ from prod. @jorg3lopez can you follow up with CDPH to clarify what the limits are per environment?

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
1. Read a file from California (let's assume it's not a ZIP) - scheduled polling happens in later card.
2. Send it to the RS SFTP site (Azure bucket).

**Comment by scleary1cs** [comment]
SFTP access to CA.  Manjula sent an updated form on Wednesday.  Account will be created soon.  Email's regarding this account should be forwarded to cdc-ti@flexion.us
Manjula sending a followup email today. Part of the email is looking for non-prod access for testing.

**Comment by scleary1cs** [comment]
Need CA creds

**Comment by jcrichlake** [comment]
We have most of the basic functionality in place.  The work that has been done is either merged into main or is waiting inside of a PR.   

The remaining work is currently blocked until we receive the SFTP non-prod credentials from California.

**Comment by jcrichlake** [comment]
We have received some word back from California, we have implemented some of the information they have given us.   There are still one or two lingering outstanding questions that we need to get clarity on from them

**Comment by scleary1cs** [comment]
Blocked based on - Q&A based on email thread "CDPH SFTP Integration Questions (for ReportStream & UCSD)"

**Comment by somesylvie** [comment]
This remains blocked - we need to meet with CADPH to get on the same page about file structures, and the right people from their side weren't at the touchbase today

**Comment by jcrichlake** [comment]
@scleary1cs We have the code for accepting a key in place but commented out until we here word from CA that they are turning on the requiring of a key.  Let us know if that is a show stopper based on the Acceptance Criteria for this card.

**Comment by scleary1cs** [comment]
@jcrichlake sorry I something changed while I was out.  Did we create a key pair and supplied to CA?

**Comment by scleary1cs** [comment]
We have provided the public keys for our prod and non-prod accounts to Sumitha via a secure email and posted the files:Home/CDPH-SIS-Staging/HIE-Staging/UCSD

**Comment by somesylvie** [comment]
After Shawn sent keys last week, they sent us some info about setting up a new/different user account, but not the new password for that account I don't think
