### ISSUE TITLE
SFTP File Deletion

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1078]
# Story
As a CA, so that I know my files have been sent, I need the files on my SFTP server to be deleted after they have been received by the external SFTP service.

## Pre-conditions
- [x] #1077 is complete. 

## Acceptance Criteria
- [x] The files are deleted off of the CA SFTP server only after the files have been written to our Azure bucket.

###  Engineering
- [x] The files are deleted off of the CA SFTP server after the files have been written to our Azure bucket.

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
  - [x] [Threat model](https://lucid.app/lucidchart/693ff5f9-c289-4585-9e74-a7f5abb36d69/edit?invitationId=inv_24d83a2b-b0fe-436d-8bd2-027b17beeb33) updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Unit test coverage of our code >= current minimum threshold
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
1. Delete a file after reading it from the external SFTP site.
2. What should we do when we fail to delete the file? If it's not deleted, we'll end up sending the file again at the next polling interval
3. There's a bunch of old files in the `OUTPUT` folder in prod - should we be sending those or will they remove them before we go live?

**Comment by somesylvie** [comment]
PR for file deletion opened today. This card should be complete once it's approved and merged
