### ISSUE TITLE
SFTP Unzipping

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1079]
# Story
As a CA, so that my HL7 messages can be read, I need the SFTP service to unzip and apply a password to access the  messages.

## Pre-conditions
- [x] #1077 is complete (#1077 is complete enough as of 07/10/2024).

## Acceptance Criteria
- [x] Zip files read from external SFTP server are put into a special subfolder in Azure bucket. 
- [x] Unzip the file in the special subfolder and write the messages into the _processing_ subfolder.

### Research
- [x] We need to get our hands on a test password protected zip file from CA @JohnNKing. 

###  Engineering
- [x] Code to apply a password to a locked file
- [x] Code to unzip a file
- [x] Code to call the unzipping - when retrieving a file from external SFTP site, check if it's a zip. If it's a zip, move to an unzip folder. Then immediately unzip that file since we know it's there and move the single hl7 files to `import`. If the file is not a zip, move to `import` for importing
- [x] Update `ca-dph-zip-password-${var.environment}` in deployed environments - Updated in staging, dev, and internal on 7/11/24

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
  - [x] [Threat model](https://lucid.app/lucidchart/693ff5f9-c289-4585-9e74-a7f5abb36d69/edit?invitationId=inv_24d83a2b-b0fe-436d-8bd2-027b17beeb33) updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Unit test coverage of our code >= current minimum threshold
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
1.  Password entry mysteries
2. Do the unzipping

**Comment by scleary1cs** [comment]
Should we add decrypting to the AC? @halprin @somesylvie @jcrichlake

**Comment by halprin** [comment]
> Should we add decrypting to the AC? @halprin @somesylvie @jcrichlake

We could represent this as a precondition stating that the Zip file is password protected.

**Comment by jherrflexion** [comment]
Stream 1 is currently POCing some code to test the unzip/decrypt logic. At the moment, we are considering Yeka package to handle this functionality.

**Comment by scleary1cs** [comment]
Who needs to/can take action on this last task? 
" Update ca-dph-zip-password-${var.environment} in deployed environments"

**Comment by somesylvie** [comment]
> Who needs to/can take action on this last task? " Update ca-dph-zip-password-${var.environment} in deployed environments"

@scleary1cs we've update that value in the appropriate environments
