### ISSUE TITLE
SFTP AL Receipt ACKs

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1083]
# Story
As a _, so that _, I need _.

## Pre-conditions
- [ ] *Assumptions of prior or future work that's out of scope for this story*

## Acceptance Criteria
- [ ] HL7 MSA CA (commit ack) created on SFTP file ingest 

### Research
- [ ] *Research work needed to complete the story*
- [ ] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [ ] *Engineering work needed to complete the story*
- [ ] Foundational: *Technical runway work to support this and future efforts*

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*
- Is the right time to send these 'once received by ReportStream' or some other time? @JohnNKing 
  - The key constraint is it needs to be immediate, or nearly so. Also, I don't expect ReportStream to be able to handle the forwarding of HL7 ACK messages until farther in the future -- so we can't rely on that. Conceivably, this could even be before we sent the message off to ReportStream.
  - Also, there's no expectation of sending a NAK this way, as many things that could cause a NAK (e.g. connectivity or auth issues) may be fixed by re-submitting the message. 
- Would we write these ACKs to our blob storage (i.e. where they sent the files) or to somewhere else (their own SFTP site?)?

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
1.  Receipt ACKs (for Alabama) - might need help figuring out the format

**Comment by somesylvie** [comment]
Unclear on exactly when makes sense to send the ACK/exactly what we're acknowledging. Could potentially send ACK on ingestion to SFTP service (like once we read the queue message before we call RS), or based on response from sending to RS. If after RS step, where do retries come in here? If we get a bad response from RS, what does that mean for what the receipt looks like?

**Comment by scleary1cs** [comment]
AL no longer an initial implementation partner.
