### ISSUE TITLE
CA Result OBX Mapping Issues

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1133]
# Bug

## Describe the Bug

We've identified a few issues with OBX mapping for the CA sample ORU: https://github.com/CDCgov/trusted-intermediary/blob/main/examples/CA/002_CA_ORU_R01.hl7

- ~~OBX.2 of TN is rejected by RS (and if changed to XTN, OBX.5 is lost)~~
  - To confirm with CDPH if this would be used for UCSD
- OBX.2 of CE are losing OBX.3 and OBX.5
  - Confirmed that data is lost when converting HL7 => FHIR 
  - Mappings for OBX.3 and OBX.5 are here: `prime-router/metadata/HL7/catchall/hl7/segments/OBX/Observation.yml`
  - [RS is looking into this issue](https://github.com/CDCgov/prime-reportstream/issues/14685)
- OBX.6: For μmol, 'μ' has an incorrect encoding in the resulting HL7
  - Fixed in PR #1134  

## Impact

This will prevent integration with CA.

## To Reproduce

Submit the sample ORU (https://github.com/CDCgov/trusted-intermediary/blob/main/examples/CA/002_CA_ORU_R01.hl7) to ReportStream.

## Expected Behavior

The content of the input and output HL7 matches

## Screenshots

n/a

## Logs

n/a

## Version

Current main

## Additional Context
Related backlog items:
- #905
- #1071

**Comment by basiliskus** [comment]
I just found out that the CE OBX mapping issue is a known bug in RS. A ticket will be created and someone from RS will take a look next week

**Comment by basiliskus** [comment]
A ticket to address the OBX CE issue was created in RS: https://github.com/CDCgov/prime-reportstream/issues/14685

**Comment by basiliskus** [comment]
Waiting for RS to look into this issue. Tagged as blocked

**Comment by jorg3lopez** [comment]
Findings:
- [HL7-2.5.1](https://hl7-definition.caristix.com/v2/HL7v2.5.1/Tables/0125) supports CE datatype for OBX.2
- [HL7-2.7](https://hl7-definition.caristix.com/v2/HL7v2.7/Tables/0125) does not support CE datatype for OBX.2
- The issue happens when HL7 -> FHIR translation occurs. If `OBX.2` has `CWE`, the FHIR resource comes with a coding resource as part of the `Observation` resource. This coding resource is used to populate `OBX.3` and `OBX.5`, and this resource is missing when `OBX.2` has `CE` as the datatype.

`CWE` datatype:

<img width="1112" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmRVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4aa8fbd0a907ea0f824207a0c5f66f5990053b0a/image.png" alt="image.png" />

`CE` datatype:

<img width="1007" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmxVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f61d63c4435088051bf898b0ff3c62e31c917eb/image.png" alt="image.png" />

**Comment by jorg3lopez** [comment]
Worked together with Josh Fisk from Report Stream to fix this issue. Findings: RS turns all CE datatypes for OBX.2 into CWE. Reason being, some clients have a hybrid message with v251 and v27 configurations. To address this problem, RS uses the v27 model to parse the file. 

CE to CWE:

<img width="1285" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVJoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e83eb2bbdb4b72a22fe60dab70ccd5fbbc1d131/image.png" alt="image.png" />


Using CWE configs for OBX.2:

<img width="1172" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36474ba8f505f856e364d6dc8c51bd35a3d629f0/image.png" alt="image.png" />

Same for OBX.5:

<img width="1168" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEJoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ad5aa726726541652a051cc49a76b23a2c2090f/image.png" alt="image.png" />

<img width="1526" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEpoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fc7edd82779826bc8b81dad1e6a87616c03bdf0/image.png" alt="image.png" />

Mapping FHIR -> HL7 using CWE for OBX.2

<img width="1652" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDVoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e4d6d0db3d2e281e4ffbb696f9225ab6c23d41b/image.png" alt="image.png" />

Josh is working on adding new unit tests, fixing the broken tests, and adding integration tests. This is his branch: [ingest-ce-fields-as-cwe](https://github.com/CDCgov/prime-reportstream/pull/14724)

**Comment by JohnNKing** [comment]
Final step: Need to test that merged PR has resolved this issue

**Comment by jorg3lopez** [comment]
Update:
Ran tests against the main branch and we could observe that OBX.3 and OBX.5 are populated when OBX.2 has CE as datatype:

<img width="1282" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1NiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ab487661066b8c9ded14ee0b8681254e46eebf3/image.png" alt="image.png" />

Also, the FHIR bundle has the entries mapped with CWE mappings. This was expected to happen.

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2FiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c508a508fbf06e1d08d11beee89c071e512f9e01/image.png" alt="image.png" />

**Comment by jorg3lopez** [comment]
We can close this ticket now.
