### ISSUE TITLE
SFTP Post-process File Handling

### ISSUE THREAD

**Issue by somesylvie** [CDCgov/trusted-intermediary#1141]
# Story
As a Intermediary developer, so that can, at a glance, understand where a file is in the processing lifecycle, I need the folder structure and file locations to reflect its current status.

## Pre-conditions
- [ ] [1076](https://app.zenhub.com/workspaces/cdc-ti-633de70d939f6c00155f3722/issues/gh/cdcgov/trusted-intermediary/1076)

## Acceptance Criteria
- [ ] *Required outcomes of the story*

### Research
- [ ] *Research work needed to complete the story*
- [ ] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [ ] Add blob storage code to move files along to where they are in the process (e.g. move from customer/import folder to customer/processed or customer/error folder)
  - Notes moved out of `queue.go`:
  ```text
	// TODO - how do we decide when to move a file from import to failure/error?
	// If a queue message ends up on the poison queue, should the file still be in `import`
	// or should we know to move it to `error`? Does it matter if it's e.g. a non-success response from RS
	// vs an error calling them?
	// TODO - minimum option is to check the dequeue count, and if we're over the threshold, log an error so we at least know something failed
  ```
- [ ] Once we know what folder structure we're using, add retention policy - [see RS for inspiration](https://github.com/CDCgov/prime-reportstream/blob/master/operations/app/terraform/modules/storage/main.tf#L118)

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
Closed, open tasks moved to story #1076
