### ISSUE TITLE
TI Internal Error Monitoring

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#1143]
# Story
As an Intermediary engineer, so that I can notify CA about any errors that occur, I need a way to identify error that occur during intermediary processing within the TI service.

## Pre-conditions
- Automated alerting is not mandatory for this story.

## Acceptance Criteria
- [x] If processing of a message fails in TI, that failure can be identified via a query.

###  Engineering
- [x] Make sure log capture and monitoring is set up the prod environment 
- [x] Add a query to the azure monitor (in all used environments) to view failures 
  - [x] Add terraform to create query in azure 
- [x] Clean up log output: remove test log messages at start (e.g. "Error", "Warning", etc)

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by luis-pabon-tf** [comment]
Tied to #500, might be blocked at the moment. Will update after discussion...

**Comment by luis-pabon-tf** [comment]
- Research what is needed to get our system hooked to Splunk
- Reach out again to Azure support as seen in #500

**Comment by jcrichlake** [comment]
Splunk integration shouldn't be required for this card.  The Splunk integration is to satisfy a separate CDC log aggregation requirement. For this card we probably just need to add some error based queries to our `logs.tf` file in TI.  There are 2 example queries already in that file, you just have to tinker in the Azure portal to figure out what would be a helpful query or a helpful set of queries for the above mentioned scenario

**Comment by basiliskus** [comment]
We can use this log query to get the errors in the azure logs:
```
AppServiceConsoleLogs
| project JsonResult = parse_json(ResultDescription)
| evaluate bag_unpack(JsonResult)
| where level == 'ERROR'
```

**Comment by basiliskus** [comment]
People in the team that were tasked with adding the query are still waiting for access to the azure resources needed. I'll look into this ticket today to check if I can add it

**Comment by basiliskus** [comment]
I added the terraform with the query and tested in the `dev` environment. Tomorrow will  deploy to rest of the environments
