### ISSUE TITLE
Expedite Partner Troubleshooting

### ISSUE THREAD

**Issue by saquino0827** [CDCgov/trusted-intermediary#1183]
# DevEx/OpEx
This set of tasks will allow us to know when deploying the polling function fails. The polling function is for triggering external SFTP calls and deploying it can fail silently. 

(Make sure we have automated alerting; dependency on PagerDuty. Deploys of SFTP service can fail silently. Specifically the polling trigger function.)

## Tasks
- [x] Add a step or some kind of alert to report failure on Azure Function App Func creation
  - Function App Function deploy can fail silently, leaving us not knowing our Func. App Func. failed to be made

## Additional Context
Add any other context or screenshots about the work here.

**Comment by jherrflexion** [comment]
This might be helpful: https://flexion.slack.com/archives/CQSN41TDK/p1721067663928249?thread_ts=1720805958.047789&cid=CQSN41TDK
