### ISSUE TITLE
Spike: Manual connection for PHL Results Staging Connectivity

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1193]
## Spike Goal
Confirm most of the preconditions of story #829.  We will need production and non-production users.

-We need the URL(s) for their SFTP server
-How should we connect (User/Pass+Keys, User+Keys)?
-What are our connecting credentials?
-What is the expected Polling schedule?
-We've manually connected the SFTP server
-Public/Private key generated by us

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by hcp4** [comment]
To AL:  
Suggested usernames:  cdctitest and cdctiprod
Will do both password and SSH authentication.
received this back from AL:
The cdcti accounts have been created with folders. I have used the suggested user accounts.  I have passwords.
I will be generating a new 2048 Key on Monday July 29 2024.
Our URL is     ph.state.al.us 
SSH/SFTP   is required.

**Comment by hcp4** [comment]
Confirmed connectivity using command line sftp using both password and public key authentication.  Configuration to link username and public key provided done by AL IT.  Production and Staging usernames, passwords, and private/public key pairs are in cdc_ti/secrets_to_access_partner_services/alsftp.  Keys were generated using Openssl version 3.0.2 in Ubuntu 22.04 with "ssh-keygen -t rsa -b 2048"
