### ISSUE TITLE
Technical Document / Diagram for UCSD

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1196]
# Design or Research

Based on CA SME call today, we've been asked to provide a document including the results flow, endpoints, and other information that would be valuable for future reference (e.g. troubleshooting).

## Tasks

- [x] Create Workflow diagram of PHL to UCSD

## Additional Context

Add any other context or screenshots about the work here.

**Comment by jorg3lopez** [comment]
LucidChart link: diagram[https://lucid.app/lucidchart/237fde81-9f15-43a1-9901-34dc34f7c956/edit?viewport_loc=-484%2C30%2C3328%2C1546%2C0_0&invitationId=inv_fd270dfb-2206-4eef-812a-1d95ff53af0f](url)

**Comment by jorg3lopez** [comment]
Update:
Jeff (UCSD) requested for us to add the endpoints to the diagram. The endpoints for RS, TI, and Epic have been added. This include the OAught2 and payload endpoints.

**Comment by jorg3lopez** [comment]
Update:
- Jeff uses Visio and our workflow diagram is in LucidChart. We need to export the diagram in visio format so he can access it via Visio.

**Comment by JohnNKing** [comment]
Minor updates made and diagram exported to https://aphlinformatics.atlassian.net/wiki/spaces/ERI/pages/2165997854/California+Documentation+Master+List
