### ISSUE TITLE
Alerting based on Azure Operational Metrics

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1206]
# DevEx/OpEx

High level description of what what needs to be improved.

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the work here.

We need to create alerting based on Create Azure Operational Metrics #671

**Comment by pluckyswan** [comment]
Closed because we have alerts set up from other cards that have been completed. See here for more information on what has been done: https://github.com/CDCgov/trusted-intermediary/issues/671
