### ISSUE TITLE
Improper access in app terraform

### ISSUE THREAD

**Issue by jcrichlake** [CDCgov/trusted-intermediary#1209]
# DevEx/OpEx

Priority: High

We currently have admin_enabled set to true in our app settings. We need to explore what options we have to turn that off and set up the other permissions needed to not break the application

## Tasks
Turn off `admin_enabled` and make sure deploys still work:
- [x] for ingestion service
- [x] for TI

## Additional Context

Add any other context or screenshots about the work here.

**Comment by saquino0827** [comment]
Blocked Pending additional permissions [here](https://servicedesk.cdc.gov/esc?id=sc_request&is_new_order=true&table=sc_request&sys_id=1d4500ff1bcc925404dedacae54bcb5c)
Request Number : REQ0342930

**Comment by somesylvie** [comment]
Permissions were updated the morning of 8/27 and are working now
