### ISSUE TITLE
Double locking in Intermediary

### ISSUE THREAD

**Issue by jcrichlake** [CDCgov/trusted-intermediary#1210]
# DevEx/OpEx

Priority: High

Inside of `TransformationRuleEngine.java` and `ValidationRuleEngine` we are checking `rules.isEmpty()` twice, once before the synchronized keyword and again afterward.  We need to remove the check before the synchronized keyword to satisfy the scan and not provide a false sense of security. 

## Additional Context

Add any other context or screenshots about the work here.

**Comment by halprin** [comment]
This might be able to be fixed with simply adding `volatile` keyword to the `rules` fields.

**Comment by JohnNKing** [comment]
PR is under review.

**Comment by JohnNKing** [comment]
PR: https://github.com/CDCgov/trusted-intermediary/pull/1228
