### ISSUE TITLE
Implement Azure Deployment Slots

### ISSUE THREAD

**Issue by saquino0827** [CDCgov/trusted-intermediary#1220]
# Story
As California, so that our results are not lost, I need Azure deployment slots to ensure Zero Downtime Deployment(ZDD).

## Pre-conditions
- [x] N/A

## Acceptance Criteria
- [x] We have Zero Downtime Deployments for our TI application code.
- [x] We have Zero Downtime Deployments for our RS SFTP Ingestion application code.
- [x] We have tested that we have minimal traffic loss during a zero downtime deployment.

### Research
- [x] *Research work needed to complete the story*
- [x] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [x] Implement Azure Deployment Slots
  - [x] For TI
  - [x] For ingestion service web app
- [x] Update GitHub actions to swap slots after deploy to lower slot
  - [x] For TI
  - [x] For ingestion service web app
- [x] Confirm Deployment Slots Swap and Function properly
  - [X] For TI
  - [X] For Ingestion Service Web App

Notes for letting pre-live be healthy but not handle traffic/events (having pre-live be healthy enables quickly rolling back by swapping slots manually):
- For TI, web traffic drives the app. Post-swap, the pre-live slot is unhealthy because it's missing DB creds. We should give both slots all the same app settings - either by putting them in a var that both reference, or just copy/pasta the values
- For Ingestion Service app, without the queues, the pre-live service is unhealthy after swap (`main.go` completes, and then restarts later). To keep it healthy, we could either:
  - Share all the settings like with TI, but have a different `env` value and check the `env` before reading queues (still need some kind of infinite loop to keep the app running)
  - Not share any more settings than we currently are, but add an infinite loop to `main` to keep the app up even when we don't have queues to use

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
  - [x] [Threat model](https://lucid.app/lucidchart/693ff5f9-c289-4585-9e74-a7f5abb36d69/edit?invitationId=inv_24d83a2b-b0fe-436d-8bd2-027b17beeb33) updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Unit test coverage of our code >= 80%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- Improving the time between database migrations and when a deployment slot comes active is out of scope of this ticket.

## Notes
- Create 2 slots for each app/function/environment (e.g. `live` and `pre-live`)
- Update deploy action to deploy app/function to the `pre-live` slot
- After deploy is complete, run swap action to move new code to `live` slot
- example command for slot swapping:
```
- name: Azure Swap Slots
uses: azure/CLI@v1
with:
inlineScript: |
az webapp deployment slot swap --slot xxx --name xxx --resource-group xxx
```

**Comment by saquino0827** [comment]
We have gotten the following working and tested in the Dev environment:
- TI Service Deployment slots and swapping functionality
- RS Ingestion Service Web App Deployment slots and swapping functionality
 
We are have deployment slots and GHA ready for the RS Ingestion Service Function App. We need to confirm the functionality works in Dev.

Afterwards, we need to test all functionality in Staging.

**Comment by somesylvie** [comment]
We ran into a bunch of errors trying to implement slots for the function app. Since the function app only runs intermittently, having a brief downtime for deploys won't impact outside callers, so we moved that to a separate ticket that can be completed after go live: https://github.com/CDCgov/trusted-intermediary/issues/1283

**Comment by halprin** [comment]
This now works for both services.  Yay!
