### ISSUE TITLE
CA sample ORU with `µ` character gets corrupted when accessed from "Daily Data" RS UI

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#1222]
# Bug

## Describe the Bug

When submitting [this ORU](/examples/CA/016_CA_ORU_R01_CDPH_produced_from_UCSD_order_189609160_0_initial_message.hl7) to RS in staging, which includes a `µ` character and is using UTF-8 charset, the `µ` character gets garbled when downloading the final HL7 file from ReportStream's staging "Daily Data" UI.

Important to note this doesn't happen when running the sample file locally. When testing locally, the character is preserved

## To Reproduce

1. Submit [016_CA_ORU_R01_CDPH_produced_from_UCSD_order_189609160_0_initial_message.hl7](/examples/CA/016_CA_ORU_R01_CDPH_produced_from_UCSD_order_189609160_0_initial_message.hl7) to RS staging waters API
2. Once delivered to its final destination, check the "Daily Data" page using `ucsd` as organization

## Expected Behavior

The final HL7 should show the `µ` character correctly

**Comment by JohnNKing** [comment]
Closing out in favor of #1229

**Comment by basiliskus** [comment]
I took a look at this issue today. Inspecting the browser response with the message content before it's downloaded, I can see the string encoded correctly. It seems the issue is happening in the [downloadjs](https://github.com/rndme/download) library the RS frontend is using to download to a file. The last release for that library was in 2017 and it has [an open issue regarding broken encoding of non-ASCII characters](https://github.com/rndme/download/issues/56). There's a workaround proposed there, but it seems we should create an issue for this in the RS repo for them to address more appropriately

**Comment by basiliskus** [comment]
Created this bug report in RS: https://github.com/CDCgov/prime-reportstream/issues/16309

Moving this story back into the backlog and adding the `blocked` tag. We're blocked with this one until the bug gets fixed in RS

**Comment by brick-green** [comment]
Chris said this should be completed by Nov 12 or 13

**Comment by basiliskus** [comment]
The PR has been merged. I tested it in staging and it's working as expected for me now
