### ISSUE TITLE
Enable ReportStream to work on Windows

### ISSUE THREAD

**Issue by jbiskie** [CDCgov/trusted-intermediary#1227]
## Describe the Bug

Currently, the ValidateYMLCommandTests unit test `no YAML files in directory` fails in Windows. Need to fix this and ensure ReportStream builds properly in Windows.

## Impact

Unable to run ReportStream properly in Windows.

## To Reproduce

In a Windows environment, run the unit test described above. The first assertion in the test (containing the forward slashes) fails.

## Expected Behavior

All unit tests should pass.

**Comment by jbiskie** [comment]
Link to PR: https://github.com/CDCgov/prime-reportstream/pull/15475

**Comment by jorg3lopez** [comment]
[PR ](https://github.com/CDCgov/prime-reportstream/pull/15475)was taken out of draft mode on Friday (08/16/2024)

**Comment by jorg3lopez** [comment]
No update, the [PR ](https://github.com/CDCgov/prime-reportstream/pull/15475)is still awaiting review.
