### ISSUE TITLE
Enable Infrastructure Encryption

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#1237]
# DevEx/OpEx

Azure Terraform Misconfiguration: Storage Account Missing Infrastructure Encryption.
Priority: Low.
In both applications, set infrastructure encryption to true for all `resource "azurerm_storage_account"`s

This will destroy and re-create these storage accounts.  Make sure there isn't anything that can't be permanently lost.

## Tasks

- [x] Enable infrastructure encryption for azurerm_storage_account's `docs` and `storage` resources

## Additional Context

Add any other context or screenshots about the work here.

**Comment by basiliskus** [comment]
Here's the [PR with the fixes](https://github.com/CDCgov/trusted-intermediary/pull/1258). Need to make sure nothing important will be permanently lost when re-creating the resources

**Comment by basiliskus** [comment]
Confirmed nothing important would be lost and deployed in staging. It will be deployed to production on next release (next Monday)

**Comment by halprin** [comment]
@basiliskus, mind doing this same change for RS SFTP Ingestion service too?

**Comment by basiliskus** [comment]
PR to add it to the SFTP Ingestion service: https://github.com/CDCgov/reportstream-sftp-ingestion/pull/132
