### ISSUE TITLE
DORA Metrics workflow failing 

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#1252]
# DevEx/OpEx

Error log [here](https://github.com/CDCgov/trusted-intermediary/actions/runs/10453249836/job/28943331866)

## Tasks

- [x] Something.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by somesylvie** [comment]
Fixed in https://github.com/CDCgov/trusted-intermediary/pull/1375
