### ISSUE TITLE
Struggle with Terraform Azure v4 Provider

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#1290]
# DevEx/OpEx

High level description of what what needs to be improved.

## Tasks

- [x] Update trusted-intermediary terraform.
- [x] Update sftp-ingestion terraform

## Additional Context

Add any other context or screenshots about the work here.

**Comment by jcrichlake** [comment]
As part of this work we will have to delete the container registries in a given environment.
