### ISSUE TITLE
Who is Ott's back-up, we need to find this out and document it.

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1317]
# DevEx/OpEx

Who is Ott's back-up, we need to find this out and document it.

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by csweet92** [comment]
I'll take this task

**Comment by csweet92** [comment]
Added a call out in the process doc:
https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0?pvs=4#b977afdc639145218f75563ab75eaf7f

**Comment by jcrichlake** [comment]
Verified the doc update and it looks good

**Comment by scleary1cs** [comment]
Significant overlap with task from second retro:
"Documentation: figure out who we should contact if Ott isn't around.  Update the documentation section of the incident process to include this."

**Comment by saquino0827** [comment]
Do we need a follow up task to review and update this section after Ott's contract period ends?

**Comment by csweet92** [comment]
Yeah, I'm going to put this back into the backlog for now

**Comment by pluckyswan** [comment]
Blocked until we have new Ott in place.

**Comment by csweet92** [comment]
@halprin Is it accurate to say at this point that there is no one back-filling Ott's position?

**Comment by halprin** [comment]
Correct, @csweet92.  We have an item in the TI/RS sync meeting to go over how we will work with RS when it comes to a) helping us during incidents, and b) how we formally transfer an incident over to them.  That topic is specific to the new "no Ott or backfill" world we live in now.  So, once we have that information, we can update the incident response process document and close this card.

**Comment by scleary1cs** [comment]
Closing this story.  Created #1447  and #1448 to replace.
