### ISSUE TITLE
Finish up making the incident log into a Notion database.

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1318]
# DevEx/OpEx

Finish up making the incident log into a Notion database.

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by csweet92** [comment]
I believe this task is complete. @somesylvie can you confirm?

**Comment by somesylvie** [comment]
I think we're good, other than we should delete the old template (once someone-other-than-me agrees it's sufficiently copied) and figure out how we want to do this thing now: <img width="1030" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3o4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--429d106a076e21bff8b835b01fe1e16564f891a0/image.png" alt="image.png" />

**Comment by csweet92** [comment]
@somesylvie Is this in regards to the the database view or the individual incident logs?
