### ISSUE TITLE
Run book about top three areas to check.  

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1320]
# DevEx/OpEx

Run book about top three areas to check.  For example, TI logs, RS SFTP logs, and RS app insights.

## Tasks

- [x] Add [runbook](https://www.notion.so/flexion-cdc-ti/Top-3-Troubleshooting-6e2019c8b2704ffbae1e8d5867593975) for logs.
  - [x] sftp-ingestion
  - [x] ti
- [x] Add [runbook](https://www.notion.so/flexion-cdc-ti/Top-3-Troubleshooting-6e2019c8b2704ffbae1e8d5867593975) for app insights.
  - [x] reportstream

## Additional Context

Add any other context or screenshots about the work here.

**Comment by pluckyswan** [comment]
Jeff and Sam reviewed and approved.

**Comment by pluckyswan** [comment]
Sylvie reviewed and approved.
