### ISSUE TITLE
Run book for how to rotate a secret. 

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1321]
# DevEx/OpEx

Run book for how to rotate a secret.  For example, we ran into the gotcha that we also need to restart the service afterward to start using that rotated secret.

## Tasks

- [x] Add [page](https://www.notion.so/flexion-cdc-ti/Rotating-a-secret-3bc06d2ee35b468cbd0b96580fe84564) under Run Books section.
- [x] Add links to helpful resources
- [x] Add steps
    - [x] sftp-ingestion
    - [x] ti 

## Additional Context

Add any other context or screenshots about the work here.

**Comment by pluckyswan** [comment]
Asked Peter for clarification on document. As of 09/13/2024, doc reflects desired purpose.
