### ISSUE TITLE
Run book for sending messages to a deployed environment.  

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1324]
# DevEx/OpEx

Run book for sending messages to a deployed environment.  Could reference the updated hurl scripts.

## Tasks

- [x] Add [run book](https://www.notion.so/flexion-cdc-ti/Sending-messages-to-staging-or-production-a2d32ec0de0b4e7480f03267302a60e0) with steps.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by pluckyswan** [comment]
This is for testing if fixes work, not for sending the fixed real file according to Peter.

**Comment by pluckyswan** [comment]
Basilio, Sylvie, and Jeff reviewed and approved.
