### ISSUE TITLE
Update incident response process to isolate per-incident communication so the main channel doesn't become too cluttered.

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1325]
# DevEx/OpEx

Update incident response process to isolate per-incident communication so the main channel doesn't become too cluttered (e.g. a temporary room or thread; possibly created via PagerDuty; as a way to handle multiple in-progress incidents).
## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by csweet92** [comment]
I'm happy to take this one

**Comment by csweet92** [comment]
I added a call out to this block about creating Slack threads for multiple incidents
https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0?pvs=4#240ccfc9d5854a36bfefda40640f7b32

**Comment by saquino0827** [comment]
Here is a link to the block with the updates: https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0?pvs=4#10b5955365f580149c39e88331bf882e

**Comment by saquino0827** [comment]
I reviewed the section and this change looks good.

**Comment by pluckyswan** [comment]
Section looks good.
