### ISSUE TITLE
Do not cache bad keys.

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1326]
# DevEx/OpEx

Make DevEx/OpEx backlog item for bad keys not to be cached.

## Tasks

- [x] Update TI service's caching system to remove cache'd token when an Invalid Token is caught. @saquino0827 

## Additional Context

Root cause for session 1 during game day exercises.

**Comment by saquino0827** [comment]
A PR is open here: https://github.com/CDCgov/trusted-intermediary/pull/1333/files

**Comment by saquino0827** [comment]
The PR has been merged.
