### ISSUE TITLE
Figure out if there is ever a time we need to e-mail a security stakeholder at the CDC if the incident is security related. 

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1329]
# DevEx/OpEx

Figure out if there is ever a time we need to e-mail a security stakeholder at the CDC if the incident is security related.  And find out who that is.  Our ISSO?  Update the communication documentation with findings.

## Tasks

- [x] Update who to notify.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by pluckyswan** [comment]
Might get more info. on this with 1313

**Comment by jherrflexion** [comment]
Notion updated with comments about who/when to contact people. See here: 
https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0?pvs=4#1185955365f5806ebcb3c48975818908

**Comment by sfradkin** [comment]
@pluckyswan There are some comments in this section in Notion.  I also added a comment.

**Comment by halprin** [comment]
@pluckyswan, yeah, your changes look good to me.
