### ISSUE TITLE
Improve the documentation to indicate when an incident is resolved, and an all clear can be given.

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1330]
# DevEx/OpEx

Improve the documentation to indicate when an incident is resolved, and an all clear can be given.  Remember, resolving the incident is not necessarily the same as permanently fixing the issue.

## Tasks

- [x] Update types of incidents in [doc](https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0?pvs=4#3fdccf04019d4639977d4146aad39c34).

## Additional Context

Add any other context or screenshots about the work here.

**Comment by pluckyswan** [comment]
Worked with Jeff. James and Peter reviewed and approved.
