### ISSUE TITLE
Add a sub-page under the Resources page to outline the RS retry mechanism.

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1331]
# DevEx/OpEx

Add a sub-page under the Resources page to outline the RS retry mechanism.

## Tasks

- [x] Look into RS retry mechanism for the ETOR use-case.
- [x] Add document this page in notion.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by saquino0827** [comment]
Got a thumbs up review from @jherrflexion
