### ISSUE TITLE
🐞 - `.hl7` files are not deleted from SFTP after moving them to our own Azure storage account.

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1337]
# Bug

- [x] `.hl7` files are not deleted from SFTP after moving them to our own Azure storage account.

A clear and concise description of what feature is not working.

## Impact

Please describe the impact this bug is causing to you.

## Logs

If applicable, please attach logs to help describe your problem.

## Version

The version or git commit sha of the application that the bug found on.

**Comment by jcrichlake** [comment]
I did some early digging into this.  I confirmed that the test service account can delete files via the command line.

**Comment by pluckyswan** [comment]
[PR](https://github.com/CDCgov/reportstream-sftp-ingestion/pull/176) is open for this.

**Comment by pluckyswan** [comment]
PR merged.
