### ISSUE TITLE
Determine whether we should use the `schedule: { adjustForDST: true }` setting in the timer

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1338]
# DevEx/OpEx

Determine whether we should use the `schedule: { adjustForDST: true }` setting in the timer

## Tasks

- [x] Research option and/or alternatives
- [x] Implement

## Additional Context

Add any other context or screenshots about the work here.

**Comment by pluckyswan** [comment]
Decided to use WEBSITE_TIME_ZONE in function app instead.

**Comment by pluckyswan** [comment]
[PR](https://github.com/CDCgov/reportstream-sftp-ingestion/pull/174) is out for review

**Comment by pluckyswan** [comment]
PR merged.
