### ISSUE TITLE
Threat Model: IG Removed

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#1340]
# DevEx/OpEx

Now that the IG has been removed, we can update the threat model in Lucidchart accordingly. 

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by jorg3lopez** [comment]
@JohnNKing Can we close this? I think @halprin (Peter) updated the threat model already.

**Comment by JohnNKing** [comment]
Yep! Looks good to me. Closing...
