### ISSUE TITLE
Improve our incident management process documentation (the incident log section)

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1349]
# DevEx/OpEx

Improve our incident management process documentation (the incident log section) to include some prose on what makes a good log or log statement.  E.g. "James searched logs" isn't helpful.  "James searched the TI logs and found the reportId of 1234" is more useful.

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by csweet92** [comment]
I added this call out to our "Creating an incident log" page:
https://www.notion.so/flexion-cdc-ti/Creating-a-new-incident-log-8537dc35020242e6852502328a60c2ca?pvs=4#10b5955365f5800c9977d25152e8fcf7

**Comment by csweet92** [comment]
@scleary1cs @pluckyswan Y'all wanna take a look at this?

**Comment by scleary1cs** [comment]
Looking today @csweet92 .

**Comment by scleary1cs** [comment]
@csweet92 looks good to me.  Hopefully we can have another game day exercise and get another run through the process and get some "in the moment" feedback.

**Comment by scleary1cs** [comment]
<img width="951" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHNxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e58ce7f66c05ea105539f9568b180465dd58c0bf/Screenshot%202024-10-07%20at%2012.37.27%E2%80%AFPM.png" alt="Screenshot 2024-10-07 at 12.37.27 PM.png" />
