### ISSUE TITLE
Clarify Incident Commander's responsibilities

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1351]
# DevEx/OpEx

Clarify Incident Commander's responsibilities; what are their top priorities?

## Tasks

- [x] Gain feedback on existing [section](https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0?pvs=4#bbd8b0e255a44cf3b597bc97aaa8cf39).

## Additional Context

Add any other context or screenshots about the work here.

**Comment by csweet92** [comment]
It looks like this has been defined in the process doc:
https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0?pvs=4#1065955365f5806ab739e1a7b7326619

**Comment by saquino0827** [comment]
It looks good to me, I can't think of anything else it may be missing.

**Comment by halprin** [comment]
This looks good to me.

**Comment by pluckyswan** [comment]
Existing section was approved.
