### ISSUE TITLE
Add a custom exception class that can be thrown by transformations when there is a failure

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1356]
# Design or Research

Add a custom exception class that can be thrown by transformations when there is a failure

## Tasks

- [ ] Something.

## Additional Context

https://flexion.slack.com/archives/C055XTF22B0/p1726762760557609

**Comment by pluckyswan** [comment]
Closed because YAGNI. When there is a card or requirement that sparks this, right now we don't have a use for it, it can be recreated later.
