### ISSUE TITLE
Azure Alerts for Errors - CDC TI services are down/offline

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1398]
# Story
As a developer, I need to know if our services are down/offline, so that we can begin an incident.

## Pre-conditions
- [ ] *Assumptions of prior or future work that's out of scope for this story*

## Acceptance Criteria
- [x] Alerts trigger when the TI and/or Ingestion Service are down. After discussion, we decided to base this on whether there are an appropriate number of healthy instances - if instances can't stay up/healthy, the service is not working

###  Engineering
- [x] Alerts are set up that trigger if TI is down
- [x] Alerts are set up that trigger if Ingestion Service is down

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [TI Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) or [Ingestion Service threat model](https://lucid.app/lucidchart/693ff5f9-c289-4585-9e74-a7f5abb36d69/edit) updated
  - [x] API documentation updated
- [x] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Additional e2e tests created
  - [x] Additional RS e2e assertions created in the `rs-e2e` project for any new transformations.  Includes improvements to the assertion code required to make the new assertions
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- This story came out of #1379, and #1380.

**Comment by pluckyswan** [comment]
I believe this is covered by #1397

**Comment by JohnNKing** [comment]
Already complete?

**Comment by pluckyswan** [comment]
Alert was successfully activated and deactivated in both repos. We are currently considering how to handle the ADR for Azure Alerts (duplicate them in both repos, exist only in one repo, etc).

**Comment by pluckyswan** [comment]
ADR was added to both repos.
