### ISSUE TITLE
Azure Alerts for Errors - high memory usage

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1401]
# Story
As a developer, I need to be alerted on high memory usage (CDC TI, SFTP, & database), so that we can begin investigation. 

## Acceptance Criteria
- [x] High memory usage alerts are configured where appropriate

## Notes
Context: Early warning sign for something going wrong. May also impact response times.

###  Engineering
- [x] High memory alerts for TI web app are configured
- [x] High memory alerts for TI db are configured @jcrichlake 
- [x] High memory alerts for ingestion service web app are configured

## Definition of Done
- [x] Build & Deploy tasks completed
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- This story came out of #1379, and #1380.

**Comment by jherrflexion** [comment]
Starting
