### ISSUE TITLE
Combine docker-compose.yml files in TI

### ISSUE THREAD

**Issue by tjohnson7021** [CDCgov/trusted-intermediary#1423]
# DevEx/OpEx

Update base docker-compose TI to stand up the db as well as the TI app in Docker instead of having to run 2 commands

## Tasks

- [x] Combine files and run load tests. 

## Additional Context
- https://flexion.slack.com/archives/C055XTF22B0/p1713382055379129
Add any other context or screenshots about the work here.

**Comment by jherrflexion** [comment]
Starting
