### ISSUE TITLE
Document Ott’s Best Practices from 1 hour session

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1426]
# Design or Research
Document Ott’s Best Practices from 1 hour session on 10/10/2024.

## Tasks

- [x] Document session in [notion](https://www.notion.so/flexion-cdc-ti/Ott-s-Best-Practices-11c5955365f580569842d47539f5af9b#11f5955365f5800c87a2fad35c5481ad).

## Additional Context

https://www.notion.so/flexion-cdc-ti/Ott-s-Best-Practices-11c5955365f580569842d47539f5af9b#11f5955365f5800c87a2fad35c5481ad

**Comment by pluckyswan** [comment]
James reviewed and approved.

**Comment by scleary1cs** [comment]
Follow up session scheduled for 10/17/2024 at 3:00 PM EDT. 

Ott's message:
" I just completed the  **documentation for ReportStream and ETOR**.  And, I also have another good advice of how to generate and test message locally without going to Azure.  I use it.  It is very affective and good to know.  Would you like to get together again once more session meeting?  I will go over the doc and demo it to you all."

**Comment by saquino0827** [comment]
@pluckyswan reviewed and left a comment. Once that's addressed, it's good to go from my POV.
