### ISSUE TITLE
Ott knowledge transfer part II

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1449]
# Design or Research

Ott knowledge transfer part II

## Tasks

- [ ] Something.

## Additional Context

Ott reached out with:
"I just completed the  documentation for ReportStream and ETOR.  And, I also have another good advice of how to generate and test message locally without going to Azure.  I use it.  It is very affective and good to know.  Would you like to get together again once more session meeting?  I will go over the doc and demo it to you all."

Second session scheduled for 10/17/2024.  Added to team calendar and session will be recorded.

**Comment by scleary1cs** [comment]
[Flexion-Training.postman_collection.json](https://github.com/user-attachments/files/17421316/Flexion-Training.postman_collection.json)
[Documentation for ETOR Newborn Screening Project.pdf](https://github.com/user-attachments/files/17421317/Documentation.for.ETOR.Newborn.Screening.Project.pdf)
[Reportstream Processing and testing message locally.pdf](https://github.com/user-attachments/files/17421315/Reportstream.Processing.and.testing.message.locally.pdf)

**Comment by scleary1cs** [comment]
[Setting for message to route to local sftp.txt](https://github.com/user-attachments/files/17421356/Setting.for.message.to.route.to.local.sftp.txt)

**Comment by scleary1cs** [comment]
Water API to load public keys (from @basiliskus):
./prime organization addkey --env staging --public-key /path/to/public/key.pem --scope "flexion.*.report" --orgName flexion --kid flexion.simulated-hospital --doit
./prime organization addkey --env staging --public-key /path/to/public/key.pem --scope "flexion.*.report" --orgName flexion --kid flexion.etor-service-sender --doit
./prime organization addkey --env staging --public-key /path/to/public/key.pem --scope "flexion.*.report" --orgName flexion --kid flexion.simulated-lab --doit

**Comment by scleary1cs** [comment]
Above documents also uploaded to our [google drive](https://drive.google.com/drive/folders/15Et7J4EmMEnXA8_Asg_M4-gDTt5NbNKG?usp=drive_link).

**Comment by scleary1cs** [comment]
Basilio (from chat):
"I have a question about the folders in the azure container. I think a couple of new folders have been recently added (I think the -filter ones?). Is there some up to date documentation where we can see the RS pipeline steps and its corresponding folders?  Does the `ready` folder correspond to the `send` step, for example?" 

Brick (in chat):
"There are architecture diagrams that Arnej maintains. They’re not published anywhere so we’d have to ask him to share. I can take that"

**Comment by scleary1cs** [comment]
Gilmore (from chat):
prime-router/docs/universal-pipeline/README.md

**Comment by scleary1cs** [comment]
[FHIR Pipeline Architecture v4 - March 20 2024 - Overall Arch.pdf](https://github.com/user-attachments/files/17422507/FHIR.Pipeline.Architecture.v4.-.March.20.2024.-.Overall.Arch.pdf)

**Comment by scleary1cs** [comment]
[Ott - Triaging Best Practices (Part II) recording.](https://drive.google.com/file/d/1pgkgzcPigUI1gVZ_EORuay7aBuntJ1e3/view?usp=drive_link)

**Comment by basiliskus** [comment]
@scleary1cs Can you take a look at this one? Can we close it?
