### ISSUE TITLE
Update Incident Log Section with examples

### ISSUE THREAD

**Issue by brick-green** [CDCgov/trusted-intermediary#1450]
# Backlog Task

Improve our incident management process documentation (the incident log section) to include some prose on what makes a good log or log statement.  E.g. "James searched logs" isn't helpful.  "James searched the TI logs and found the reportId of 1234" is more useful.

## Completion Criteria

- [ ] Incident Log section of the Process page in Notion has been updated

## Tasks

- [ ] Add examples to the Incident Log section

## Other Notes

- [Incident Process page](https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0)

**Comment by csweet92** [comment]
@brick-green Is this ticket a duplicate of https://github.com/CDCgov/trusted-intermediary/issues/1328?

**Comment by brick-green** [comment]
> @brick-green Is this ticket a duplicate of #1328?

@csweet92 I don't think these are duplicates. This ticket is meant to give more guidance for an incident commander on how they should be logging the tasks that they complete during the incident response. Those logs would just be for our internal purposes. #1328 seems to be more about how we communicate out to the external partners about an incident.

**Comment by brick-green** [comment]
> Sorry, wrong ticket number. I meant this closed ticket #1349

Oh yep definitely looks like a duplicate! Good call :) closing
