### ISSUE TITLE
Leading zeros in OBX-5 for NM data type cause exception in RS when converting to FHIR

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/trusted-intermediary#1454]
# Bug

## Describe the Bug

When an OBX segment has a data type of "NM" in OBX-2 and the result value in OBX-5 contains leading zeros, the resulting fhir bundle contains an invalid value for "Bundle.entry.resource.ofType(Observation).valueQuantity.value".

example HL7 segment: 

OBX|1|NM|38473-5^17-Hydroxyprogesterone^LN|1|065.88|nmol/L|<85|N|||F|||20241015055726

example converted FHIR Resource:

`{
            "fullUrl": "Observation/1729104155244834642.39eac40b-c44b-4d07-b4bb-8b96ade62411",
            "resource": {
                "resourceType": "Observation",
                "id": "1729104155244834642.39eac40b-c44b-4d07-b4bb-8b96ade62411",
                "extension": [
                    {
                        "url": "https://reportstream.cdc.gov/fhir/StructureDefinition/sub-id",
                        "valueString": "1"
                    },
                    {
                        "url": "https://reportstream.cdc.gov/fhir/StructureDefinition/obx-observation",
                        "extension": [
                            {
                                "url": "OBX.2",
                                "valueId": "NM"
                            },
                            {
                                "url": "OBX.6",
                                "valueCodeableConcept": {
                                    "coding": [
                                        {
                                            "extension": [
                                                {
                                                    "url": "https://reportstream.cdc.gov/fhir/StructureDefinition/cwe-coding",
                                                    "valueString": "coding"
                                                }
                                            ],
                                            "code": "nmol/L"
                                        }
                                    ]
                                }
                            },
                            {
                                "url": "OBX.11",
                                "valueString": "F"
                            }
                        ]
                    }
                ],
                "status": "final",
                "code": {
                    "coding": [
                        {
                            "extension": [
                                {
                                    "url": "https://reportstream.cdc.gov/fhir/StructureDefinition/cwe-coding",
                                    "valueString": "coding"
                                },
                                {
                                    "url": "https://reportstream.cdc.gov/fhir/StructureDefinition/cwe-coding-system",
                                    "valueString": "LN"
                                }
                            ],
                            "system": "http://loinc.org",
                            "code": "38473-5",
                            "display": "17-Hydroxyprogesterone"
                        }
                    ]
                },
                "subject": {
                    "reference": "Patient/1729104154973770467.0f02574a-aaca-4e07-9989-d810f3a7d499"
                },
                "effectiveDateTime": "2024-10-15T05:57:26Z",
                "_effectiveDateTime": {
                    "extension": [
                        {
                            "url": "https://reportstream.cdc.gov/fhir/StructureDefinition/hl7v2-date-time",
                            "valueString": "20241015055726"
                        }
                    ]
                },
                "valueQuantity": {
                    "value": 065.88,
                    "unit": "nmol/L"
                },
                "interpretation": [
                    {
                        "coding": [
                            {
                                "extension": [
                                    {
                                        "url": "https://reportstream.cdc.gov/fhir/StructureDefinition/cwe-coding",
                                        "valueString": "coding"
                                    }
                                ],
                                "code": "N"
                            }
                        ]
                    }
                ],
                "referenceRange": [
                    {
                        "text": "<85"
                    }
                ]
            }
        }`

This occurs because leading zeros are not explicitly invalid in HL7 V2 NM data type (https://hl7-definition.caristix.com/v2/HL7v2.7/DataTypes/NM)
![image](https://github.com/user-attachments/assets/86e4c993-dfbd-4ddb-a095-ba65208936b1), however when this is converted to FHIR per the hl7V2 -> FHIR documentation (https://build.fhir.org/ig/HL7/v2-to-fhir/ConceptMap-segment-obx-to-observation.html) this becomes a ValueQuantity.value element (https://hl7.org/fhir/R4/datatypes.html#Quantity) with  a primitive type of decimal,
![image](https://github.com/user-attachments/assets/aa847372-4aa2-44d4-9f60-2e8f9ba67907)
![image](https://github.com/user-attachments/assets/27facc47-a4f0-4002-a14d-fb6873ba4e80)
 which does not allow leading zeros (https://www.w3.org/TR/xmlschema-2/)
![image](https://github.com/user-attachments/assets/b02673da-301b-4262-b85d-76ab002d9721)

## Impact

When an HL7 V2 message is sent into ReportStream and converted to FHIR exception "ca.uhn.fhir.parser.DataFormatException: HAPI-1861: Failed to parse JSON encoded FHIR content: Invalid numeric value: Leading zeroes not allowed at [line: 1, column: 137695]" is thrown when attempting to parse the FHIR bundle to apply the jurisdictional filters.

## To Reproduce

1. Send an HL7 v2 ORU file to RS that contains an OBX with an NM data type and leading zeros in OBX-5

## Expected Behavior
The resulting FHIR resource from a converted HL7 v2 message should not contain invalid values and should not throw an error when reaching the destination-filter step

## Acceptance Criteria
- [x] OBX-5 fields with NM data types will have leading zeroes truncated
- [x] A sample ORU message sent by ReportStream staging to the UCSD receiver is filed successfully by their EHR test environment with all OBX-5 values preserved with theexception of leading zeros.
- [x] Assertions added to RS e2e tests that check leading zeroes are truncated appropriately

###  Engineering
- [x] Create RS sender transform to truncate leading zeroes and add  to ca-phl.etor-nbs-results sender
- [x]  Test End2End with CA and UCSD
- [x]  Add assertions to RS e2e tests for UCSD

**Comment by GilmoreA6** [comment]
After further research, RS does not use the LINUX4HEALTH HL7->FHIR mappings (https://github.com/LinuxForHealth/hl7v2-fhir-converter/tree/master/src/main/java/io/github/linuxforhealth/hl7) unless the message type is not mapped in RS (i.e. ADT-A04 would use the LINX4HEALTH library but ORU_RO1 would not). For the NM data type for OBX.5 RS is simply taking the string value of the inbound OBX.5 and placing it into the valueQuantity.value fhir element.

This limits our potential options to solve the leading zero issue to the following:

1.) Ask RS to change how it is converting the OBX.5 value for the NM data type to a valueString FHIR element in a new custom extension.
Pros:
- retains original value that was sent in OBX-5
- applies to all senders uniformly without further configuration needed
Cons:
- does not follow official hl7 V2 -> fhir mappings
- timeline for implementation unclear as it requires RS agreement

2.) Create sender transform that moves value in valueQuantity,value to valueString element on same observation resource
Pros:
- retains original value that was sent in OBX-5
Cons:
- does not follow official hl7 V2 -> fhir mappings
- requires both a sender and a receiver transform

3. Create a sender transform that removes leading zeroes in valueQuantity.value
Pros:
- Easy to implement and change
- requires only a sender transform
- makes value conform to FHIR R4 standard
Cons:
- does not maintain original value sent by sender
- transform needs to be applied to each sender in sender settings individually

**Comment by GilmoreA6** [comment]
After discussion at engineering sync, option 3 was decided upon for the time being. This does not prevent us from continuing to pursue other options. PR for option 3 opened and approved with RS: https://github.com/CDCgov/prime-reportstream/pull/16296

**Comment by GilmoreA6** [comment]
Transform added to ca-phl.etor-nbs-results sender in RS staging. ![Image](https://github.com/user-attachments/assets/904ff52b-f604-4b82-861d-37a89ea38471)

**Comment by GilmoreA6** [comment]
Round trip test was conducted with ETOR and RS staging environments which confirmed leading zeroes were truncated appropriately and no other values were affected. Additional test will be performed on 10/23/24 with UCSD and CA at the regular weekly SME call.

**Comment by basiliskus** [comment]
Added the transform to ca-phl. etor-nbs-results in our open PR in RS: https://github.com/CDCgov/prime-reportstream/pull/16064/commits/5c388cdc6738b7ce3f80069e9ebf93b660277eac

**Comment by GilmoreA6** [comment]
Added draft PR for RSe2e tests https://github.com/CDCgov/trusted-intermediary/pull/1487/files

**Comment by GilmoreA6** [comment]
PR approved and merged. Example file from CDPH from 10/22/28 had correct truncations
