### ISSUE TITLE
Receiving FHIR Demographics via REST

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#148]
# Story
As a hospital, so that my NBS order demographic data can be transmitted to a public health lab, I need the receiver to be able to accept FHIR data via REST.

## Pre-conditions
- Only a single, fake hospital is supported.
- The received data is assumed to be correctly formatted and valid in terms of required fields and data types.

## Acceptance Criteria

- [x] Demographic data must be transmitted securely in non-development environments.
- [x] The hospital receives confirmation that the newborn demographic data was successfully received (by the CDC; not the lab).
- [x] If the hospital user provides valid login information, they are allowed to submit newborn demographic data.
- [x] If the hospital user does not provide valid login information, any attempt to submit newborn demographic data results in an access denied error.

### Research
~~- [ ] Investigate with the ReportStream team possibilities for creating a shared Auth service~~

###  Engineering
- [x] Get ReportStream public key
- [x] Caching
    - [x] Create caching class @jorg3lopez @tjohnson7021 
    - [x] Refactor ReportStreamLabOrderSender to use caching class @jorg3lopez 
- [x] Onboard RS client using YAML file @basiliskus @jorg3lopez @JohnNKing 
   - [x] Add implementation to read YAML file into object @basiliskus 
   - [x] Create Organization and OrganizationsLoader class @basiliskus 
   - [x] Validate sender id exists in organizations.yaml @basiliskus
- [x] Add the authentication endpoint the ReportStream will call [ POST /v1/auth ]
   - [x] Determine our bearer token format (JWT?), and whether ReportStream supports short term JWTs. @jorg3lopez 
   - [x] Create endpoint @JohnNKing 
   - [x] Check if user and credentials are valid @JohnNKing 
   - [x] Generate session token @JohnNKing 
   - [x] Get keys (e.g. RS public, TI private) from Azure Key Vault and/or cache @jorg3lopez, @halprin 
   - [x] Change how we load organizations. - @halprin 
   - [x] Harden the AuthController's parsing of the request body. - @halprin
   - [x] Enhance `LocalSecrets` to also read from the Java resources if the local file doesn't work. - @halprin 
   - [x] AuthCotroller needs to return the JWT in a JSON blob similar to how RS does it. @jorg3lopez 
   - [x] Unit tests for exceptions, POJOs, and the usecase - @halprin, @JohnNKing 
   - [x] JavaDocs - @halprin 
   - [x] Check that we can parse the request, and if not, return a 400 HTTP status code. - @halprin 
- [x] OpenAPI documentation for the new endpoint. - @tjohnson7021 
- [x] End-to-end tests. - @basiliskus 
- [x] Enforce a valid bearer token on our demographics endpoint. @jorg3lopez, @halprin 
- [x] Update the OpenAPI documentation for our demographics endpoint to indicate it requires an API key. - @tjohnson7021 @basiliskus 
- [x] Improve `Formatter` with library-agnostic type references. - @halprin @basiliskus  
- [x] Create ReportStream public key for the key vault in Terraform. - @JohnNKing 
- [x] Create TI public for the key vault in Terraform. - @JohnNKing 
- [x] Upload ReportStream's actual public key to the key created in the above task.
- [x] Consider using a `HashMap` for storing the `Organization`s in `OrganizationsSettings`. - @basiliskus @tjohnson7021 
- [x] Change the name of the TI's private key secret name. - @halprin 

## Definition of Done
- [x] Threat model updated - @JohnNKing 
- [x] Code refactored for clarity and no design/technical debt
- [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies.
- [x] Source code is merged to the main branch. @jorg3lopez
- [x] Unit test coverage of our code >= 90%
- [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer.
- [x] Build process updated
- [x] Feature toggles created and/or deleted.  Document the feature toggle.
- [x] Source code documentation created when the code is not self-documenting. @tjohnson7021 
- [x] API documentation generated
- [x] Code quality checks passed @basiliskus 
- [x] Security & privacy gates passed
- [x] Load tests passed @basiliskus @tjohnson7021 
  - [x] Configure load test for /v1/auth endpoint 
  - [x] Configure load test for authenticated demographics endpoint @basiliskus @tjohnson7021
  - [x] Handle token expiration @basiliskus 
  - [x] Assess and re-run load tests once final PR is merged @tjohnson7021 @basiliskus 
- [x] Documentation and diagrams created or updated
  - [x] Implementation guide (`ig` folder) - @halprin 
  - [x] ADRs (`adr` folder) - @halprin 
  - [x] Main `README.md` @tjohnson7021 
  - [x] Other readme's in the repo.
- [x] API(s) are versioned
- [x] Debug logging

## Research Questions 
- What format of reply should be sent back by TI if the message is accepted?

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by jorg3lopez** [comment]
Note:
response:
{"sub":"client name", "access_token":"ACCESS-TOKEN-STRING","token_type":"bearer","expires_in":300,"scope":"clienttest.*.report"}

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-40 - Intermediaries should enable to server-to-server access so that other systems have access to call it

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-42 - Intermediaries will need at least one authentication mechanism for server-to-server access
