### ISSUE TITLE
SonarCloud findings

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1531]
## Spike Goal
Look at SonarCloud findings and determine what finding should be fixed before CA go live. 

## Timebox
1 Day

## Notes
A new backlog task should be created for each item to be addressed.

**Comment by jherrflexion** [comment]
Started this morning

**Comment by jherrflexion** [comment]
Reviewed. Second review by @halprin. We determined no items are necessary for go-live. Moving to done.

**Comment by halprin** [comment]
> Reviewed. Second review by @halprin. We determined no items are necessary for go-live. Moving to done.

And for those digging through this issue later, that doesn't mean that the current items aren't worth doing.  It just means the aren't worth doing before CA go-live.

**Comment by scleary1cs** [comment]
This seems great, thanks for verifying @jherrflexion and @halprin .
