### ISSUE TITLE
Add documentation to Automated Test's readme

### ISSUE THREAD

**Issue by basiliskus** [CDCgov/trusted-intermediary#1540]
# DevEx/OpEx

Things to add to readme:
- Instructions on how to test new assertions from a new branch/PR
- checking for internal open/close quotes in json
- making tests fail on purpose as a gut check that they're running as expected/not passing because they're being filtered out

## Tasks

- [x] Something.

## Additional Context

https://flexion.slack.com/archives/C055XTF22B0/p1727717357268009

**Comment by jherrflexion** [comment]
Starting
