### ISSUE TITLE
ORM NK1 Segment Support

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/trusted-intermediary#1547]
# Story
As a LA sender I need to be able to send nonstandard ORM_001 messages that contain NK1 segments

## Context
Add ReportStream functionality that allows NK1 segment sent in ORM messages to convert to RelatedPerson FHIR resources

## Acceptance Criteria
- [ ] ORM_001 message with NK1 segment is sent to ReportStream and translates to FHIR message with  RelatedPerson resource(s).
- [ ] Sample HL7 OML NK1 segments sent out of ReportStream exactly match the incoming ORM NK1 content.

### Research
- [ ] How does ReportStream want to accomplish this?
- [ ] Should ReportStream have a sender setting that allows specifying which HL7 message structure to use?

###  Engineering
- [ ] New Sender setting added to RS to allow specifying which HL7 message structure to use
- [ ] New ORM_001_Oschner HL7 message structure added to ReportStream

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Additional e2e tests created
  - [ ] Additional RS e2e assertions created in the `rs-e2e` project for any new transformations.  Includes improvements to the assertion code required to make the new assertions
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

**Note**: Please remove any DoD items that are not applicable

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by brick-green** [comment]
Blocker on research question. Split out to different ticket:

Can LA-Oschner not send an OML_021 message from their EPIC system?

**Comment by JohnNKing** [comment]
This one is likely to be pulled into the next sprint, but the team was hesitant to commit to this being completed in the sprint's timeframe, so I'm leaving it in the product backlog for now.

**Comment by brick-green** [comment]
I think we should confirm with Epic about the ability to change MSH.9. If they can change it to OML then we should just be treating the messages as OML which would already include mapping for NK1.

**Comment by basiliskus** [comment]
We're currently waiting to hear if Ochsner can change MSH-9 message type to be OML. If they can, then the mapping already works in RS

**Comment by brick-green** [comment]
Ochsner made the change and sent a new message. See comment [here](https://github.com/CDCgov/trusted-intermediary/issues/900#issuecomment-2479555354)

**Comment by basiliskus** [comment]
We could close this story if not needed now that we know we'll get NK1 in an OML message instead of ORM

**Comment by GilmoreA6** [comment]
Closing as this ticket is no longer needed
