### ISSUE TITLE
SFTP Configuration Spike

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1553]
## Spike Goal
Design/plan configuration for the ingestion service. The SFTP CA Flag [#1082](https://github.com/CDCgov/trusted-intermediary/issues/1082) will be the first configuration item to implement.

## Timebox
3 days 

## Notes
- Additional context [here](https://www.notion.so/flexion-cdc-ti/Thinking-about-config-eb9424dafea14320be5cee1b8b03d890)

**Comment by somesylvie** [comment]
Plan summarized here: https://www.notion.so/flexion-cdc-ti/Brainstorming-for-config-spike-1425955365f58011a8e1e7419fd4ce87?pvs=4#1435955365f5801ea83dd2a0c508aa91
