### ISSUE TITLE
Add index to HL7 parser used for e2e tests

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/trusted-intermediary#1595]
Assertions for E2E tests currently can only check the first repetition of any segment or field. We need to add indexing to the parser so we can check specific repetitions for values

**Comment by basiliskus** [comment]
May relate to: https://github.com/CDCgov/trusted-intermediary/issues/1532

**Comment by GilmoreA6** [comment]
Determined we do not need this now as we are shifting to a "golden copy" testing strategy"
