### ISSUE TITLE
Processing Specimen ID

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#182]
# Story
As a public health lab, to be able to make use of received electronic NBS orders, I need the specimen ID included with the order.

## Pre-conditions
- Each specimen ID is provided on the NBS specimen card.
- Each specimen ID is unique per state.
- The specimen ID is included as part of an incoming order.
- The specimen ID is alphanumeric

## Acceptance Criteria
- The specimen ID from the hospital is received by the lab. (I.e. included in the outgoing OML order)

### Research
- [ ] *Research work needed to complete the story*

###  Engineering
- [ ] *Engineering work needed to complete the story*

## Definition of Done
- [ ] Threat model updated
- [ ] Code refactored for clarity and no design/technical debt
- [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies.
- [ ] Source code is merged to the main branch.
- [ ] Unit test coverage of our code >= 90%
- [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer.
- [ ] Build process updated
- [ ] Feature toggles created and/or deleted.  Document the feature toggle.
- [ ] Source code documentation created when the code is not self-documenting.
- [ ] API documentation generated
- [ ] Code quality checks passed
- [ ] Security & privacy gates passed
- [ ] Load tests passed
- [ ] Documentation and diagrams created or updated
- [ ] API(s) are versioned
- [ ] Debug logging

## Research Questions 
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
Discussed on 4/25: More clarity needed, especially related to adjacent story FHIR Orders story

**Comment by sfradkin** [comment]
closing.  will be part of #494

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-08 - Each intermediary will support at least one format for outbound orders

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-19 - Each intermediary system should be able to link physical samples to an electronic order and integrate outgoing data with previously stored order data to satisfy hospital requirements
