### ISSUE TITLE
Ideal State Order Workflow

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/trusted-intermediary#211]
#  Research

Identify potential ideal state order workflow and map how existing FHIR capabilities support components of that ideal workflow

## Completion Criteria

- [ ] x

## Tasks

- [ ] x

## Additional Context

Add any other context or screenshots about the work here.

**Comment by JohnNKing** [comment]
@MikeC-A6 Any additional information we should consider for this story? Is it still relevant in light of most recent research efforts?

**Comment by JohnNKing** [comment]
Closing out in favor of more recent research backlog items.
