### ISSUE TITLE
Research NBS-Adjacent Processes

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#278]
# Backlog Task

From the perspective of a nurse, better understand adjacent newborn workflows. The goal is to ensure our solution will work well alongside those processes and to identify new product opportunities.

In Miro, see "CDC TI Story Map" =>  "2023-04-14 NBS Adjacent Processes"

## Completion Criteria

- [ ] What is the criteria for calling this task complete?

## Tasks

- [ ] What tasks need to be done to fulfill the completion criteria?

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by sfradkin** [comment]
Closing this in favor of similar research coming up more organically as we start interviews within our PHL/HCO partnerships.
