### ISSUE TITLE
Order HL7 ORM => FHIR

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#290]
# Story
As a hospital, to be able to transmit an NBS order via my EHR’s native order interface, I need the CDC ReportStream ecosystem to be able to receive an HL7 ORM order message and then send out an HL7 OML order message to a synthetic lab.

## Pre-conditions
- [x] The EHR is able to create an order that matches the HL7 v2 ORM standard.
- [x] The ability to convert outgoing FHIR to OML messages is already supported

## Acceptance Criteria
- [x] Inbound ORM messages can be received by ReportStream.
- [x] The order is transmitted to the synthetic lab soon after it has been received. Note: Not all data elements in the order need yet be included in the OML message.

## Related Stories
https://github.com/CDCgov/prime-reportstream/issues/10370

### Research
- [x] Contrast CA, MN, & LA sample messages and/or IGs
- [x] Ecosystem Mapping
  - [x] Identify how ORM data is collected for each state
- [x] Review CA's IG (https://drive.google.com/drive/folders/1JxbGZY9kRG8HwFaepSCJIntgORe9edUT)
- [x] Review Epic's Orders Tech Spec (https://open.epic.com/Tech/TechSpec?spec=staged%2FOutgoing%20Results%20and%20Orders%20Interface%20Technical%20Specification.zip or https://drive.google.com/drive/folders/1teOpcHrF74PwJB9FmssEOTfyNhlY6j4Z)
- [x] Review feedback on Cerner IGs (see https://aphlinformatics.atlassian.net/wiki/spaces/IR/pages/1981383536/6+28+2023+CDC+APHL+Flexion+Oracle+Cerner+-+Biweekly+ETOR+Mtg+Notes comments and attachment from Alexa; also reply via email forwarded 7/12 titled "RE: CDC/APHL/Flexion/Oracle Cerner - Biweekly ETOR Mtg")
- [x] Develop a [matrix](https://docs.google.com/spreadsheets/d/1yUZ5SnL5et3QYvu6p1Luk3AUSuOziCL-lRRI8uyYfn4/edit#gid=471449702) (contrasting info with EHR) of how EHRs may be able to provide mother's name and specimen ID. (e.g. mother's name via PID.6, PID.21, GT1, NK1, OBX; specimen ID via OBR, SPM, OBX; practitioner info via OBX, PD1) 
  ~~- [ ] Then request feedback from Epic and Cerner~~
  - [x] Share this with RS, to help identify parts of the message that may deviate from the current ORM sample message (https://github.com/CDCgov/trusted-intermediary/blob/main/examples/hl7/MN/MN%20NBS%20ORM_O01%20Lab%20Order%20Message.txt)
  - [x] Document deviations from standards that this would introduce
~~- [ ] Develop more ORM sample messages (if needed? More discussion needed)~~
~~- [ ] Determine if we can easily generating a FHIR message via Linux4Health or Synthea~~
~~- [ ] Get a copy of Alabama's insurance side of NBS card~~

###  Engineering

All uncompleted tasks are moved to story #472.  These are all items we are awaiting feedback for.

- [x] Watch both [RS HL7v2 -> FHIR knowledge sharing sessions](https://drive.google.com/drive/folders/1XU6XPJ2aGqqJQ-UGoBmgflng9x4GxMq_). - team
- [x] Review LinuxForHealth HL7 to FHIR Converter documentation for [templating](https://github.com/LinuxForHealth/hl7v2-fhir-converter/blob/master/TEMPLATING.md) (+ [techniques](https://github.com/LinuxForHealth/hl7v2-fhir-converter/blob/master/TECHNIQUES.md) and [best practices](https://github.com/LinuxForHealth/hl7v2-fhir-converter/blob/master/BEST_PRACTICES.md))
- [x] Meet with Jessica. - team
- [x] Create stand-in ORM file and explore.  - team
- [x] Create simplified FHIR to coincide with our simplified HL7 file.
- [x] `MessageHeader`
  - [x] `name` in the `destination` we think should be NATUS, but NATUS showed up as its own `Device`.
- [x] `Organizations`
  - [x] `identifier` is used instead of `name`.  Is this OK?
- [x] `Device`
  - [x] We have a NATUS device (which is referenced in the `MessageHeader`).  Is this OK?
- [x] `Practitioner`
- [x] `PractitionerRole`
- [x] `Patient` - Jessica
  - [x] `contact` field has the mother's information from `PID.6` but instead the mother's info is put into an `extension` (maiden name).  This is an ETOR NBS-specific requirement.  This would need to be accomplished on some TI-receiver-specific transformation in RS or directly in TI (this may be the better answer).
  - [x] birth date time extension added puts it as a `valueString` which is incorrect.
  - [x] `_birthDate` extension shows up in the `extension` list, not under `_birthDate`.  Probably not OK, but maybe is OK?
- [x] `ServiceRequest` - Jessica
  - [x] Figure out what proper identifier is for this resource. It should be the early ORC or OBR sub-segments.
  - [x] Work with Jessica if there's any overlap.
  - [x] `status` should be `unknown` or `active`?  It should be `unknown`.  Our example is missing `ORC.5` which means `status` needs to be `unknown`.
- [x] `Specimen` - team in progress
  - [x] `subject` should be a patient reference. - @halprin
  - [x] `collection` and its `collectedDateTime` in `test.fhir` compared to `receivedTime` in `expected.fhir`.  Is it OK the way it is?  Or should we really change things to be as in the expected FHIR?
- [x] `Observation`
  - [x] Fix rounding of `value`.
    - [x] Create an [issue](https://github.com/LinuxForHealth/hl7v2-fhir-converter/issues/500) with LinuxForHealth to create a `DOUBLE` type that handles bigger decimal numbers, and potentially create a PR to add it - @basiliskus 
      - [x] Created [a PR](https://github.com/LinuxForHealth/hl7v2-fhir-converter/pull/501) to fix above issue  - @jorg3lopez 
  - [x] Figure out rest of the way what the proper `identifier` is for this resource.  It was `MSH.7` (a date/time), but now is some field out of `ORC` or `OBR`.
  - [x] `status` should be `unknown` or `final`?  Should be `unknown`, but we need a custom extension to persist this value because `O` doesn't map to anything in FHIR.
- [x] Contact WG with our questions. - @halprin ([contacted](https://chat.fhir.org/#narrow/stream/179188-v2-to-FHIR/topic/Convert.20ORM_O01.20to.20FHIR.20Questions))
- [x] Communicate back with WG group. - @halprin
- [x] Change RS's `RESTTransport.kt` (around line 450) to work for the `orders` endpoint in addition to `demographics`.  See this [Slack message](https://flexion.slack.com/archives/C055XTF22B0/p1692207866289729). @basiliskus 
- [x] Update our RS organization information such that it hits our `orders` endpoint and correctly forwards the FHIR to us.  This means also in staging.  This may need updated `jurisdictionalFilter`, `qualityFilter`, and `reportUrl`. @jorg3lopez 
- [x] Have our orders convert to be OML orders when they come into our `orders` endpoint.  This can be implemented in a similar way to how we convert demographics to an order.  See `ConvertAndSendDemographicsUsecase.java` and `OrderConverter`. - @halprin 
-  [x] Add local set up for RS <-> TI connection to the main readme file - @basiliskus

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] ~~ADRs (`/adr` folder)~~
    - [x] ~~Other READMEs in the repo~~  
    - [x] Implementation guide (`/ig` folder) - check w/ @sfradkin @tjohnson7021
      - [x] create ORM message definition @tjohnson7021 
  - [x] Threat model updated - check w/ @JohnNKing @jorg3lopez 
  - [x] ~~API documentation updated~~ 
  - [x] Source code documentation created when the code is not self-documenting 
- [x] Code quality tasks completed
  - [x] Logging added where useful  
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] ~~Build process updated~~
  - [x] ~~API(s) are versioned~~
  - [x] ~~Feature toggles created and/or deleted.  Document the feature toggle~~
  - [x] Source code is merged to the main branch

## Research Questions 
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes

- Engineering should branch off of `jessica/10370-orm-mapping` in the RS repository.

**Comment by JohnNKing** [comment]
Discussed 4/25: Narrow to min required data for ORM?

**Comment by JohnNKing** [comment]
Defer until HL7 orders need to be supported

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-06 - Each intermediary will support at least one format for inbound orders
