### ISSUE TITLE
Processing Collection Date, Time, & Weight

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#304]
# Story
As a public health lab, to reduce transcription errors caused by handwritten order data, I need specimen collection date/time and newborn birth weight included as part of the electronic order.

## Pre-conditions
- [ ] The specimen collection date/time and newborn birth weight are included as part of an incoming order.
- [ ] The date/time of collection is in military time
- [ ] The birth weight is in grams

## Acceptance Criteria
- [ ] The specimen collection date/time and newborn birth weight are included in the OML order transmitted to the public health lab.

### Research
- [ ] Determine ways to represent these data elements in both HL7 and FHIR
- [ ] *Research work needed to complete the story*
- [ ] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [ ] *Engineering work needed to complete the story*
- [ ] Foundational: *Technical runway work to support this and future efforts*

## Definition of Done
- [ ] Threat model updated
- [ ] Code refactored for clarity and no design/technical debt
- [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies.
- [ ] Source code is merged to the main branch.
- [ ] Unit test coverage of our code >= 90%
- [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer.
- [ ] Build process updated
- [ ] Feature toggles created and/or deleted.  Document the feature toggle.
- [ ] Source code documentation created when the code is not self-documenting.
- [ ] API documentation generated
- [ ] Code quality checks passed
- [ ] Security & privacy gates passed
- [ ] Load tests passed
- [ ] Documentation and diagrams created or updated
- [ ] API(s) are versioned
- [ ] Debug logging

## Research Questions 
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by sfradkin** [comment]
closed.  collection date and time will be part of #493 and #494, birth weight is part of #495
