### ISSUE TITLE
JWT Tests Occasionally Fail

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#312]
Linting step occasionally fails builds, due to 1-second off issues with getting token expiration times.

Example: https://github.com/CDCgov/trusted-intermediary/actions/runs/4984233515/jobs/8922291539

JjwtEngineTest > getExpirationDate works happy path FAILED
    Condition not satisfied:

    actual == expected
    |      |  |
    |      |  2023-05-15T19:18:43
    |      false
    2023-05-15T19:18:44
        at gov.hhs.cdc.trustedintermediary.external.jjwt.JjwtEngineTest.getExpirationDate works happy path(JjwtEngineTest.groovy:85)

**Comment by jorg3lopez** [comment]
I did it to the bad path. I will fix this soon.

**Comment by jorg3lopez** [comment]
Fix is in, waiting for review.

https://github.com/CDCgov/trusted-intermediary/pull/331

**Comment by jorg3lopez** [comment]
Fix has been merged. This ticket can be closed.
