### ISSUE TITLE
Ecosystem research and documentation

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#32]
- [x] Continued HL7 meeting attendance and making contacts - @sfradkin 
- [ ] Big picture questions, organize and document - @cjterdi @SkiWether

**Comment by JohnNKing** [comment]
Moved "Learn more about FHIR - @halprin" to https://github.com/CDCgov/trusted-intermediary/issues/13

**Comment by JohnNKing** [comment]
"Public health laboratory and health care organization domain modeling - @MikeC-A6" moved to #53

**Comment by JohnNKing** [comment]
Further research on high-level process documented to be done under #49
