### ISSUE TITLE
Field Presence Validation of NBS Orders

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#340]
# Story
As a hospital, so that incomplete NBS orders can be fixed more quickly, I need validation of orders that identifies if any required fields are missing.

## Pre-conditions
- A single set of validation rules are used (i.e. they are not hospital or state-specific)

## Acceptance Criteria
- [x] A list of shared validation rules, based upon data gap analysis work to date, has been documented.
- [x] The shared validations rules are used to validate incoming orders.
- [x] We provide some means of capturing & persisting validation warnings (so they can be communicated back to the sender in the future).
- [x] None of the validation rules added prevent the order from being delivered.

### Research
- [ ] Link in state research boards (so that NBS card data can be reviewed by devs)
- [ ] Analyze and compare state data gap analyses
  - [ ] Identify opportunities for standardizing on a set of fields (e.g. birthweight, gestational age)
  - [ ] Review existing research
    - [ ] https://docs.google.com/spreadsheets/d/1yUZ5SnL5et3QYvu6p1Luk3AUSuOziCL-lRRI8uyYfn4/edit#gid=0
    - [ ] https://docs.google.com/document/d/1OIMRIQQ_0zBm8sYefEF_qhdtMV8mszCvf4OFtu59kDU/edit
    - [ ] Review LOI guide (cardinality of fields)
    - [ ] Document a standard list of validation rules

###  Engineering
- [x] Document what RS is validating
- [x] Implement validation rules and generate warnings for missing parts data from:
  - [x] MessageHeader
    - [x] `MSH-6` is required (`Bundle.entry.resource.ofType(MessageHeader).destination.receiver.resolve().identifier.where(value = 'simulated-hospital-id').exists()`) 
  - [x] Patient
  - [x] Next of Kin
  - [x] Observations 
- [x] Persist warnings as metadata and/or logs

#### Findings

Currently in RS, the only required fields for both `ORM` and `ORU` are:
- Required to parse the message (Sync/HTTP 400 error response):
  - `MSH-1`: Field Separator
  - `MSH-2`: Encoding Characters
  - `MSH-9`: Message Type
  - `MSH-12`: Version ID
- Required to deliver the message (no error response):
  - `MSH-6`: Receiving Facility (this one doesn’t throw any error or warning, it just doesn’t deliver)
- Required fields (error when converting FHIR => HL7):
  - `MSH-10`: Message Control ID

## Definition of Done
- [x] Threat model updated
- [x] Code refactored for clarity and no design/technical debt
- [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies.
- [x] Source code is merged to the main branch.
- [x] Unit test coverage of our code >= 90%
- [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer.
- [x] Build process updated
- [x] Feature toggles created and/or deleted.  Document the feature toggle.
- [x] Source code documentation created when the code is not self-documenting.
- [x] API documentation generated
- [x] Code quality checks passed
- [x] Security & privacy gates passed
- [x] Load tests passed
- [x] Documentation and diagrams created or updated
- [x] API(s) are versioned
- [x] Debug logging

## Research Questions 
- Should validation be performed by TI or by the PHLs LIMS? (hard vs soft failures)

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- NBS Card Reference
  - MN: https://miro.com/app/board/uXjVMaOm3o0=/?share_link_id=128589224770
  - AL: https://miro.com/app/board/uXjVMaOm3uE=/?share_link_id=841127339748

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-04 - Each intermediary will create an MVP with the capability to support when the facility receives the entire order, and the intermediary is responsible for validating and transforming the order for PHL

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-05 - Each intermediary will create an MVP wherein the system accepts all order-related information from the facility. The intermediary is responsible for receiving the order, performing validation, and carrying out transformations for PHL LIMS

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-15 - Intermediaries will establish, utilize, and validate a common set of data elements

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-36 - Each intermediary will have the same validations performed for all data exchange formats (e.g, NIST)

**Comment by basiliskus** [comment]
Required field validation will be applied using the validation engine in #341

**Comment by JohnNKing** [comment]
@JohnNKing to capture a subsequent (non-MVP) story for how to handle validation for AL (e.g. rejecting orders if missing card number)

**Comment by luis-pabon-tf** [comment]
When #341 is completed and closed, is this one finished as well?

**Comment by JohnNKing** [comment]
> When #341 is completed and closed, is this one finished as well?

@luis-pabon-tf I think so -- yes.
