### ISSUE TITLE
Automate tooling updates in local doc automation container

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#357]
# Backlog Task

The Docker container used to do local development of the documentation should periodically auto-update all the tools

## Completion Criteria

- [ ] Tooling is updated automatically on a periodic basis

## Tasks

- [ ] What tasks need to be done to fulfill the completion criteria?

## Other Notes

- Any other notes to help clarify this task for the team

**Comment by sfradkin** [comment]
You can just rebuild the Docker image and everything should be updated.  Might be easier than adding the ability to update the image periodically.

**Comment by pluckyswan** [comment]
Closing this issue as it relates to the implementation guide and that no longer exists
