### ISSUE TITLE
Receiving FHIR Orders via REST

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#382]
# Story
As a public health lab, to be able to receive the NBS order such that it can be ingested by my LIMS, I need to receive a single order via REST that includes demographic data combined with additional order fields.

## Pre-conditions
- [x] All demographic data is submitted with the additional order fields in a single REST call. (Combining previously submitted demographic data with a partial order is a later story.)

## Acceptance Criteria
- [x] We can ingest a FHIR order that includes demographics.
- [x] An outgoing FHIR order is sent soon after receiving the incoming FHIR order
- [x] The outgoing FHIR order includes currently-supported demographic information.
- [x] The service request ID of the incoming order is unchanged and no additional FHIR orders are created.
- [x] The ability to receive only demographic data and then send out a FHIR order continues to function.
- [x] The incoming FHIR order is only accepted if and only if it is sent from a trusted organization.

### Research
- [x] Better understand how billing information can be captured as part of an order @MikeC-A6 [https://miro.com/app/board/uXjVM8df8xY=/]
  - [x] Determine how billing works for MN
- [x] Review HL7v2 to FHIR conversion spreadsheets and see how this could map to FHIR elements (e.g. service request & patient) - @cjterdi 
  - [x] Apply to MN orders - @cjterdi
- [x] Develop a knowledge base for how HL7 and/or FHIR messages are constructed, mapped, and converted (e.g. provenance)
  - [x] Evaluate use of RS terminal-based conversion for creating sample files (Answer: not currently possible)
  - [x] Review sample ADT & OML message from MN
  - [x] Create sample NBS ORM message, based on OML sample and known standards - @JohnNKing 
  - [x] Create sample NBS FHIR order, based on OML sample and known standards - @JohnNKing 
  - [x] Follow-up on ReportStream to define product needs - @JohnNKing 
  - [x] Discuss provenance on 7/7 with ReportStream - @JohnNKing 

###  Engineering
- [x] Decide on architectural design for API endpoint
- [x] Create OrdersController @basiliskus 
- [x] Create OrdersResponse @basiliskus @jorg3lopez 
- [x] Orders endpoint
   - [x] Create v1/etor/orders endpoint skeleton @jorg3lopez 
   - [x] Enforce a valid bearer token on our orders endpoint @jorg3lopez
   - [x] Process request using OrdersController @basiliskus 
   - [x] Send order to ReportStream (new usecase) - @halprin 
   - [x] Return OrdersResponse @jorg3lopez @basiliskus 
   - [x] Add endpoint to OpenApi - @basiliskus 
   - [x] Add endpoint to Locust load testing file - @tjohnson7021 
   - [x] Add end to end tests @tjohnson7021 
   - [x] Javadocs
   - [x] ReadMe
   - [x] Check OWASP @jorg3lopez 
   - [x] Handle bad requests @jorg3lopez @basiliskus 
- [x] improving logging capability - @halprin 
- [x] Fix IG deployment to update and correctly target different environments - @halprin 

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder) - @halprin 
    - [x] ADRs (`/adr` folder)
    - [x] Main README.md
    - [x] Other READMEs in the repo
  - [x] Threat model updated
  - [x] API documentation generated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions 
- OML or ORM for incoming orders?

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:MVP-REQ-01 - Each intermediary will support delivery of individual orders in real time

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-05 - Each intermediary will create an MVP wherein the system accepts all order-related information from the facility. The intermediary is responsible for receiving the order, performing validation, and carrying out transformations for PHL LIMS
