### ISSUE TITLE
TI/RS Delivery Loop

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#461]
# Bug

## Describe the Bug

When connecting ReportStream and the TI service locally, a delivery loop occurs.

See branches:
* https://github.com/CDCgov/trusted-intermediary/tree/rs-form-data
* https://github.com/CDCgov/prime-reportstream/tree/john-etor-demo

Also see all the messages from Aug 4th in https://flexion.slack.com/archives/C04FT9U8MPB/p1691135600671569

## Impact

The PHL would be unable to use our service for order delivery.

## To Reproduce

1. Submit an ORM order to ReportStream locally
2. OML files in the SFTP folder continue to be created every minute or two

## Expected Behavior

The OML order should only appear once in the SFTP folder.

## Screenshots

n/a

## Logs

n/a

## Version

See above

## Additional Context

none

**Comment by halprin** [comment]
This is complete given the merge of https://github.com/CDCgov/prime-reportstream/pull/10979
