### ISSUE TITLE
change management/error handling/onboarding research

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#464]
# Design or Research

High level description of what design or research needs to be accomplished.

## Tasks

- [ ] Something.

## Additional Context

change management / error handling -> needs hospital
on-boarding - who are we onboarding (technically this is onboarding the PHL and HCO to connect, the reportstream onboarding uses a questionnaire to understand how the STLT will connect and the types of messages they will send/receive)
need to know who is actually sending message (who physically sends out the order?  a person pressing button?  automated somehow in the EHR?)

**Comment by JohnNKing** [comment]
Merging with #470
