### ISSUE TITLE
Research: Order Insurance Processing

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#465]
# Research Backlog Item
To inform future engineering efforts, we need to understand our partner needs for communicating insurance information and what ReportStream supports.

## Acceptance Criteria
- [x] We know how insurance information may be submitted for LA
- [x] We know what insurance-related order date can be converted by ReportStream
- [x] Implementation tickets exist for ReportStream and/or TI processing insurance information

### Research
- [x] Confirm if IN1 is the only way this information may need to be provided.
  - [x] ~~For AL: No, we should expect mother's insurance info in GT-1, based on https://aphlinformatics.atlassian.net/wiki/spaces/ERI/pages/2657746945/8+27+2024+AL+PM+Touchpoint~~
  - [x] For LA, IN1 is referenced in the order profile (IN1.3, IN1.36) (as of 10/27/2024) 
- ~[ ] If the information is not coming in the ORM message on the IN1 segment, how will it come in?~
- [x] Do the LIMS support ingestion of IN1 on the OML message?
    - [x] For LA PHL, yes
- [x] Do the EHRs also support IN1?
    - [x] For LA HCO, yes
- [x] May need to do a bit of gap analysis on insurance information as part of this story: None needed

###  Engineering
- [x] Test the updated version of ReportStream if any conversions are now taking place with IN1 & GT1

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
Discussing with AL this week, to clarify if this is needed. It was initially considered essential, but what we learned from the on-site is that second page of the card (for insurance) is often not filled out in practice.

**Comment by JohnNKing** [comment]
Will Natus be able to support IN1?

**Comment by JohnNKing** [comment]
For AL scoping, it's really just IN1 processing in an OML message that's required.

**Comment by JohnNKing** [comment]
ReportStream related effort: https://github.com/CDCgov/prime-reportstream/issues/15500

**Comment by JohnNKing** [comment]
@JohnNKing Split into separate research and implementation stories

**Comment by JohnNKing** [comment]
Old description and AC:
As a lab, so that I can receive insurance information for billing purposes, I need the electronic order sent to ReportStream to be able to include insurance details.

## Pre-conditions

## Acceptance Criteria
- [ ] Insurance information can be included as part of the order message from the hospital.
- [ ] Orders lacking insurance information are not rejected.

**Comment by luis-pabon-tf** [comment]
[FHIR mapping for GT1](https://confluence.hl7.org/pages/viewpage.action?pageId=49644444)

[Proposed FHIR mapping for IN1](https://docs.google.com/spreadsheets/d/1-8U35_8X9wQTQAchyVAujF4TFrbcjyDeloU2gpHT2_o/edit?gid=0#gid=0)

**Comment by luis-pabon-tf** [comment]
The library in RS does not automatically translate either IN1 or GT1. It will need to be developed. Will add information regarding that in this ticket.

**Comment by luis-pabon-tf** [comment]
I've included the input and output from running tests on RS to check if the Insurance segments were translated.

[Epic_ORU_Insurance.hl7.txt](https://github.com/user-attachments/files/17421608/Epic_ORU_Insurance.hl7.txt)
[Epic_ORU_Insurance.fhir.txt](https://github.com/user-attachments/files/17421597/Epic_ORU_Insurance.fhir.txt)

**Comment by luis-pabon-tf** [comment]
The mapping matches on the previously posted test data are actually a map from the PID segment. Removing most of the PID segment makes it so nothing matches anymore.

When this becomes a development task, mapping will need to be added for both segments on all fields that we need.

**Comment by JohnNKing** [comment]
Note: For LA, IN1 is referenced in the order profile (IN1.3, IN1.36) for both the lab and hospital (as of 10/27/2024)

**Comment by luis-pabon-tf** [comment]
Just updating that recent RS mapping updates have no change regarding this issue.

**Comment by luis-pabon-tf** [comment]
> Note: For LA, IN1 is referenced in the order profile (IN1.3, IN1.36) for both the lab and hospital (as of 10/27/2024)

Our test data doesn't have anything on these fields. We can fill them, but should make sure what they send us fits what we expect.

**Comment by luis-pabon-tf** [comment]
The [proposed FHIR mapping](https://docs.google.com/spreadsheets/d/1-8U35_8X9wQTQAchyVAujF4TFrbcjyDeloU2gpHT2_o/edit?gid=0#gid=0) for IN1 does not have definitions for `IN1.3` or `IN1.36`.

**Comment by tjohnson7021** [comment]
We wrote a proposal mapping for the unmapped fields in IN1:  https://docs.google.com/spreadsheets/d/1-VriilwJZSSPqxTxjkom42-darUN0WNqjRILbDHCLqA/edit?usp=sharing

**Comment by jbiskie** [comment]
We did get a couple samples earlier this week, which were helpful. The questions yet to be answered in this ticket are embedded in the research tasks up top.

**Comment by JScott-JMC** [comment]
I added notes in the task list.  No gaps for LA re: IN1.

**Comment by GilmoreA6** [comment]
@brick-green to create tickets for mapping IN1 and GT1 in ReportStream
