### ISSUE TITLE
ORM -> FHIR - Continued Field transformations 

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#472]
# Story
As a hospital, to be able to transmit an NBS order via my EHR’s native order interface, I need the CDC ReportStream ecosystem to be able to receive an HL7 ORM order message and then send out an HL7 OML order message to a synthetic lab with all required fields.

## Pre-conditions
- [ ] The EHR is able to create an order that matches the HL7 v2 ORM standard.
- [ ] The ability to convert outgoing FHIR to OML messages is already supported

## Acceptance Criteria
- [ ] Inbound ORM messages with all required fields can be received by ReportStream.
- [ ] The order is transmitted to the synthetic lab soon after it has been received with all required data elements.

## Related Stories
https://github.com/CDCgov/prime-reportstream/issues/10370

### Research
- 

###  Engineering
- [ ] `MessageHeader`
  - [ ] `focus` is missing.  We will not convert it.  Reach out to the working group in charge of this and get their input.
- [ ] `Organizations`
  - [ ] St. Cloud Hospital org had an identifier of `739`, but test FHIR has `739` in `ServiceRequest`.  `ORC.21` can _repeat_ and identifies the facility placing the order.  In a `ServiceRequest`, it only allows a single `PractitionerRole` as the `requester`.  That only allows us to reference one `Organization` through that `PractitionerRole`.  But let's assume we have two `ORC.21`s.  What do we do with that second organization?  Do we make a second `Organization` resource, but then how do we reference it from the `ServiceRequest`?  Again, the `ServiceRequest` only supports one `PractitionerRole` which only supports one `Organization`.  As of this writing, RS's ORM mapping puts these organization's IDs as `identifiers` in the `ServiceRequest` (which probably isn't right because they aren't IDs of the `ServiceRequest` but of the organization).  Reach out to the working group in charge of this and get their input.
- [ ] `Provenance` is completely missing.
- [ ] `Device`
  - [ ] Missing the RS device.  The RS device is because it will be referenced in `Provenance`.  Figure out `Provenance` and then come back to this.
- [ ] `Patient` - Jessica
- [ ] `ServiceRequest` - Jessica
  - [ ] `specimen` is missing.  We will not convert it.  Reach out to the working group in charge of this and get their input.
- [ ] `Observation`
  - [ ] `basedOn` is missing.  We will not convert it.  Reach out to the working group in charge of this and get their input.
- [x] Contact WG with our questions. - @halprin ([contacted](https://chat.fhir.org/#narrow/stream/179188-v2-to-FHIR/topic/Convert.20ORM_O01.20to.20FHIR.20Questions))
- [ ] Distill FHIR WG group findings into tasks. - @halprin

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Document current status for ORM mapping in TI repo (readme.md?)
    - [ ] Add local set up for RS <-> TI connection to the main readme file
    - [ ] ADRs (`/adr` folder)
    - [ ] Other READMEs in the repo
  - [ ] Threat model updated
  - [ ] API documentation updated
  - [ ] Source code documentation created when the code is not self-documenting
- [ ] Code quality tasks completed
  - [ ] Logging added where useful
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions 
- 

## Decisions
- 

## Notes

-

**Comment by JohnNKing** [comment]
Need to updated based on current transformation state and LA requirements

**Comment by basiliskus** [comment]
Reviewed at Planning but need to check with @JohnNKing

**Comment by JohnNKing** [comment]
I wonder if this should be converted to a spike, to determine if any of these FHIR components are still missing.

**Comment by basiliskus** [comment]
Do we still need this story now that we know Ochsner will send an OML message instead of ORM?

**Comment by brick-green** [comment]
Agreed. Closing.
