### ISSUE TITLE
Create Outbound OML MSH Segment

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#489]
# Story
As a public health lab, to be able to make use of received electronic NBS orders, I need the OML MSH segment included with the order.

## Pre-conditions
- [x] The required fields are already included in the incoming FHIR.

## Acceptance Criteria
- [x] The MSH segment shows up in the outbound OML and has all the required fields.

### Research
- [x] Identify required fields. - @cjterdi and team

###  Engineering
- [x] Watch [RS fhir -> hl7vs KS video](https://drive.google.com/drive/folders/1lDEUX03HSpjLoYHrJPRps3DP4umPUntf) - entire team
- [x] Convert MSH-1.
- [x] Convert MSH-2.
- [x] Convert MSH-3.
  - [x] Convert MSH-3.2.
  - [x] Convert MSH-3.3.
- [x] Convert MSH-4.
- [x] Convert MSH-5.
- [x] Convert MSH-6.
- [x] Convert MSH-7.
- [x] Convert MSH-9.
- [x] Convert MSH-10.
- [x] Convert MSH-11.
- [x] Convert MSH-12.
- [x] Convert MSH-15.
- [x] Convert MSH-16.
- [x] Convert MSH-21.

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions

- Team has decided that for the purpose of this story and the "required" fields, we will ensure that the fields on the [Screening Card Data fields spreadsheet](https://docs.google.com/spreadsheets/d/1yUZ5SnL5et3QYvu6p1Luk3AUSuOziCL-lRRI8uyYfn4/edit#gid=1336407508&range=E3) are marked as `R` and `C` that contain an `R` in the Minnesota column (column `G`) will be converted.

## Notes
- [Minnesota Order IG](https://drive.google.com/file/d/1sSkT2e3_pFtffhyrKvaD9bNZkvxX-G4l/view?usp=share_link).

**Comment by halprin** [comment]
Attached is the sample FHIR we should use when converting to OML via ReportStream.
[FHIR_OML_example.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEkzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0457eb4d28d648705eea586509fd08bb505f510e/FHIR_OML_example.txt)

**Comment by basiliskus** [comment]
Looks like this is the command to convert from FHIR to HL7: `./gradlew primeCLI --args='fhirdata --output-format HL7 --input-file "./test/input.json" --output-file "./test/output.hl7" -s "./metadata/hl7_mapping/OML_O21/OML_O21-base.yml"'`

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-08 - Each intermediary will support at least one format for outbound orders
