### ISSUE TITLE
Create Outbound OML NK1 Segment

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#491]
# Story
As a public health lab, to be able to make use of received electronic NBS orders, I need the OML NK1 segment included with the order.

## Pre-conditions
- [x] The required fields are already included in the incoming FHIR.

## Acceptance Criteria
- [x] The NK1 segment shows up in the outbound OML and has all the required fields.

### Research
- [x] Identify required fields.

###  Engineering

- [x] Update sample test file to include patient contact information
- [x] Map `NK1` segment
  - [x] NK1-1: Set ID - NK1 (SI)
  - [x] NK1-2: Name (XPN)
    - [x] NK1-2.1: Family Name (FN)
    - [x] NK1-2.2: Given Name
    - [x] NK1-2.3: Second and Further Given Names or Initials Thereof
  - [x] NK1-3: Relationship (CWE)
    - [x] NK1-3.1: Identifier
    - [x] NK1-3.2: Text
    - [x] NK1-3.3: Name of Coding System
    - [x] NK1-3.9: Original Text
  - [x] NK1-5:  Phone Number (XTN) - _not required but already present_
    - [x] NK1-5.3: Telecommunication Equipment Type
    - [x] NK1-5.5: Country Code
    - [x] NK1-5.6: Area/City Code
    - [x] NK1-5.7: Local Number
    - [x] NK1-5.12: Unformatted Telephone Number
- [x] Copy patient address and telecom to patient's contacts' address and telecom in our application.

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
      - [x]  Add ig provenance (changelog) updates for this story specifically (if applicable)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- [RS fhir -> hl7vs KS video](https://drive.google.com/drive/folders/1lDEUX03HSpjLoYHrJPRps3DP4umPUntf)

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-08 - Each intermediary will support at least one format for outbound orders
