### ISSUE TITLE
Create Outbound OML SPM Segment

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#494]
# Story
As a public health lab, to be able to make use of received electronic NBS orders, I need the OML SPM segment included with the order.

## Pre-conditions
- [x] The required fields are already included in the incoming FHIR.

## Acceptance Criteria
- [x] The SPM segment shows up in the outbound OML and has all the required fields.

### Research
- [x] Identify required fields.

###  Engineering
- [x] Update sample test file to include specimen information (We used MN NBS OML_21 Lab Order Message.txt for testing)
- [x] Map `SPM` segment
  - [x] SPM-1: Set ID – SPM (SI)
  - [x] SPM-4: Specimen Type (CWE)
    - [x] SPM-4.1: Identifier
    - [x] SPM-4.3: Name of Coding System
  - [x] SPM-17: Specimen Collection Date/Time (DR)
    - [x] SPM-17.1: Range Start Date/Time

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
      - [x]  Add ig provenance (changelog) updates for this story specifically (if applicable)
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Build & Deploy tasks completed
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- [RS fhir -> hl7vs KS video](https://drive.google.com/drive/folders/1lDEUX03HSpjLoYHrJPRps3DP4umPUntf)

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-08 - Each intermediary will support at least one format for outbound orders
