### ISSUE TITLE
Create Outbound OML OBX Segment

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#495]
# Story
As a public health lab, to be able to make use of received electronic NBS orders, I need the OML OBX segment included with the order.

## Pre-conditions
- [ ] The required fields are already included in the incoming FHIR.

## Acceptance Criteria
- [x] The OBX segment shows up in the outbound OML and has all the required fields
- [x] OBX can handle multiple segments

### Research
- [x] Identify required fields (double check LOI)

###  Engineering
- [x] OBX-1
- [x] OBX-2
- [x] OBX-3
  - [x] OBX-3.1
  - [x] OBX-3.2
  - [x] OBX-3.3
- [x] OBX-4
- [x] OBX-5
- [x] OBX-6
  - [x] OBX-6.1
  - [x] OBX-6.2
  - [x] OBX-6.3
- [x] OBX-11
- [x] OBX-14

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
      - [x]  Add ig provenance (changelog) updates for this story specifically (if applicable)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- [RS fhir -> hl7vs KS video](https://drive.google.com/drive/folders/1lDEUX03HSpjLoYHrJPRps3DP4umPUntf)

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-03 - Intermediaries must support delivery of AOE questions (data elements present on existing NBS order cards)

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-08 - Each intermediary will support at least one format for outbound orders
