### ISSUE TITLE
ITDG: Integrate with APIM/Digital Marketplace/API Gateway

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#499]
# Backlog Task

ITDG: Integrate with APIM/Digital Marketplace/API Gateway

## Completion Criteria

- [ ] We integrate with the CDC's API gateway offering if required.

## Tasks

- [ ] Hear back and continue conversations (maybe revisit early September?)

## Other Notes

- Currently unsure if this applies to the intermediary.  It is up in the air whether the APIM/Digital Marketplace/API Gateway also applies to non-"enterprise CDC".
- Our point of contact is Sailaja Savanam.  She's in charge of the Digital Marketplace.  Last we heard as of 8/29/23, she was going to reach out to Rishi to see if we really belong under the API gateway (see above bullet point).  There is a questionnaire that her team would give us to figure out the requirements, but they are all very busy supporting DEX.
- There's also a question whether we need to be behind the API gateway if we, for the MVP, will be only ever called by ReportStream.
- API Gateway brings different software with different API endpoints under a cohesive location - eg: covid APIs, HIV APIs brought under a single URL endpoint for external parties to use
-

**Comment by scleary1cs** [comment]
Post MVP in your opinion @halprin?

**Comment by JohnNKing** [comment]
Looking for @halprin's thoughts on needs and priorities for this.

**Comment by halprin** [comment]
@JohnNKing, I say we close it.  It hasn't been important for this long.  No one has come back and asked.
