### ISSUE TITLE
Public facing metadata format

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#589]
## Spike Goal
Determine a format for the public facing metadata.
Options are:

1. [`AuditEvent` resource](https://hl7.org/fhir/R4/auditevent.html).
2. [`OperationOutcome` resource](https://hl7.org/fhir/R4/operationoutcome.html).
3. [`Provenance` resource](https://hl7.org/fhir/R4/provenance.html).
4. Custom format 

## Timebox
2 FTE days

## Tasks

- [x] Also send an email to Rishi (cc: jason and sara) with documented decision on format - @halprin 

## Decision

`OperationOutcome`.

We decided to pick FHIR over a custom format because...

1. We're already using FHIR as our main format.
2. Others can use a FHIR library to parse our response.
3. There isn't a downside to using FHIR if the consumer doesn't care that we use FHIR.

We decided on `OperationOutcome` because...

1. `Provenance` doesn't fit our metadata at all, so it is disqualified.
2. `AuditEvent` looks nice with its ability to support hierarchy, but this resource is meant for internal tracking of events.
3. `OperationOutcome` is already meant to be externally facing, unlike `AuditEvent`.  It is also the result of an [operation](https://hl7.org/fhir/operations.html), which is a type of call one can make to a FHIR server that doesn't fit nicely into CRUD operations on FHIR resource which is what a metadata request would be.

## Notes

- What outputs will be needed? ADR?
- Related to #517.
- Will need an endpoint
- Endpoint will need to be externally facing 
- External endpoint will need to be authenticated 
- Next Three Stories after this Spike - "Unique ID #610, File name #611, and Time of order ingestion into intermediary #612"

### Mapping

| Metadata | `AuditEvent` | `OperationOutcome` | `Provenance` |
|--------|--------|--------|--------|
| Time of order ingestion | `entity.where(name = 'order').detail.where(type = 'ingestion time').value` | `issue.where(severity = 'information' and code = 'informational' and details.text = 'order ingestion' and details.coding.system = 'http://terminology.hl7.org/CodeSystem/operation-outcome' and details.coding.code = 'MSG_CREATED').diagnostics` | _Unknown_ |
| Time of order delivery | `entity.where(name = 'order').detail.where(type = 'delivery time').value` | `issue.where(severity = 'information' and code = 'informational' and details.text = 'order delivery').diagnostics` | _Unknown_ |
| Time of result ingestion | `entity.where(name = 'result').detail.where(type = 'ingestion time').value` | `issue.where(severity = 'information' and code = 'informational' and details.text = 'result ingestion' and details.coding.system = 'http://terminology.hl7.org/CodeSystem/operation-outcome' and details.coding.code = 'MSG_CREATED').diagnostics` | _Unknown_ |
| Time of result delivery | `entity.where(name = 'result').detail.where(type = 'delivery time').value` | `issue.where(severity = 'information' and code = 'informational' and details.text = 'results delivery').diagnostics` | _Unknown_ |
| Order failure reason | `entity.where(name = 'order').detail.where(type = 'failure reason').value` | `issue.where(severity = 'error' or severity = 'warn' and code = '_TBD_' and details.text = 'order failure reason' and details.coding.system = 'http://terminology.hl7.org/CodeSystem/operation-outcome' and details.coding.code = '_TBD_').diagnostics` | _Unknown_ |
| Result failure reason | `entity.where(name = 'result').detail.where(type = 'failure reason').value` | `issue.where(severity = 'error' or severity = 'warn' and code = '_TBD_' and details.text = 'result failure reason' and details.coding.system = 'http://terminology.hl7.org/CodeSystem/operation-outcome' and details.coding.code = '_TBD_').diagnostics` | _Unknown_ |
| Unique ID | `id` | `id` |`id` |
| Sender name | `agent.where(type.coding.system = 'http://terminology.hl7.org/CodeSystem/v3-ParticipationType' and type.coding.code = 'AUT').name` | `issue.where(severity = 'information' and code = 'informational' and details.text = 'sender name').diagnostics` | `agent.where(role.coding.system = 'http://terminology.hl7.org/CodeSystem/v3-ParticipationType' and role.coding.code = 'AUT').who.display` |
| Receiver name | `agent.where(type.coding.system = 'http://terminology.hl7.org/CodeSystem/v3-ParticipationType' and type.coding.code = 'IRCP').name` | `issue.where(severity = 'information' and code = 'informational' and details.text = 'receiver name').diagnostics` | `agent.where(role.coding.system = 'http://terminology.hl7.org/CodeSystem/v3-ParticipationType' and role.coding.code = 'IRCP').who.display` |
| Payload hash | `entity.where(name = 'payload').detail.where(type = 'hash').value` | `issue.where(severity = 'information' and code = 'informational' and details.text = 'payload hash').diagnostics` | _Unknown_ |
| File name | `entity.where(name = 'payload').detail.where(type = 'file name').value` | `issue.where(severity = 'information' and code = 'informational' and details.text = 'file name').diagnostics` | _Unknown_ |

#### `AuditEvent`

This resource is specific to a single event while our metadata is generally associated with multiple events that are tied together, but it supports multiple types of metadata in general.  Only strings or binary data is supported, so numbers and booleans won't be natively represented.  Any additional metadata that would be supported in the future would be added as additional `entity.detail`s.  I do like that I can group similar metadata together under a single `entity`.

##### Other Required Fields

- `type` - `system` is `http://terminology.hl7.org/CodeSystem/iso-21089-lifecycle` and `code` is `transmit`
- `recorded` - current date/time.
- `agent.requestor` - If we wanted to set this field correctly...
  - `true` when the HCO calls the metadata endpoint for an order or when the PHL calls the metadata endpoint for a result.
  - `false` when the HCO calls the metadata endpoint for a result or when the PHL calls the metadata endpoint for an order.
- `source.observer` - We can just use the `reference` or `display` field and fill it in with `ReportStream Intermediary` or something like that.

##### Example

<details><summary>Example</summary>
<p>

```json
{
  "resourceType": "AuditEvent",
  "id": "8439C442-5988-4CA9-8414-5C89DB753160",
  "type": {
    "system": "http://terminology.hl7.org/CodeSystem/iso-21089-lifecycle",
    "code": "transmit"
  },
  "recorded": "2023-10-26T23:41:23Z",
  "agent": [
    {
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
            "code": "AUT"
          }
        ]
      },
      "name": "LA Childrens Hospital",
      "requestor": true
    },
    {
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
            "code": "IRCP"
          }
        ]
      },
      "name": "LA PHL",
      "requestor": false
    },
  ],
  "source": {
    "observer": {
      "display": "ReportStream Intermediary"
    }
  },
  "entity": [
    {
      "name": "payload",
      "detail": [
        {
          "type": "hash",
          "valueString": "71a103d892d771e8b325abac82740c3af3ffab0e"
        },
        {
          "type": "file name",
          "valueString": "DogCow-delivers-order.hl7"
        }
      ]
    },
    {
      "name": "order",
      "detail": [
        {
          "type": "ingestion time",
          "valueString": "2023-10-26T22:41:23Z"
        },
        {
          "type": "delivery time",
          "valueString": "2023-10-26T22:51:23Z"
        },
        {
          "type": "failure reason",
          "valueString": "You gave me your grocery list, not a NBS lab order."
        }
      ]
    },
    {
      "name": "result",
      "detail": [
        {
          "type": "ingestion time",
          "valueString": "2023-10-26T22:41:23Z"
        },
        {
          "type": "delivery time",
          "valueString": "2023-10-26T22:51:23Z"
        },
        {
          "type": "failure reason",
          "valueString": "You gave me your grocery list, not a NBS lab result."
        }
      ]
    }
  ]
}
```

</p>
</details> 

#### `OperationOutcome`

This resource has good support for listing multiple bits of data which aligns well with the multiple types of metadata.  To use this resource, we can't use the `details` codeable concept to its fullest extent.  A codeable concept normally includes a `system` and a `code`, but the allowed `system` doesn't have codes that represent our metadata concepts except for the order/result failure reasons.  So, to use this resource, we can only fill in the `text` field of the codeable concept.  Only strings is supported, so numbers and booleans won't be natively represented.  Any additional metadata that would be supported in the future would be added as additional `issue`s.

##### Other Required Fields

_None_.

##### Example

<details><summary>Example</summary>
<p>

```json
{
  "resourceType": "OperationOutcome",
  "id": "8439C442-5988-4CA9-8414-5C89DB753160",
  "issue": [
    {
      "severity": "information",
      "code": "informational",
      "details": {
        "text": "order ingestion"
      },
      "diagnostics": "2023-10-26T22:41:23Z"
    },
    {
      "severity": "information",
      "code": "informational",
      "details": {
        "text": "order delivery"
      },
      "diagnostics": "2023-10-26T22:51:23Z"
    },
    {
      "severity": "information",
      "code": "informational",
      "details": {
        "text": "result ingestion"
      },
      "diagnostics": "2023-10-26T22:41:23Z"
    },
    {
      "severity": "information",
      "code": "informational",
      "details": {
        "text": "results delivery"
      },
      "diagnostics": "2023-10-26T22:51:23Z"
    },
    {
      "severity": "error",
      "code": "structure",
      "details": {
        "text": "order failure reason",
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/operation-outcome",
            "code": "MSG_BAD_FORMAT"
          }
        ]
      },
      "diagnostics": "You gave me your grocery list, not a NBS lab order."
    },
    {
      "severity": "error",
      "code": "structure",
      "details": {
        "text": "result failure reason",
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/operation-outcome",
            "code": "MSG_BAD_FORMAT"
          }
        ]
      },
      "diagnostics": "You gave me your grocery list, not a NBS lab result."
    },
    {
      "severity": "information",
      "code": "informational",
      "details": {
        "text": "sender name"
      },
      "diagnostics": "LA Childrens Hospital"
    },
    {
      "severity": "information",
      "code": "informational",
      "details": {
        "text": "receiver name"
      },
      "diagnostics": "LA PHL"
    },
    {
      "severity": "information",
      "code": "informational",
      "details": {
        "text": "payload hash"
      },
      "diagnostics": "71a103d892d771e8b325abac82740c3af3ffab0e"
    },
    {
      "severity": "information",
      "code": "informational",
      "details": {
        "text": "file name"
      },
      "diagnostics": "DogCow-delivers-order.hl7"
    }
  ]
}
```

</p>
</details> 

#### `Provenance`

I can't seem to find an appropriate location within `Provenance` for most of the metadata without egregiously stretching the FHIR specification.  There seems to only be a half-way suitable location for the unique ID and the sender/receiver name.

##### Other Required Fields

- `recorded` - current date/time.
- `entity.role` - no value seems appropriate.

##### Example

_N/A_.

**Comment by jcrichlake** [comment]
https://aphlinformatics.atlassian.net/wiki/spaces/IR/pages/2060419190/ETOR+Intermediary+Metadata+Alignment

Including link to APHL for expected data that is to be exposed and not exposed

**Comment by jcrichlake** [comment]
Pasting the below for the FHIR v4 guide.  Looks like the Operation Outcome  expects an expression tag with the EXACT location within the message

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODUxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b98448b8d4af6d4ec43049c0f20b341fa0630be0/image.png)

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-27 - Intermediaries will provide metadata required, including elements to calculate timeliness metrics

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-29 - Each Intermediary shall have a dashboard for some higher level internal monitoring metrics – team who is troubleshooting and supporting would need access to these different views of the system
