### ISSUE TITLE
0.17 – Template Data Element Gap Analysis Matrix

### ISSUE THREAD

**Issue by nvcllns** [CDCgov/trusted-intermediary#603]
Rationale: Using the experience of the Louisiana data element gap analysis creation, set-up a site-agnostic template that can be used by the ReportStream Lab Terminologist to cross-walk the various IGs and sample messages inclusive of all relevant data elements, underlying value-sets, and individual values to systematically capture all data element needs relevant to a single site’s ETOR initial implementation. An outcome of use of this template will be a comprehensive understanding of all data that a given HCO will send to RS to construct an order message; and that a given PHL will send to RS to construct a result message. 

Inputs:
•	HL7 Implementation Guide for order type used by sending HCO
•	HCO/EHR-localized version of HL7 Implementation Guide for order type used by sending HCO (if applicable)
•	Current NBS card of receiving jurisdiction
•	HL7 Implementation Guide for order type used by receiving PHL
•	PHL/NBS LIMS-localized version of HL7 Implementation Guide for order type used by receiving PHL (if applicable) 

## Anticipated Urgency Level: Suggesting High 
Rationale: ReportStream Lab Terminologist resumes are being collected now and a candidate could begin as early as November 13th. This artifact could be started by the Flexion/Agile 6 team and serve as one of the first assignments prioritized by this new resource. 

## Other Notes
This TA Output is reflected 0.17 within the NBS ETOR ReportStream Technical Assistance Development Framework and working drafts and final copies can be uploaded or linked at https://cdc.sharepoint.com/:f:/r/teams/OLSS_ETOR_ReportStream/Shared%20Documents/General/ETOR%20for%20Newborn%20Screening/3.%20ReportStream%20Implementation%20Support%20(Technical%20Assistance)/Phase%200/0.17%20Template%20Data%20Element%20Gap%20Analysis%20Matrix?csf=1&web=1&e=mA9TWB

**Comment by scleary1cs** [comment]
Already part of #585
