### ISSUE TITLE
Compare 24Oct_Master Requirement Matrix - APHL_Flexion with Roadmap/completed stories (Gap analysis) 

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#606]
## Spike Goal
Identify complete MVP requirements and outline path to completion for outstanding MVP requirements. 

## Timebox
OCT 26 EOD

## Notes
MVP spreadsheet can be found [here](https://docs.google.com/spreadsheets/d/154TovWQJ-btHDd-Gutm3uBq5EZLzzYBwQVoX0Ob4aag/edit#gid=465708544).
Roadmap can be found [here](https://lucid.app/lucidchart/6af50ece-e0bc-42cc-8752-911e407d605a/edit?invitationId=inv_68a62158-7ece-491e-9a0a-b6ea40db28b5&referringApp=slack&page=0_0#).

Saved a copy of response to the shared google drive: CDC TI > MVP

**Comment by SaraleCDC** [comment]
Yesterday, I have sent out the last set of requirements to be reviewed by 11/2. This is separate from the concurrent Development status tracking also to be finished by 11/2.
