### ISSUE TITLE
Intermediary Development Status Tracking

### ISSUE THREAD

**Issue by SaraleCDC** [CDCgov/trusted-intermediary#607]
# Work Request

**For the action item to review requirements for CDC leadership by Thursday, November 2nd , please note:
On tab “MVP Requirements Dev Oct” - Each Intermediary team should update the status of their development against each requirement (Column L, N)) and provide a description as to what functionality within their intermediary system aligns with the requirement (Column M,O).**

## Anticipated Ticket Size

Assign a size for this ticket.  Use "t-shirt sizes".

**- Large: Multiple people or longer than one day.**

## Anticipated Urgency Level

Assign an urgency level for this ticket.

**- Urgent: Request within the current sprint (may impact current work in progress).**

## Other Notes

https://aphlinformatics.atlassian.net/wiki/spaces/IR/pages/1820852269/Reference+Materials+-+Intermediary+Development#ETOR-MVP-Requirements-Matrix

**Comment by scleary1cs** [comment]
@sfradkin since this is a duplicate, ok to close? Or are duplicate stories handled in a different way?

**Comment by scleary1cs** [comment]
This is a duplicate story of #606
