### ISSUE TITLE
Metadata: Hospital Order Status

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#610]
# Story
As a hospital, so I can confirm my order has been received by the lab, I need to be able to view the delivery status of all orders I’ve submitted recently.

## Acceptance Criteria
- [x] The hospital is able to view the delivery status (e.g. pending, delivered, failed) of their orders.
- [x] The order metadata is available in the form of FHIR OperationOutcome
- [x] The hospital is able to view all orders submitted by them over the past 90 days.

### Research
- [ ] *Research work needed to complete the story*
- [ ] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [x] Figure out the tasks.
- [x] Create new enum for the different states for the delivery status.
- [x] Add new delivery status "column" to `PartnerMetadata` and associated other DB updates.
- [x] Update PostgresDao to retrieve new column
- [x] Update PostgresDao to write new data to database
- [x] Add stored data to metadata object for endpoint to return
- [x] Set delivery status to `FAILED` when the intermediary wouldn't forward on a message after accepting it (e.g. anything that happens within the `EtorDomainRegistration#handleOrders` method). - @tjohnson7021, @halprin 
- [x] Whenever we call the RS history API for the outbound order, we need to map their statuses to one of our status. - @halprin 
- [x] (See PR #770) Fix `Caused by: org.postgresql.util.PSQLException: ERROR: column "delivery_status" is of type message_status but expression is of type character varying.  Hint: You will need to rewrite or cast the expression.  Position: 54`. - @halprin 
- [x] When deploying a second time, we get the following issue: `ERROR:  type "message_status" already exists`.  Looks like we need to make the SQL statement `CREATE TYPE message_status...` conditional. - @jcrichlake, @halprin 

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-27 - Intermediaries will provide metadata required, including elements to calculate timeliness metrics

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-29 - Each Intermediary shall have a dashboard for some higher level internal monitoring metrics – team who is troubleshooting and supporting would need access to these different views of the system

**Comment by jcrichlake** [comment]
Posting statuses that ReportStream will return.  Got these from Ott:
VALID
ERROR
RECEIVED
NOT_DELIVERING
WAITING_TO_DELIVER
PARTIALLY_DELIVERED
DELIVERED
