### ISSUE TITLE
Metadata: Hospital Order Errors

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#611]
# Story
As a hospital, so I can determine how to correct a failed order, I need to be able to view the cause of all delivery failures for all orders I’ve submitted recently.
## Acceptance Criteria
- [x] The hospital is able to view the detailed errors of their orders.
- [x] The order metadata is available in the form of FHIR OperationOutcome
- [x] The hospital is able to view all orders submitted by them over the past 90 days.

###  Engineering
- [x] Add status message column to database
- [x] Update fetchMetadata function to return new column
- [x] Update upsert statement to store new reason
- [x] Update History API to return failure reasons from RS History API
- [x] Add failure reason and save metadata where the intermediary is failing the message
- [x] Propagate stored data into metadata API response   
- [x] Improve e2e tests. - @jcrichlake, @halprin 

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-27 - Intermediaries will provide metadata required, including elements to calculate timeliness metrics

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-29 - Each Intermediary shall have a dashboard for some higher level internal monitoring metrics – team who is troubleshooting and supporting would need access to these different views of the system

**Comment by jcrichlake** [comment]
https://app.zenhub.com/workspaces/engagement-6166edbd409257001e09f1b2/issues/gh/cdcgov/prime-reportstream/12925
