### ISSUE TITLE
Receiving Results via REST

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#615]
# Story
As a lab, so that test results can forwarded to a hospital, I need the intermediary to accept results via REST.

## Pre-conditions
- ReportStream is already able to send us a FHIR results message based upon an ORU from the lab.
- The incoming message is a valid FHIR lab test results message

## Acceptance Criteria
- [x] An indication of success or failure is returned to the calling service (e.g. an HTTP response)
- [x] The incoming FHIR results are only accepted if and only if it is sent from a trusted organization (e.g. ReportStream).
- [x] For production & staging: Results data is transmitted securely

###  Engineering
- [x] Create the TI results endpoint
  - [x] results endpoint skeleton (branch)
    - [x] handleResults method in EtorDomainRegistration @jorg3lopez 
  - [x] Enforce authentication
- [x] ResultController @saquino0827 
- [x] SendResultUseCase @basiliskus 
  - [x] Create `MessageSender` interface
    - [x] Initial implementation for `ReportStreamResultSender`
    - [x] Refactor `OrderSender` to use interface
  - [x] Create `SendMessageUseCase` interface
    - [x] Initial implementation for `SendResultUseCase`
    - [x] Refactor `ConvertAndSendDemographicsUseCase` to use interface
  - [x] Add `UnableToSendMessageException`
    - [x] Use exception in result sending classes
    - [x] Use exception in orders sending classes
    - [x] Use exception in demographics sending classes
- [x] Parse results
- [x] ResultResponse
  - [x] Return success/failure notice via HTTP response
- [x] Result Interface
  - [x] interface @jorg3lopez 
  - [x] HapiResult @saquino0827 @jorg3lopez 
- [x] Configure ReportStream to route ORU messages to the TI results endpoint @basiliskus 
  - [x] Create PR in RS to add settings ([created here](https://github.com/CDCgov/prime-reportstream/pull/13114))
  - [x] Get PR merged 
  - [x] Apply settings to RS staging
  - [x] Re add client keys to staging: `flexion.simulated-hospital`, `flexion.etor-service-sender`, `flexion.simulated-lab`
- [x] DoD items that will require work:
  - [x] Update swagger docs
  - [x] Update thread model
  - [x] Update load tests
  - [x] README docs
  - [x] Update `ReportStream Setup` in readme @basiliskus 

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*
- MVP-REQ-07

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-07 - Each intermediary will support at least one format for inbound results

**Comment by nvcllns** [comment]
615/616 do not reflect any transformation/manipulation between ORU received from PHL and ORU sent to HCO. Analysis needed in context of California implementation to determine LOE by Flexion/ReportStream to accommodate transforms on result payloads.
