### ISSUE TITLE
Simple Orders & Results Acknowledgements

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#617]
# Story
As a hospital, so that NBS order submission failures can be identified more quickly, I need an indication of success or failure when an order is received by ReportStream.

## Pre-conditions
- Orders or Results may fail later in the process (e.g. asynchronously) and are not in scope.

## Acceptance Criteria
- [x] If an order or result is sent to ReportStream, an indication of success or failure is returned. (e.g. an HTTP response is sufficient)
- [x] We have a documented list of response codes that ReportStream may return indicating success or failure that can be shared with our partners.

###  Engineering
- [x] Review past investigation into ReportStream response codes: https://github.com/CDCgov/trusted-intermediary/issues/632
- [x] Review ReportStream codebase to determine HTTP responses to expect for both waters and reports endpoints.
- [x] Document list of HTTP response codes that can be provided to partners.
  - `/api/reports` (swagger docs at `prime-router/docs/api/reports.yml`)
    - `400` Bad Request
      - No Sender name
      - Unknown Sender
      - An invalid message is passed
      - An invalid option is passed
      - An illegal argument is passed
      - An illegal state is present
      - Invalid receiver information
    - `411`: Length Required
      - Content Length Header Not found
      - Content Length is not a number
      - Content Length is a negative number
    - `413` Payload too large
      - Content is larger than allowed max bytes
    - `500` Internal Server Error
      - An unexpected error occurs
    - `200` Ok
      - If checking connection or validating payload, a successful 200 is returned
    - `201` Created
      - The message was successfully received
    
  - `/api/waters`
    - `400` Bad Request
      - No Sender name
      - Unknown Sender
      - An invalid message is passed
      - An invalid option is passed
      - An illegal argument is passed
      - An illegal state is present
      - Invalid receiver infromation
    - `401` Unauthorized
      - Not authorized to use the endpoint
      - Not authorized to send and receive data through the endpoint.
    - `411` Http Length Required
      - Content Length Header Not found
      - Content Length is not a number
      - Content Length is a negative number
    - `413` Http Payload too large
      - Content is larger than allowed max bytes
    - `500` Internal Server Error
      - An unexpected error occurs
    - `200` Ok
      - If checking connection or validating payload, a successful 200 is returned
    - `201` Created
      - The message was successfully received

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- See https://github.com/CDCgov/prime-reportstream/tree/master/prime-router/docs/api
- MVP-REQ-58

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-58 - Each intermediary will support transport level acknowledgment

**Comment by scleary1cs** [comment]
Document in IG, double check what lives on RS, do they already have it documented (if yes put pointer in our IG)?

**Comment by saquino0827** [comment]
This was documented in the Programmers Guide: https://docs.google.com/document/d/19xii5OlERxziIRfHftVzz8o1u9AHIbDdJlOb3B3mVVw/edit
