### ISSUE TITLE
Linking Orders to Results

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#621]
# Story
As a hospital (or lab), so that I can know if a result has been returned for an order I placed (or vice versa), I want order and results metadata to be provided together.

## Pre-conditions
- Orders and results processing are already supported.
- Any modification to the result message based on the order is out of scope of this story.
- Calculating stats for unsolicited orders is out of scope of this story.

## Acceptance Criteria
- [x] When retrieving order metadata, metadata for the corresponding result is included.
- [x] When retrieving result metadata, metadata for the corresponding order is included.

## Note
- Added bonus based on how this was implemented: results to results and orders to orders matching; however test cases would need to be created in the future if that becomes a real use case

### Research
- [x] What unique identifier can we use to link the order and result?
  - [x] Is there already a way to do this in the HL7 specs? **Placer order number: ORC.2 & OBR.2** (they are required, and should be the same value)
    - [x] Which one should we rely on? **ORC.2** & **MSH.4** (decided not to also key based on Patient ID for now) 
    - [x] What does that look like in FHIR?
    - [x] Ask what AIMS is doing for this: They are assigning an internal ID to each order received which is what they use to link back to result. For that internal ID, they are using the placer order number (ORC-2) from the order message to assign that internal ID -- but one that also included the assigning authority.
    - [x] Consider how this may work under reflex testing, re-orders, amended orders, etc.
- [x] There is the potential that this will also allow us to take data from an order and add it to a result, but this may or may not be something the intermediary wants to support.

###  Engineering
- [x] Stream 2 to sync up with Stream 1
  - [x] Test integration of different PRs
- [x] Add fields to metadata table - @halprin 
  - [x] Add `placer_order_number`, `sending_application_id`, `sending_facility_id`, `receiving_application_id`, `receiving_facility_id` to the partner metadata table - @halprin 
  - [x] Extract fields from FHIR message and write them into the metadata table @jorg3lopez 
    - [x] Orders
      - [x] Extract placer order number @jherrflexion 
      - [x] Extract sending application details @jorg3lopez
        - [x]  Refactor to SendingApplicationDetails Object
      - [x] Extract sending facility details @jorg3lopez 
        - [x]  Refactor to SendingFacilityDetails Object 
      - [x] Extract receiving application details @jorg3lopez 
      - [x] Extract receiving facility details @jorg3lopez 
        - [x]  Refactor to ReceivingFacilityDetails Object
      - [x] Add unit tests @jorg3lopez 
    - [x] Results
      - [x] Extract placer order number @saquino0827 
      - [x] Extract sending application details @saquino0827
        - [x]  Refactor to SendingApplicationDetails Object 
      - [x] Extract sending facility details @saquino0827 
        - [x]  Refactor to SendingFacilityDetails Object
      - [x] Extract receiving application details @luis-pabon-tf 
        - [x]  Refactor to ReceivingApplicationDetails Object
      - [x] Extract receiving facility details @luis-pabon-tf 
        - [x]  Refactor to ReceivingFacilityDetails Object
      - [x] Add unit tests
    - [x] Refactor Order and Result data extraction into a generic MessageHelper.
    - [x] Create MessageDetails POJO @jorg3lopez 
    - [x] FHIR Path
      - [x] Create method for extracting string value using fhir path @jorg3lopez 
      - [x] Create enum for fhir paths @saquino0827 
        - [x] Add enum to ETOR/plugin for centralized use @saquino0827 
    - [x] General refactoring 
      - [x] HapiOrderTest @jorg3lopez 
      - [x] HapiResultTest @jorg3lopez 
      - [x] HapiResult @jorg3lopez 
      - [x] HapiOrder @jorg3lopez 
    - [x] Testing
      - [x] All unit tests pass
      - [x] Application compiles
    - [x] Add javadocs to new files @jorg3lopez 
    - [x] Save these new fields to the metadata storage. - @halprin 
- [x] Check for linked orders/results and possibly write to linking table @basiliskus 
  - [x] Create the linking table @basiliskus 
  - [x] Implement check for linked orders/results (Partner Metadata Orchestrator) @basiliskus 
  - [x] Write linked order/results entries in linking table, if needed, using the additional fields added to the metadata table to identify the orders and results to link
  - [x] Call new partner metadata orchestrator method in the send order/result usecase @basiliskus 
  - [x] Refactor to use new table structure @basiliskus 
- [x] When requesting metadata, retrieve linked order/results using linking table
  - [x] Retrieve linked message IDs (only IDs, not required to get partner metadata for linked messages for now)
  - [x] Marshal the linked message ids into the `OperationOutcome` FHIR message
    `Output will be a single OperationOutcome, just like it is today.  And for each connected ID, there will be one item added to the issues list inside.`
- [x] Add e2e test that will send an Order and Result with matching metadata to create the link, and then will query the metadata endpoint to make sure the OperationOutcome has the expected resources for both 

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- MVP-REQ-19: "Each intermediary system should be able to link physical samples to an electronic order and integrate outgoing data with previously stored order data to satisfy hospital requirements. "
- [Miro board with design sketches](https://miro.com/app/board/uXjVKbLwru0=/)

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-19 - Each intermediary system should be able to link physical samples to an electronic order and integrate outgoing data with previously stored order data to satisfy hospital requirements

**Comment by nvcllns** [comment]
Documenting this here as Scott's summary on 2/23 office hours was very useful - the spirit of this MVP requirement is to be able to link the order w/ result transactions via metadata to know if the round trip transaction is complete. This is NOT about extracting data from orders and inserting them back into results.

**Comment by scleary1cs** [comment]
Email - Matching Results with Orders - 03/20/24

Hey Riki,
Do you know what fields the AIMS Intermediary uses to match a results message to an order message?  Do you use a combination of Sending Facility identifier with Placer Order number?  Do you look to a patient identifier, too?
Thanks
-Daniel

----

We are assigning an internal ID to the order and that’s what we are matching on – we are using the placer order number (and since we capture the assigning authority with that, we are not also looking somewhere else)
Riki

----

This is to inform story 621. 
Effectively this is combining information from the Placer Order Number (the actual ID) in ORC-2/OBR-2 of the order message with the assigning authority for that Placer Order Number
- which could be found in ORC-2.3 (Universal ID for the assigning authority of the Placer Order Number), if we’re lucky enough to receive this and, it is in fact, a universal ID like an OID for the application
- Or could be pulled from the universal ID in MSH-3 (Sending Application) or MSH-4 (Sending Facility) – I think we could use either of these as long as they utilize a universal ID like an ISO OID in MSH-3.2 and/or MSH-4.2

 -Daniel

**Comment by JohnNKing** [comment]
Fixing load test captured as #1044
