### ISSUE TITLE
Persist original order/results messages (for troubleshooting)

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#622]
# Story
As an intermediary engineer, so that I can view the history of a message being transported through the intermediary, I need all messages to be persisted on a temporary basis with encryption at rest.

## Acceptance Criteria
- [x] A message that passes through the ReportStream Universal Pipeline is stored at each step

###  Engineering
- [x] Asked RS about what they do to persist messages as they flow their system. - @halprin 
- [x] Waiting for answers.

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*
- MVP-REQ-21 and MVP-REQ-44

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-21 - Both intermediaries shall have storage capabilities for In-progress orders

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-44 - Each intermediary will implement data encryption measures for both data-at-rest and data-in-transit

**Comment by halprin** [comment]
Reached out to ReportStream to see what they do for us.  Based on their responses, it all looks good to me and I think we meet the letter and spirit of the MVP requirements outlined in this story.  Assuming we get access to their blob storage and learn how to interact with it, we should be able to easily troubleshoot anything that comes through.

Specifically, I asked the following...

> 1. RS saves a copy of the message at each step of the universal pipeline, correct?
> 2. How long are the messages saved?  I've heard that they are expunged at some point.
> 3. Are the messages encrypted at rest?
> 4. When is the message first saved upon initial ingestion into RS?  Is the initial message saved only when a 2xx is returned from the waters/reports endpoint?  Or does RS save any message sent in even if some 4xx is returned?  E.g. there's a few initial validation checks that happen that can result in some 4xx status code, and so I'm wondering if RS still saves the message in that instance.
> 5. Lastly, is the message saved one last time before it is sent out the door to the receivers?

Patric responded with the following answers.

> 1. Yes, the message is stored in blob store at each step.
> 2. The messages are persisted for 60 days, at which point they are deleted forever
> 3. Yes, encrypted at rest
> 4. I believe we save no matter what, but in the event of an ingest failure it would go to our poison queue/DLQ rather than blob store (Arnej?)
> 5. The batch step is the last step in the pipeline (immediately precedes sending), and messages are stored there
