### ISSUE TITLE
Terraform Drift for Every Apply

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#627]
# DevEx/OpEx

There seems to be drift for every apply we do even though nothing was changed in Azure and nothing was changed in the Terraform code.  As of this writing, it seems to affect two resources, `module.template.azurerm_linux_web_app.api` and `module.template.azurerm_monitor_diagnostic_setting.app_to_logs`.  You can view the drift on nearly any deployment.

## Tasks

- [ ] Something.

## Additional Context

https://flexion.slack.com/archives/C055XTF22B0/p1684185710682809

**Comment by pluckyswan** [comment]
Closing this issue as we have fixed this by messing with CDC tags in terraform.
