### ISSUE TITLE
Run Load Tests Against Staging

### ISSUE THREAD

**Issue by halprin** [CDCgov/trusted-intermediary#628]
# DevEx/OpEx

Improve our load tests to run against our Staging environment.

We may need to re-examine our load test assumptions, we are currently ramping up to 1k users and then hammering the various endpoints, this may be an amount of load that is either far off in the future or will require multiple instances of the intermediary running to handle it.

## Tasks

- [ ] Set up the `locust` load test in the staging enviroment
- [ ] Set up the load tests to run periodically or after each deployment

## Additional Context

https://docs.locust.io/en/stable/running-in-docker.html

https://flexion.slack.com/archives/C055XTF22B0/p1686933099084339

**Comment by basiliskus** [comment]
Currently waiting for our CDC staging environment creation

**Comment by pluckyswan** [comment]
Closing this issue as it is covered by an existing [card about setting up load tests in azure ](https://github.com/CDCgov/trusted-intermediary/issues/1122)
