### ISSUE TITLE
Review Pre-Implementation Data Collection Template (for Evaluation)

### ISSUE THREAD

**Issue by GrantB-CDC** [CDCgov/trusted-intermediary#631]
# Work Request

Review Pre-Implementation Data Collection Template (for Evaluation)

-Review to ensure the template is set up sufficiently for collection pre-implementation data for the purpose of evaluation.

## Link to File
https://cdc.sharepoint.com/:x:/r/teams/OLSS_ETOR_ReportStream/Shared%20Documents/General/ETOR%20for%20Newborn%20Screening/3.%20ReportStream%20Implementation%20Support%20(Technical%20Assistance)/Phase%200/0.21%20Template%20Pre-Implementation%20Data%20Collection%20Instruments/Drafts%20and%20Archive/Pre-Implementation%20Data%20Collection%20Template.xlsx?d=wcdd1198c503d402eb446d8340102d644&csf=1&web=1&e=Il1hev

**Comment by GrantB-CDC** [comment]
Link to File: https://cdc.sharepoint.com/:x:/r/teams/OLSS_ETOR_ReportStream/Shared%20Documents/General/ETOR%20for%20Newborn%20Screening/3.%20ReportStream%20Implementation%20Support%20(Technical%20Assistance)/Phase%200/0.21%20Template%20Pre-Implementation%20Data%20Collection%20Instruments/Drafts%20and%20Archive/Pre-Implementation%20Data%20Collection%20Template.xlsx?d=wcdd1198c503d402eb446d8340102d644&csf=1&web=1&e=LGAaAl

**Comment by JohnNKing** [comment]
Needed by next Tuesday. File should be fully completed Fri afternoon.

**Comment by nvcllns** [comment]
On hold - reprioritizing agenda and material prep for Alabama site visit for this week's (11/7) program meeting. Will communicate out when this is ready for review, but will mostly fall back to CDC evaluation office. Thanks!
