### ISSUE TITLE
ORM Validation Research

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#632]
## Spike Goal

1. New stories are created or the existing validation stories are updated based on our findings.

O.G. goal:

1. Understand what validations are currently being done in the HL7 ORM => FHIR conversion 
2. Understand what types of validation we will want and where those should occur.

## Timebox

3 days

### Updated new tasks.

- [x] New stories identified.
- [x] New stories written. - @JohnNKing 
- [x] Research findings moved to the new stories.

### Old tasks not needing to be finished

- [x] Document what validation that is happening already in RS today.
  - [x] What would cause the API endpoint to fail immediately?  E.g. a `400` is returned. @jcrichlake 
  - [ ] What would cause the pipeline to fail which would require a history API call to find out about? - @jcrichlake 
- [x] Document what validation that TI does (not JSON, JSON but not FHIR, FHIR but extra fields/missing fields) today.- **@tjohnson7021** 
- [ ] If RS fails to send a message (to TI) due to a bad format, how does the customer know?  How do we want our customers finding out? @jorg3lopez 
- [x] Document if RS exposes messages that fail based on some mechanism that TI would have (e.g. the `etor-ti` topic).
- [ ] See if we can be notified when an error occurs in RS.
- [ ] Figure out if there are other validations that we need to do to ensure delivery to its final destination.  E.g. we get perfectly good FHIR, but there's something that prevents us from delivering this to RS and prevents RS from delivering it to the final destination.
- [ ] Did the e-mail notification on failure get implemented in ReportStream? - @jorg3lopez 

## Proposed New Stories

Epic:
1. If order (or results?) delivery fails, we notify the sender.
2. Failures can be viewed via the metadata endpoint.

Stories:

- Handle errors that occur in TI's handling of the order.
- Handle errors that occur when TI gets a non-200 from interacting with RS.
- Handle errors that occur when TI gets a 200 but RS cannot deliver the message.
- Handle errors that occur when the sender gets a 200 but RS cannot deliver the message to TI.
- Research: Understand EHR constraints and what they need to receive (to stop re-attempting deliveries, or to mark order as delivered) or what they can receive (e.g. sync vs async).

## Findings
  What would cause the API endpoint to fail immediately?  E.g. a `400` is returned.

### 400 Bad Request
- Sender name is blank
- Sender is unknown
- invalid Schema or Formate Paramater = Invalid Parameter Exception
- Invalid receiver name
- unknown sender
- unknown schema
- missing content type
- Not a mimeType
- Blank messages if hl7- v2

### 401 Unauthorized
- Bad authentication
- Bad Authorization

### 404 Not Found
- Organization does not exist (need to test this one)

### 411 Length Required
- Request Header "content-length" is missing, "content-length" header is not a number, "content-length " is < 0

### 413 Payload Too Large
- "content-length" header is > 50 mb, request body is greater than 50 mb

### 500 Internal Server Error
-

### Other
- Further 400s
- Unsupported HL7 message type
- rawMessage is empty
- if FHIR bundle is empty
- Unable to parse FHIR data
- IllegalStateException Unexpected sender format

## Notes

- We need to ensure data is not lost; document any existing scenarios where this could occur.
- How do we get visibility into validation errors that occur?
- See https://aphlinformatics.atlassian.net/wiki/spaces/IR/pages/2060419190/ETOR+Intermediary+Metadata+Alignment#Defining-the-Types-of-Errors

**Comment by jcrichlake** [comment]
Posting a link from Ott that has some pretty detailed RS validation info
https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/design/design/validation/design.md

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-04 - Each intermediary will create an MVP with the capability to support when the facility receives the entire order, and the intermediary is responsible for validating and transforming the order for PHL

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-05 - Each intermediary will create an MVP wherein the system accepts all order-related information from the facility. The intermediary is responsible for receiving the order, performing validation, and carrying out transformations for PHL LIMS

**Comment by jorg3lopez** [comment]
### If RS fails to send a message (to TI) due to a bad format
- status code of 400
output:

{
    "id": null,
    "submissionId": 290,
    "overallStatus": "Error",
    "timestamp": "2023-11-08T18:18:50.431Z",
    "plannedCompletionAt": null,
    "actualCompletionAt": null,
    "sender": "",
    "reportItemCount": null,
    "errorCount": 1,
    "warningCount": 0,
    "httpStatus": 400,
    "destinations": [],
    "actionName": "receive",
    "externalName": "",
    "reportId": null,
    "topic": null,
    "errors": [
        {
            "scope": "report",
            "message": "String did not contain any HL7 messages",
            "errorCode": "UNKNOWN"
        }
    ],
    "warnings": [],
    "destinationCount": 0
}

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-15 - Intermediaries will establish, utilize, and validate a common set of data elements

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-36 - Each intermediary will have the same validations performed for all data exchange formats (e.g, NIST)

**Comment by tjohnson7021** [comment]
### **Document what validation that TI does**: 
[Full error notes here...](https://docs.google.com/presentation/d/1Ey15TdknWef2o4MI7VTHB6eZQ4sRrgXOvoRKLgF6hwU/edit?usp=sharing)
### Summary:
**Not JSON** - errs out
**JSON, but not FHIR** - errs out
**FHIR, but has extra fields** (duplicated `MessageHeader`) - completes with no issue 
**FHIR, but has extra fields** - (added `"extraField": "extra field"`) - completes with warning
**FHIR, but missing fields** - If you remove the `id` from `Bundle`, it errs out, but removing other fields does not seem to cause a problem (`Bundle.meta, .identifier, .type, .timestamp`)
**FHIR, but missing fields** -  If you remove the `resourceType:` from any FHIR resource, it errs out.

**Comment by JohnNKing** [comment]
The question came up recently regarding HL7 2.3 ORM support. I also tried submitting several sample messages (one from the Postman collection, the other being MN's ORM sample from our repo) with the HL7 version number in the MSH header changed from 2.5.1 to 2.3. The result is an error:

{
    "id": null,
    "submissionId": XXXXXXX,
    "overallStatus": "Error",
    "timestamp": "2023-11-09T22:33:51.902Z",
    "plannedCompletionAt": null,
    "actualCompletionAt": null,
    "sender": "",
    "reportItemCount": null,
    "errorCount": 1,
    "warningCount": 0,
    "httpStatus": 400,
    "destinations": [],
    "actionName": "receive",
    "externalName": "",
    "reportId": null,
    "topic": null,
    "errors": [
        {
            "scope": "item",
            "indices": [
                1
            ],
            "trackingIds": [
                null
            ],
            "field": "",
            "message": "Ignoring unsupported HL7 message type ",
            "errorCode": "UNKNOWN"
        }
    ],
    "warnings": [],
    "destinationCount": 0
}

**Comment by JohnNKing** [comment]
In terms of better understanding HL7 version-specific validation in RS, I found a (very hackish) way to make a local instance accept HL7 2.3 ORM messages:
1. The sample message MUST have an MSH-9-3 (e.g. ORM_O01), otherwise it will fail on https://github.com/CDCgov/prime-reportstream/blob/27c784530e1f94138276b064df64ec007613564c/prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt#L94
2. Change "2.5.1" to "2.3" on https://github.com/CDCgov/prime-reportstream/blob/27c784530e1f94138276b064df64ec007613564c/prime-router/src/main/kotlin/cli/tests/CompareData.kt#L418
3. The allows the conversion to take place, though I only seem to be getting MSH related content.

**Comment by JohnNKing** [comment]
Created:
https://github.com/CDCgov/trusted-intermediary/issues/659
https://github.com/CDCgov/trusted-intermediary/issues/660
https://github.com/CDCgov/trusted-intermediary/issues/661
https://github.com/CDCgov/trusted-intermediary/issues/662
https://github.com/CDCgov/trusted-intermediary/issues/663
https://github.com/CDCgov/trusted-intermediary/issues/664
