### ISSUE TITLE
Comparing development status to the 7 services

### ISSUE THREAD

**Issue by SaraleCDC** [CDCgov/trusted-intermediary#637]
# Work Request

The ETOR Intermediary service definitions can be found here - https://aphlinformatics.atlassian.net/l/cp/f5EgPMBA

In the MVP Requirements Matrix, I have added a tab called "Mapping to the 7 services," please populate column C with Flexion's current completed capabilities. You can find the most up to date file here: https://aphlinformatics.atlassian.net/wiki/spaces/IR/pages/1820852269/Reference+Materials+-+Intermediary+Development#ETOR-MVP-Requirements-Matrix

## Anticipated Ticket Size

Assign a size for this ticket.  Use "t-shirt sizes".

- Small: One person for half a day or less.

## Anticipated Urgency Level

Assign an urgency level for this ticket.

- Urgent: Request within the current sprint (may impact current work in progress).
- Complete by EOD November 3

## Other Notes

- Any other notes to help clarify this task for the team.  Please link or attach a document to the ticket if one exists.

**Comment by scleary1cs** [comment]
Flexion response attached [02Nov_Master Requirement Matrix - APHL_Flexion - Flexion response.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWloQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e2c706d36515b7a8ba2d598e9fae9ed11ae86aa/02Nov_Master%20Requirement%20Matrix%20-%20APHL_Flexion%20-%20Flexion%20response.xlsx).
And saved to shared drive CDC TI/MVP/
