### ISSUE TITLE
FHIR => HL7 ORU

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#641]
# Story
As a hospital, so that ReportStream can send NBS results in a format that my EHR can receive, I need ReportStream to send HL7 ORU messages based on an incoming FHIR result.

## Pre-conditions
- An inbound FHIR message can be received successfully by ReportStream.
- The incoming message is a valid FHIR lab test results message

## Acceptance Criteria
- [x] The outgoing ORU is a valid HL7 v2.5.1 message.
- [x] The translated result message is transmitted soon after the FHIR result has been received.
- [x] Only the intended hospital receives the result message
- [x] The incoming FHIR results are always sent through the TI service (e.g. they don't go directly to the hospital)

###  Engineering
- [x] Identify cause of inconsistent transformation seen by our development team
- [x] FHIR to HL7 mapping for ORU
  - [x] Test current mapping 
  - [x] Document missing fields
    - `OBX-4`: Observation Sub-ID
    - `OBX-29` (value `RSLT`, `SCI`, `QST`) 
  - [x] Update ORU mapping RS 
    - [x] Create `metadata/hl7_mapping/receivers/Flexion/TIResults` to replace `metadata/hl7_mapping/ORU_R01/ORU_R01-base` @basiliskus 
    - [x] Check what is required to map `OBX-4`
  - [x] Remove batch headers and footers in final HL7
  - [x] Update example files for ORU samples after transformation @basiliskus 
    - [x] Fix e2e tests 
  - [x] Look into encoding issue in final message: `The�purpose of newborn screening...`
    - The problem was in the original ORU example file. The file has been fixed
- [x] Fix results routing issue
  - [x] Identify solution to routing based on the original sender (i.e. the lab)
    - [x] Decided to use `MSH.3`, `MSH.4`, `MSH.5` and `MSH.6` for routing 
  - [x] Consult the RS team regarding our proposed solution
    - [x] Will use `jurisdictionalFilter` in org settings to filter by `Organization` (`MSH.X`) 
      - [x] Make sure we have the required FHIR resources from MSH to create the filters @basiliskus 
        - `Bundle.entry.resource.ofType(MessageHeader).destination.receiver.resolve().identifier.where(value = 'simulated-hospital').exists()` 
  - [x] Test that filters work as intended and are sufficient
- [x] RS configured to route the result to the hospital @basiliskus 
  - [x] Create PR in RS to add settings (created [here](https://github.com/CDCgov/prime-reportstream/pull/13308))
  - [x] Add ORU sample test file
  - [x] Get PR merged 
  - [x] Apply settings to RS staging (Update schema settings)
  - [x] Re add client keys to staging: `flexion.simulated-hospital`, `flexion.etor-service-sender`, `flexion.simulated-lab`
- [x] Update IG @saquino0827 
  - [x] Add entry for the `ORU` message in the implementation guide @saquino0827 
  - [x] Update `Results` section in `etor-nbs.html#results` @saquino0827 
- [x] Test the full Results flow 
  - [x] Make sure  "Only the intended hospital receives the result message"
  - [x] Test RS route settings with 2 different pairs of senders & receivers 
  - [x] Test results flow in RS staging @basiliskus 

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-09 - Each intermediary will support at least one format for outbound results

**Comment by scleary1cs** [comment]
Reference [](https://app.zenhub.com/workspaces/cdc-ti-633de70d939f6c00155f3722/issues/gh/cdcgov/trusted-intermediary/731)
