### ISSUE TITLE
Metadata for Internal Troubleshooting 

### ISSUE THREAD

**Issue by jcrichlake** [CDCgov/trusted-intermediary#643]
# Story
As a hospital or lab, so the status of undelivered newborn screening orders can be determined during troubleshooting, I need a CDC engineer to be able to get internal metadata about orders submitted over the past 90 days.

## Pre-conditions
- [x] Internal metadata story is completed and merged (#588)

## Acceptance Criteria
- [x] Event data is stored and remains after restarts.
- [x] Event data is searchable so that we can easily identify messages that were not sent back to ReportStream Core for delivery to the PHL.

###  Engineering
- [ ] Team has decided on how we are going to persist these after restarts of the application
  - [ ] Determine how we persist data, DB? File? 
- [ ] Implement the determined method from the above step
- [ ] DO the thing

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] Threat model updated
  - [ ] API documentation updated
  - [ ] Source code documentation created when the code is not self-documenting
- [ ] Code quality tasks completed
  - [ ] Logging added where useful
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by JohnNKing** [comment]
> As an engineering team member, so that I can troubleshoot messages through the intermediary, I need internal metadata that persists across restarts. I also need to be able to identify messages that may have not completed the process, preferably in a programatic or automated fashion.

My feedback:
1. Is there a way to capture the value proposition from the hospital and/or PHL perspective?
2. Should we narrow the scope to newborn screening?
3. Clarify scope around programatic/automated querying (perhaps defer to a future story?)

As a hospital or lab, so the status of undelivered newborn screening orders can be determined during troubleshooting, I need a CDC engineer to be able to get a list of all orders submitted over the past 90 days.

**Comment by scleary1cs** [comment]
What ID does AL and LA using to uniquely identify an order?

**Comment by scleary1cs** [comment]
https://miro.com/app/board/uXjVMM69QGk=/?share_link_id=995893748525

**Comment by JohnNKing** [comment]
Perhaps this can be closed? (IIRC, this was created as an internally focused metadata effort that might have preceded the other metadata stories.)

**Comment by JohnNKing** [comment]
Previously completed via other metadata stories
