### ISSUE TITLE
Add auto-formatting to codebase to apply consistent formatting

### ISSUE THREAD

**Issue by jcrichlake** [CDCgov/trusted-intermediary#647]
# DevEx/OpEx
OPTION A:
Currently we are not formatting our local code when we are developing it.  We should look into adding https://editorconfig.org/ which should allow us to have auto-formatting files locally without needing to run the applySpotless job.   

OPTION B: 
Look into having the spotless apply settings be automatically applied regardless of IDE.

## Tasks

- [x] Set up EditorConfig file locally to match Spotless expectations. 

- [x] EditorConfig needs to work in at least intelliJ, VS Code, and Fleet

**Comment by basiliskus** [comment]
Look into: https://gist.github.com/rflpazini/14d757a6ebdc3a5549e7c5bf6d7569e1
