### ISSUE TITLE
Exploring ReST Alternatives

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#652]
## Spike Goal
Determine how we might support limited integration options for EHR's (e.g. MLLP/VPN), and how that might or might not be possible via ReportStream.

## Timebox
Time allocated (2 FTE days)

## Notes
- See https://flexion.slack.com/archives/C04FT9U8MPB/p1699387231073479
- See https://github.com/CDCgov/trusted-intermediary/issues/899
- See Retreat Notes

**Comment by nvcllns** [comment]
January 2024 Retreat Action Item: The ask is for Flexion and ReportStream engineers to jointly collaborate on a list of transport options to expand inbound options into RS. A starting point is to sync inbound to outbound. Once there are recommendations available, the LDX DMI Steering Group will formally endorse the plan. (PoCs are Rebecca McNall and Rishi Tarar.) Another research input is to compare with EHR certification criteria.

**Comment by scleary1cs** [comment]
[Link to retreat](https://cdc-my.sharepoint.com/personal/uwx1_cdc_gov/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fuwx1%5Fcdc%5Fgov%2FDocuments%2FETOR%2F2%2E%20Cross%2DIntermediary%20Coordination%2FJan%202024%20Retreat%20Planning) notes, presentations, and agendas.
