### ISSUE TITLE
New ReportStream Metadata API & Authentication

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#690]
# Story
As a hospital or lab, so that I can use the existing ReportStream credential flow, I need a new metadata endpoint that retrieves the metadata from the Intermediary service.

## Pre-conditions
- Access to metadata for hospitals and labs has already been implemented.
- Hospital or Lab is able to login to RS.
- Linking work is done.
 
## Acceptance Criteria
- [x] The hospital is able view their order/results metadata through ReportStream if and only if they've successfully authenticated with their RS credentials. 
- [x] The lab is able to view their order/results metadata through ReportStream if and only if they've successfully authenticated with their RS credentials.

### Research
- [x] *Research work needed to complete the story*
- [x] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [x] Codify formal requirements for RS.  See notes bellow. - @halprin, @scleary1cs 
- [x] Send formal requirements to RS.
- [x] Figure out how to authenticate to TI from Report Stream (Find where RS is calling TI for orders?)
- [x] Add wrapper endpoint to report stream that calls the intermediary metadata endpoint
- [x] Validate that the new endpoint fails when not authenticated
- [x] Unit tests for new endpoint
  - [x] Auth endpoint
- [x] How to pass back TI response body unchanged through RS 
- [x] Ask RS folks about release process if there's anything more than just getting the change into the master branch and then waiting
- [x] TI. origin/stream1/690/passthrough
  - [x] Update use cases to retrieve and store report id instead of submission id
  - [x] Fix any broken test cases related to the above
- [x] RS halprin/ti-690/metadata-passthrough (Branch that contains a mostly complete function sans auth)
  - [x] Add a receiver metadata endpoint.  This uses the existing authorization of other receiver endpoints.
  - [x] Add a sender metadata endpoint.  This uses the existing authorization of other sender endpoints.
  - [x] Add environment variables for TI endpoint in RS call 
  - [x] Both metadata endpoints need to convert the passed-in ID to the ID that TI knows about (walk the lineage).
  - [x] Comment for endpoint stating that it shouldn't be changed except by a member of the TI team
  - [x] Unit tests.
  - [x] Refactor RS functions to pull duplicate code up into `ReportFileFunction.kt` I think the initialization of the vars from response to the jksCredential can be a data class along with 2 other suspending functions to call the duplicate suspending functions.  

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] Threat model updated
  - [x] API documentation updated
  - [x] Source code documentation created when the code is not self-documenting
- [x] Code quality tasks completed
  - [x] Logging added where useful
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [x] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [x] Testing tasks completed
  - [x] Load tests passed
  - [x] Unit test coverage of our code >= 90%
- [x] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [x] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes

We will be making a new Azure Function for ReportStream.  This function will be similar to the one for the history API endpoint, meaning our function will represent an HTTP endpoint and also require RS authentication/authorization.  The main operation of this function will be to be a passthrough to our metadata endpoint.  Meaning, the unique ID passed to this new RS endpoint will be forwarded to our metadata endpoint, and any response body we return from our metadata endpoint will be delivered back as the response body of the RS endpoint.

- RS requirements.
  - We need the metadata API to be authenticated with ReportStream's authentication.  Users should be able to call the metadata endpoint using the exact same credentials that they use to send orders or results into ReportStream.
  - Ownership of the metadata endpoint needs to appear like it belongs to ReportStream.

**Comment by scleary1cs** [comment]
https://flexion.slack.com/archives/C048S3GPSQG/p1705075066796379

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-27 - Intermediaries will provide metadata required, including elements to calculate timeliness metrics

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-27 - Intermediaries will provide metadata required, including elements to calculate timeliness metrics

**Comment by scleary1cs** [comment]
Write a new Azure function in RS that gets authenticated (Like a pass through) that will call our metadata API.

**Comment by scleary1cs** [comment]
Report versus action?

**Comment by scleary1cs** [comment]
Fast follow stories need to be created.

**Comment by scleary1cs** [comment]
Fast follow stories need to be created.

**Comment by scleary1cs** [comment]
Running RS locally (for passthrough endpoints) #1058

**Comment by scleary1cs** [comment]
Running RS locally (for passthrough endpoints) #1058
