### ISSUE TITLE
Apache Client5 v5.3 bug

### ISSUE THREAD

**Issue by jorg3lopez** [CDCgov/trusted-intermediary#723]
# Bug

## Describe the Bug
After upgrading Apache HTTP Client from version `5.2.3` to `5.3`, we encountered significant changes in how POST requests are built due to deprecated methods. A critical issue arose with this update, specifically related to header management (using org.apache.hc.core5.http.header). This was causing an internal exception that prevented TI from sending a payload to RS. Despite adjusting our code for these changes (during testing), we're consistently encountering a "format Exception" due to missing/corrupted data when receiving a response body from a HTTP request.

## Impact
This bug is severely impacting our ability to execute HTTP requests reliably, causing disruptions in functionalities that depend on external API calls. The inability to bypass this exception is hindering our development and deployment processes.

## To Reproduce

1. Live test `ReportStreamOrderSender::getRSToken`, this will give you the import error
2. Once you fix the import error, debug the test case and you will get the format exception` error.
3. Delete local branch for live testing

## Expected Behavior

The expected behavior is that the response body from HTTP requests are not corrupted or missing any data from the sender.

## Screenshots
Incompatible import
<img width="576" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTVXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b02da91a5254e96ff73e705913596b45cc844ee7/image.png" alt="image.png" />

Format exception
<img width="1080" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTlXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed8d45168b2c3fa3319dae002f477ea728c235b9/image.png" alt="image.png" />

## Logs

<img width="1606" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXhXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc1da4fc36b7365713b45009c6049c7594f9dc23/image.png" alt="image.png" />

## Version

Apache HTTP Client version 5.3

**Comment by halprin** [comment]
I'm not sure what the problem that you're seeing with the headers are.  I don't see it.  Super weird about the response body being truncated!

**Comment by halprin** [comment]
Did some digging into this.  The culprit behind the response body being truncated is a bug in the Apache Fluent API code.  Here's the [bug](https://issues.apache.org/jira/browse/HTTPCLIENT-2312) filed in their issue tracker, and here's the [PR](https://github.com/apache/httpcomponents-client/pull/521) that fixes the bug.  The general problem is that they only ever copied up to 256 bytes of the response body no matter what.  The fix looks to be slated for 5.3.1.  I do not know when that version will be released.
