### ISSUE TITLE
Technical Assessment to Inform Feasibility, Project Planning for California Implementation Site

### ISSUE THREAD

**Issue by nvcllns** [CDCgov/trusted-intermediary#731]
# Completion Criteria
- [x] LOE for transforming an ORU from CDPH GDSP into one that is consumable by UCSD (flattening of the structure)
  - [x] Including LOE for covering the MSH field gap (complex fields to simple)
- [x] LOE for ingesting the OML payload from UCSD
- [x] LOE for acting as a pass-through for ACKs produced by both CDPH GDSP and UCSD
  - [x] Can we do a real pass-through with RS vs the full universal pipeline?

# Work Request

Technical Assessment to Inform Feasibility, Project Planning, and Timelines for California Implementation Site

## Anticipated Ticket Size

- **Large: Multiple people or longer than one day.** (To initiate by 1/2; to be complete for internal review by 1/12.)

## Anticipated Urgency Level

- High: Request to include in the next sprint. 

## Other Notes

Please see https://cdc.sharepoint.com/teams/OLSS_ETOR_ReportStream/Shared%20Documents/General/ETOR%20for%20Newborn%20Screening/4.%20ReportStream%20Initial%20Implementation%20Coordination/California/CA%20Project%20Planning/Proposed%20Approach_Owners_Timeline_CA%20Imp%20via%20RS.docx?web=1 for details.

**Comment by nvcllns** [comment]
Flexion sprint to begin 1/2/24 should include a technical assessment to inform:

1. LOE for transforming an ORU from CDPH GDSP into one that is consumable by UCSD 

2. LOE for ingesting the OML payload from UCSD 

3. LOE for acting as a pass-through for ACKs produced by both CDPH GDSP and UCSD 

**Key question for week of 12/18 - does Flexion/Agile 6/JMC team have the necessary inputs on hand from UCSD and CDPH to inform the analysis? (thanks!)**

**Comment by scleary1cs** [comment]
https://hiegateway.cdph.ca.gov/GDSPHL7Tools

**Comment by scleary1cs** [comment]
5.4	Message Requirements
Implementations of NBDS electronic results reporting have found that a streamlined ORU message consisting of a single ORDER_OBSERVATION segment group (i.e., a single ORC/OBR pair) is compatible with the functionality of many EHR systems. Therefore, this guide recommends the following message requirements:
•	A single ORDER_OBSERVATION segment group (that is only one ORC/OBR pair in the message)
•	OBR-4 valued with the LOINC code received in the electronic order (typically LOINC code 57794-0, though 54089-8 would be used, when hearing and critical congenital heart disease (CCHD) results are included in the order

**Comment by cjterdi** [comment]
Started a spreadsheet for the initial data analysis for LOE for transforming an ORU from CDPH GDSP into one that is consumable by UCSD: https://docs.google.com/spreadsheets/d/1w03qjifcNnSyAFxai36KVrzIk3sQlzyUczv05ofC5R0/edit#gid=1729974063

**Comment by cjterdi** [comment]
Annotated ORU message: https://drive.google.com/drive/folders/1UL08CS6FoMWFjasmYSdqya6CzJuYnNoe

**Comment by scleary1cs** [comment]
EM subject "LRI (and LOI) proposed changes" 12/28/23 reply.

**Comment by scleary1cs** [comment]
EM subject "Fw: CDC ETOR Technical Scoping w/ UCSD" 12/29/23 reply

**Comment by nvcllns** [comment]
Team - kindly share your working LOE estimates by EOD today. Thank you.

**Comment by sfradkin** [comment]
Document written and sent to Deloitte and CDC colleagues: https://docs.google.com/document/d/1TyaUbFEsCVMRgStDD3DVSl2uJyhF63VrkGM3EfoP4FM/edit?usp=drive_link
