### ISSUE TITLE
Converting Newborn Demographic Data

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#79]
# Story

## Sentence

As a public health lab, so that newborn demographic data can be utilized, I need the TI service to convert the data to a format the lab supports.

## Pre-conditions
- Only a single, fake public health lab is supported.

## Acceptance Criteria
- The newborn demographic data is converted to a well known format of our choosing.

### Research
- [x] Refine list of questions for PHLs to answer about data formats (questions below)
- [x] Decide on a format
- [x] Is loss of extraneous patient IDs (and other fields) acceptable when sending order details to ReportStream and subsequently the PHLs?

###  Engineering

- [x] Generate an example FHIR blob that would be sent to ReportStream.  Put it in the `/examples` directory.  Use the similar information that would be gleaned from our example newborn patient FHIR resource used in our e2e test. - @halprin 
- [x]  Convert demographics to the lab order - @halprin 
- [x] Send data to ReportStream - @jorg3lopez 
  - [x] Base level code to authenticate and send the FHIR resource - @jorg3lopez 
  - [x] (to complete) Fix-up the authentication flow so that it works - @jorg3lopez, @halprin 
- [x] Dynamically determine which ReportStream environment to send to - @halprin
- [x] Local version of sending data to the hard drive (`LocalFileLabOrderSender`) @tjohnson7021 
- [x] e2e tests to test the file created from "sending" the order to the local hard drive - @halprin, @tjohnson7021 
- [x] Correctly pick between the local hard drive "sender" implementation versus the ReportStream sender implementation when we are running locally versus running in a deployed environment. - @tjohnson7021
- [x] terraform to support key/auth infrastructure - @halprin 
- [x] Tackle [code smells](https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=trusted-intermediary) in SonarCloud (ignore generic exception ones for now?) - @halprin 
- [x] Modify SonarCloud's quality gate for our own use (in PRs and for the repo as a whole) - @halprin 
- [x] Watch Carlos' deepdive videos ([1](https://drive.google.com/drive/folders/1XU6XPJ2aGqqJQ-UGoBmgflng9x4GxMq_?usp=share_link), [2](https://drive.google.com/drive/folders/1lDEUX03HSpjLoYHrJPRps3DP4umPUntf?usp=share_link)) on the [RS Universal Pipeline](https://drive.google.com/drive/folders/1YOR6NeOEmduhJQHMrG453zXed7T5P_dU?usp=share_link). - @halprin, @tjohnson7021 
- [x] Update our sample HL7 ADT message to have a correct event code in the `EVN` segment. - @halprin 
- [x] Onboard to CDC Azure environment @halprin 
- [x] Look into `IParser` class (_Thread safety: Parsers are not guaranteed to be thread safe. Create a new parser instance for every thread or every message being parsed/encoded._) - also check the` IFhirPath` - @tjohnson7021 
- [x] Ensure changes to Terraform doesn't break the deployment - @halprin, @JohnNKing 
- [x] Look at [ReportStream's FHIR -> HL7 OML conversion](https://github.com/CDCgov/prime-reportstream/pull/8444).  Run the CLI and document what is missing.  Add additional tasks to this story for conversions we need to add.  Use the [HL7v2 to FHIR mapping](https://docs.google.com/spreadsheets/d/1PaFYPSSq4oplTvw_4OgOn6h2Bs_CMvCAU9CqC4tPBgk/edit#gid=0) as a guide.
  - [x] Patient race using our US Core Race extension. - @halprin 
  - [x] Patient birth _time_. - @tjohnson7021 
  - [x] Multiple Birth Order. @tjohnson7021 
  - [x] Next of kin's telecom. @jorg3lopez 
  - [x] Convert the Service Request. - @halprin 
- [x] Add the ISO8601 timestamp to our logging. - @halprin 

### Engineering
- [x] Threat model updated - @halprin 
- [x] Code refactored for clarity and no design/technical debt - @jorg3lopez 
- [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies.
- [x] Source code is merged to the main branch.
- [x] Unit test coverage of our code >= 90%
- [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer.
- [x] Build process updated
- [x] Feature toggles created and/or deleted.  Document the feature toggle.
- [x] Source code documentation created when the code is not self-documenting. - @halprin
- [x] API documentation generated
- [x] Code quality checks passed
- [x] Security & privacy gates passed
- [x] Load tests passed - @tjohnson7021
- [x] Documentation and diagrams created or updated - @tjohnson7021
- [x] API(s) are versioned
- [x] Debug logging - @halprin 

## Research Questions

Is it okay if the outbound message have some fields stripped away? (e.g. multiple identifiers for patient)

> Hey there all in this @ channel (and specifically @ Jason and @ Jon), we're starting to embark on an MVP where we send newborn demographic information to public health labs.  We're trying to figure out what format would be more useful for PHLs: an HL7v2 ADT message or an incomplete HL7v2 OML message.  So, we have some questions around this topic.
> 1. Can any LIMS systems accept HL7v2 ADT messages in any way?
> 2. What would be easiest to ingest into LIMS systems: an HL7v2 ADT message or an incomplete HL7v2 OML message?
> 3. What is the simplest, minimal set of data needed for incoming HL7v2 OML orders?

Maybe take a more confirmatory approach.  State that we're going to do an incomplete OML, state our reasoning why, and our future plans.  See if they confirm our approach or not.

> Hey there everyone in this @ channel.  We wanted to get some feedback on the approach we are currently taking with our newborn screening electronic order minimum viable product.  The long term path we are thinking about right now is that we would combine hospital HL7v2 ADT messages (which contains demographics, next of kin, etc.) with hospital order messages (HL7v2 OML) in order to form a complete order message to be able to send to the Public Health Lab.  Some decisions and assumptions we are looking for feedback on:
> - Begin with mapping the ADT message to OML, which will produce an incomplete order message.
>   - Assumption: While we know some or most PHLs want to or are able to receive only a complete OML message, there is a higher chance that a PHL would find value in or be able to ingest an incomplete OML message rather than a complete ADT message.
> - Next, focus on the capability to ingest a OML message, and combine that message with the ADT message in order to send the complete order message to the PHL.
>   - Assumption: The ADT message will often have ADT data that is not contained on the hospitals’ standard OML message, such as the ADT message consistently having next of kin information.  By combining messages for the hospital, this will lower implementation burden for hospitals.

- ADT vs. Lightweight OML
  - (@ channel people, but also call out Jason and Jon from JMC)
  - (provide some front matter at the beginning of the message to provide context)
  - Can LIMS systems accept HL7v2 ADT messages at all?
  - What is the simplest, minimal set of data needed for incoming HL7v2 OML orders?
  - What would be easiest to integrate into LIMS systems: an HL7v2 ADT message or an incomplete HL7v2 OML message?

  - _Older questions below..._
    - What data formats for orders do labs support for incoming orders? (HL7 v2? Custom XML? CSV?)
    - What is the simplest, minimal set of data needed for incoming orders? 
    - Does the format supported vary across labs or LIMS?
    - Can ADT-like data be accepted? (without LIMS customization)
    - ~Can the demographic data be stored and later combined with the specimen information?~
    - Can a partial order by accepted?
- Are there other resources or shared services we can leverage? (e.g. from APHL)

## Decisions
- Convert internal FHIR to HL7 v2 (LOI)
- TODO: We need to decide on a particular format for our initial prototype (likely depending upon our first partner)

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by scleary1cs** [comment]
This story is represented on the roadmap as "Order FHIR => HL7 OML #79"

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-04 - Each intermediary will create an MVP with the capability to support when the facility receives the entire order, and the intermediary is responsible for validating and transforming the order for PHL

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-05 - Each intermediary will create an MVP wherein the system accepts all order-related information from the facility. The intermediary is responsible for receiving the order, performing validation, and carrying out transformations for PHL LIMS
