### ISSUE TITLE
Inbound ID from ReportStream

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#790]
# Story
As a Lab, so that I know when the order was ingested and who sent it, I need the metadata endpoint to report order ingestion time and who sent it.

## Acceptance Criteria
- [ ] RS sends us an ID that works in the history API
- [ ] We are authenticated and authorized to call the history API with that ID

### Research
- [ ] *Research work needed to complete the story*
- [ ] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [x] Find out where the submissionId gets created
- [x] Find out where the rest transport resides
- [x] Enhance the header feature of the REST transport 
  - [x] Add option for actionId
  - [x] Fix failing tests
  - [x] Add received actionId to header
- [x] Set RS environment
  - [x] Identify faults
  - [x] Package RS
- [x] Testing
  - [x] Test that the REST request has the actionId as part of the header
  - [x] Test that TI is able to ingest the POST request with the actionId as part of the header
- [x] Reach out to Arnej to see if we need this work anymore. - @halprin 
  - [x] See what Arnej says back. - @halprin 

## Definition of Done
- [x] Documentation tasks completed
  - [x] Documentation and diagrams created or updated
    - [x] Implementation guide (`/ig` folder)
    - [x] ADRs (`/adr` folder)
    - [x] Main `README.md`
    - [x] Other READMEs in the repo
    - [x] If applicable, update the `ReportStream Setup` section in `README.md`
  - [x] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [x] API documentation updated
- [ ] Code quality tasks completed
  - [x] Code refactored for clarity and no design/technical debt
  - [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [x] Security & Privacy tasks completed
  - [x] Security & privacy gates passed
- [ ] Testing tasks completed
  - [x] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [x] Build process updated
  - [x] API(s) are versioned
  - [x] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes

This story involves making changes to the RS code, not the intermediary.

Each step in RS's pipeline is assigned a unique ID.  It is only the first unique ID assigned to a message, when it is first ingested into RS, that can be used on the RS history API.  The inbound ID we get in the HTTP request header today from RS can't be used to call the RS history API because it is the unique ID of that last pipeline step.

After talking with Arnej, he wants us to change the ReST API delivery logic to be able to send that first unique ID which will work in the history API.  Arnej states that there is already a method in RS that can calculate that first unique ID when given any of the other pipeline IDs.  So, ostensibly, all we need to do is call that method with the ID that RS is already sending to the intermediary today and then send that first unique ID to the intermediary instead.

I have a hunch that when the intermediary calls RS's history API with this new inbound unique ID, we may get a unauthorized HTTP status if the sender of the order to RS is not the same organization as `flexion`, which is the organization our intermediary uses.  I'm a little unsure about this, so like I said, it is a hunch.  If indeed we get an unauthorized HTTP status, we will need to work with RS on how to get around this.

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-27 - Intermediaries will provide metadata required, including elements to calculate timeliness metrics

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-27 - Intermediaries will provide metadata required, including elements to calculate timeliness metrics

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-29 - Each Intermediary shall have a dashboard for some higher level internal monitoring metrics – team who is troubleshooting and supporting would need access to these different views of the system

**Comment by scleary1cs** [comment]
@halprin reminder to update with prose

**Comment by scleary1cs** [comment]
Need to make a devx/opex ticket for code cleanup?

**Comment by sfradkin** [comment]
https://github.com/CDCgov/prime-reportstream/issues/12624

**Comment by scleary1cs** [comment]
@halprin @sfradkin 
From Max on 02/28/24 "Hi Shawn,

#12624 isn't prioritized in our roadmap and we don't have capacity to take it on right now.

Our recommendation would be for Flexion to implement the change needed in ReportStream. We can help orient whichever engineer takes on the work and we can review/merge the pull request when it's ready. Happy to discuss more on Friday.

Thanks,
Max"

**Comment by scleary1cs** [comment]
RS Engagement team standing by to support this work if questions come up.

**Comment by scleary1cs** [comment]
(for future Peter) This story is being closed because TI will be calling the RS deliveries API. The RS deliveries API requires a "sent reportid" and we are already receiving that. No additional work needed.
