### ISSUE TITLE
Load Test Performance fixes

### ISSUE THREAD

**Issue by jcrichlake** [CDCgov/trusted-intermediary#821]
# DevEx/OpEx

There are issues around our load tests, these include 
1. Our load test doesn't by default choose the non-local implementation
2. We lack a way to monitor the internal application performance.  This means we don't have a way to diagnose any problem areas that arise from failed load tests
3. We may need to re-examine our load test assumptions, we are currently ramping up to 1k users and then hammering the various endpoints, this may be an amount of load that is either far off in the future or will require multiple instances of the intermediary running to handle it.

## Tasks

- [ ] Update ADR if needed

**Comment by basiliskus** [comment]
The test should probably choose the storage implementation depending on the `ENV` variable. If it's local, use the local implementation, otherwise use the DB one

**Comment by pluckyswan** [comment]
We are closing this issue because [another card covers it and is more of a priority ](https://github.com/CDCgov/trusted-intermediary/issues/628). Any issues related to this card that are not covered can later be created again.
