### ISSUE TITLE
Louisiana: Ochsner to ReportStream

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#825]

**Comment by JohnNKing** [comment]
ReportStream staging API key was securely transferred yesterday.

**Comment by JohnNKing** [comment]
ORM message received successfully and routed to LDH / Natus, who confirmed receipt!

**Comment by JohnNKing** [comment]
Future effort needed for HL7 response to submitted message -- otherwise Epic will assume something is wrong and halt delivery of further orders.
