### ISSUE TITLE
Louisiana: Natus to ReportStream

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#826]

**Comment by JohnNKing** [comment]
We've been able to received a sample MN ORU from Natus successfully. However, they're seeing an HTTP 400 when sending an LA-specific ORU:

"message": "Required field missing: A datatype for OBX-5 must be specified in OBX-2.",

I've offered to take a look if they can provide the sample message.

**Comment by JohnNKing** [comment]
Corrected message was processed successful! Also, receipt by Natus was confirmed.
