### ISSUE TITLE
Alabama: Baptist to ReportStream

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#828]

**Comment by JohnNKing** [comment]
Testing earlier today indicates that jurisdiction filters need to be updated to use the correct OID (it looks like we may be expecting the value from MSH-5.2 instead of 6.2). A sample OML and ORM message each ended up in a not routed state.

**Comment by JohnNKing** [comment]
Next steps: Update receiver config and test again.

MSH-3/4/5/6 I've been working from are:
- Oracle Cerner Millennium^2.16.840.1.113883.3.13^ISO
- 51H61170^2.16.840.1.113883.3.1899^ISO
- Natus.AL.STAG^2.16.840.1.114222.4.3.26.1.1^ISO
- Bureau of Clinical Labs - Prattville^2.16.840.1.114222.4.3.2.13^ISO

I've also forwarded copies of the test messages via email.

**Comment by JohnNKing** [comment]
I must have been confused when making the comments above... This backlog item has nothing to do with processing the order (which would require full OML support) or routing to Natus. We're already able to receive orders from RLN.

I think this effort depends on the Baptist build that will allow them to send sample orders. I suspected this will be blocked until they're able to do so. Does that sound right to others? (@basiliskus, @sfradkin, @scleary1cs)

**Comment by JohnNKing** [comment]
Closed based on feedback from Oracle during meeting today -- ongoing round-trip testing includes orders originating from Baptist (not just Oracle RLN).
