### ISSUE TITLE
CA HCO Data Gap Analysis - Orders

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#836]
# Story

As CA HCO, to ensure we'll send all the data needed by the LIMS, we need to understand how specimen card and EHR fields relate to the data elements of an electronic order.

## Pre-conditions
- none

## Acceptance Criteria
- [ ] Identified what are the fields required
- [ ] Identified any message transformations needed
- [ ] Get HCO approval

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by cjterdi** [comment]
[Results/orders spreadsheet](https://docs.google.com/spreadsheets/d/1w03qjifcNnSyAFxai36KVrzIk3sQlzyUczv05ofC5R0/edit#gid=1729974063)

**Comment by cjterdi** [comment]
[Electronic implementation guide for order (point-to-point)](https://docs.google.com/spreadsheets/d/1CbtDr0KIy5b2Fz5ida-NVWEnnxmLeQ63/edit#gid=141741355)

**Comment by sfradkin** [comment]
Closing because we are not doing orders for CA right now
