### ISSUE TITLE
Sending Newborn Demographic Data

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#84]
# Story

## Sentence
As a public health lab, so that the newborn demographic data will be received, I need the TI service to send the data to the lab.

## Pre-conditions
- The TI service can receive newborn demographic data (mock or in a specific format) from a mock hospital
- A mock public health lab destination is supported

## Acceptance Criteria
- The mock public health lab has received the newborn demographic data

###  Engineering
- [x] Get our ReportStream Client ID
- [x] Send data to ReportStream - @jorg3lopez 
-   [x] Get the private key from Azure or locally - @jorg3lopez 
  - [x] Fix-up the sending of FHIR resources flow so RS accepts it (if needed, maybe it just works) - @halprin 
- [x] This should work in the staging environment
- [x] Ensure that the secret key we get from Azure is only gotten once and then cached. - @tjohnson7021 
- [x] Ensure that the RS API key is cached so we don't ask for the RS API key for every TI API call. - @jorg3lopez 
- [x] Experiment with not loosing any additional information from the original FHIR input. - @halprin 
- [x] Upload our staging private key to the Azure key vault
- [x] Update our Demographics -> Lab Order logic to support [Arnej's additions](https://github.com/CDCgov/trusted-intermediary/pull/246). - @tjohnson7021 
- [x] Add better custom exceptions when sending stuff to RS and Azure keys.
  - [x] `AuthEngine` and implementations. - @halprin 
  - [x] `HttpClient` and implementations. - @jorg3lopez 
  - [x] `Secrets` and implementations. - @halprin 
  - [x]  Stitch it together in the `LabOrderSender` and implementations. - @jorg3lopez @halprin 
- [x] Get our logging in Azure into one spot. - @halprin 
- [x] Create our dev environment.  Meant to be a wild-west environment where any developer can deploy to at any time. - @halprin 

### Engineering
- [x] Threat model updated
- [x] Code refactored for clarity and no design/technical debt @jorg3lopez  @basiliskus 
- [x] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies. @jorg3lopez 
- [x] Source code is merged to the main branch. @jorg3lopez @basiliskus 
- [x] Unit test coverage of our code >= 90% @jorg3lopez @basiliskus 
- [x] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer. - @tjohnson7021 
- [x] Build process updated - @tjohnson7021 
- [x] Feature toggles created and/or deleted.  Document the feature toggle. - @tjohnson7021 
- [x] Source code documentation created when the code is not self-documenting. - @tjohnson7021 
- [x] API documentation generated - @tjohnson7021 
- [x] Code quality checks passed @jorg3lopez @basiliskus 
- [x] Security & privacy gates passed @basiliskus 
- [x] Load tests passed @basiliskus @jorg3lopez @tjohnson7021 
- [x] Documentation and diagrams created or updated
- [x] API(s) are versioned - @tjohnson7021 
- [x] Debug logging @basiliskus 

## Research Questions
- In order to understand the variation in transport mechanisms that labs require, what protocols/transports do labs support for receiving orders?
- How are we going to send them? (e.g. via ReportStream Core)
- Retry mechanisms? At what point does the transmission fail? (from the TI to RS perspective, RS has retry as part of their pipeline to the lab)

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- *Optional: Any reference material or thoughts we may need for later reference*

**Comment by halprin** [comment]
Example HL7v2 OML that is currently being sent to the fake lab.

```
FHS|^~\&|CDC Trusted Intermediary^https://reportstream.cdc.gov/^ISO|CDC Trusted Intermediary^https://reportstream.cdc.gov/^ISO|CO-ELR|CO|20230413132304+0000
BHS|^~\&|CDC Trusted Intermediary^https://reportstream.cdc.gov/^ISO|CDC Trusted Intermediary^https://reportstream.cdc.gov/^ISO|CO-ELR|CO|20230413132304+0000
MSH|^~\&|CDC Trusted Intermediary^https://reportstream.cdc.gov/||||20230413132304+0000||OML^O21^OML_O21|8190b0c6-5ec5-4636-a542-5cf15a6d5188|P|2.5.1|||||USA|UNICODE UTF-8
PID|1||S99955754^^^^MR~b531d827-de9a-4e2e-a53b-8621bd29f656^^^^PI||Solo^Jaina^^^^^L|^^^^^^L|20170515171100+0100|F||2028-9^Asian^urn:oid:2.16.840.1.113883.6.238|||||||||||||||1
NK1|1|Organa^Leia^^^^^M|||^PRN^CP^^31^201^234567^^^^^+31201234567
ORC|NW||||IP||||20230413132304+0000
OBR||||54089-8^Newborn Screening Panel^LN|||||||P
BTS|1
FTS|1
```

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-08 - Each intermediary will support at least one format for outbound orders

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-40 - Intermediaries should enable to server-to-server access so that other systems have access to call it

**Comment by scleary1cs** [comment]
This Story helps complete the requirement:
MVP-REQ-42 - Intermediaries will need at least one authentication mechanism for server-to-server access
