### ISSUE TITLE
More Robust ReportStream Integration Tests

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#898]
# DevEx/OpEx

Create more robust integration tests to ensure ReportStream HL7/FHIR translation code changes do not break our service again.

## Tasks

- [ ] Something.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by JohnNKing** [comment]
Duplicate of #841 ?

**Comment by JohnNKing** [comment]
Duplicate of https://github.com/CDCgov/trusted-intermediary/issues/1255 ? @JohnNKing , @scleary1cs

**Comment by scleary1cs** [comment]
Agree, dup.
