### ISSUE TITLE
DevSecOps Artifacts

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#90]
Provide documentation of:
- [x] Define the DevSecOps Architecture -  @halprin 
- [x] GitHub @ CDC integration with DevSecOps Process - @halprin 
- [x] Login and Monitoring infrastructure components - @halprin 
- [x] Change management process and build, deploy, test validate - @halprin 
- [x] Blue Green Deployment strategy - @halprin 
- [x] Refine words.

(see RFQ C.6)

**Comment by sfradkin** [comment]
Delivered 12-24-2022
