### ISSUE TITLE
Convert Birth Weight to Grams

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#913]
# Story
As AL PHL, so that I receive birth weight in the units I expect for orders, I need birth weight expressed in kilograms to be converted to grams.

## Pre-conditions
- Birth weight is identified as an OBX segment with LOINC code of '8339-4' or '58229-6'
- The unit of measurement is identified via OBX.6
- This transformation initially applies to all partners -- not just AL

## Acceptance Criteria
- [ ] If the received order birthweight was measured in kilograms, then the outgoing order birthweight is instead in grams
  - [ ] The value in OBX.5 is increased by a factor of 1000
  - [ ] OBX.6 is changed to identify the new unit as grams

### Research
- [ ] *Research work needed to complete the story*
- [ ] Foundational: *High-level research that will support this and future efforts*

###  Engineering
- [ ] *Engineering work needed to complete the story*
- [ ] Foundational: *Technical runway work to support this and future efforts*

## Definition of Done
- [ ] Documentation tasks completed
  - [ ] Documentation and diagrams created or updated
    - [ ] Implementation guide (`/ig` folder)
    - [ ] ADRs (`/adr` folder)
    - [ ] Main `README.md`
    - [ ] Other READMEs in the repo
    - [ ] If applicable, update the `ReportStream Setup` section in `README.md`
  - [ ] [Threat model](https://lucid.app/lucidchart/8c6e8d37-2612-42a8-ac57-150c83f8e29e/edit) updated
  - [ ] API documentation updated
- [ ] Code quality tasks completed
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies
  - [ ] Code is reviewed or developed by pair; 1 approval is needed but consider requiring an outside-the-pair reviewer
  - [ ] Code quality checks passed
- [ ] Security & Privacy tasks completed
  - [ ] Security & privacy gates passed
- [ ] Testing tasks completed
  - [ ] Load tests passed
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build & Deploy tasks completed
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted.  Document the feature toggle
  - [ ] Source code is merged to the main branch

## Research Questions
- *Optional: Any initial questions for research*

## Decisions
- *Optional: Any decisions we've made while working on this story*

## Notes
- Example ORM with birthweight in grams: https://github.com/CDCgov/trusted-intermediary/blob/9f04eee6c683f80017827893444b3f043fdb7e50/examples/MN/003_MN_ORM_O01_NBS.hl7#L6

**Comment by basiliskus** [comment]
I propose we expand the rules engine used for validations in #341 to also handle transformations. The definitions schema could look something like this:
```
{
  "transformationRules": [
    {
      "name": "PatientFullName",
      "expression": "Patient.name.given.join(' ') & ' ' & Patient.name.family",
      "targetPath": "Patient.fullName"
    },
```
