### ISSUE TITLE
Quick generation of options and high level estimates for implementing inbound SFTP

### ISSUE THREAD

**Issue by sfradkin** [CDCgov/trusted-intermediary#944]
## Spike Goal

Generate potential options along with high level estimates for implementing automated inbound SFTP message processing in ReportStream and provide best fit recommendation. 

This will need to include assessing two scenarios: inbound files via SFTP from a CDC owned site (AL) or a partner-owned site (CA).

## Timebox

8 hours

## Notes

- see #899
- see https://slack.com/archives/C048S3GPSQG/p1708538080634029 - Mo's idea on how to automate the ingestion of messages from an RS-owned SFTP site.
- Requirements as we understand them.
  - Not circumvent RS's existing auth requirements.
  - Automation needs to be used to move the message into RS.
  - IaC should be used.
  - Costs should be considered.
- Questions to be answered (our truffle pig).
  - Do we know what the underlying infrastructure CA's SFTP site is based on?
    - moveIt
  - Is virus scanning required?
    - Unknown, @JohnNKing would you know this? (Consider not having it in the MVP)
  - Is this its own service?  Or is this built into the existing RS service?
    -  Yes separate service
  - Record retention.  Do we need it, and for how long?
    - We will be following along with the RS policy of holding messages for 60 days
  - Polling and triggers.
    - Poll once per hour between the hours of 6-9 Pacific time for CA
    - Trigger processing once files have been placed in the Azure blob storage
    - Can add other polls and triggers on an as needed basis
  - SLAs and turnaround time for processing.
    - CA would like a once a day return of ACKS.   There is uncertainty around the specifics of this that will have to be worked out with CA  
  - Credential storage and rotation.
    - Will have to manually renew CA creds via their portal
  - Encryption, will the files stored on the site be cipher text?
    - Yes
  - Do we need additional security/design review from CDC? @halprin

**Comment by scleary1cs** [comment]
Password protected zip file, in a bucket (remote service) for CA. Creds will vary.

**Comment by scleary1cs** [comment]
https://lucid.app/lucidchart/78ca8590-8660-4318-a48b-c3fe65d3f5a6/edit?invitationId=inv_66b368cf-f533-4828-af06-c359bf44f646&referringApp=slack&page=0_0#

**Comment by scleary1cs** [comment]
https://www.notion.so/flexion-cdc-ti/SFTP-Spike-39fdd4c10771456287511da3dbef5391

**Comment by scleary1cs** [comment]
https://learn.microsoft.com/en-us/azure/logic-apps/connectors/built-in/reference/sftp/

**Comment by scleary1cs** [comment]
Don't forget to create ADR(s) for all this work.

**Comment by scleary1cs** [comment]
https://learn.microsoft.com/en-us/azure/azure-functions/functions-create-storage-blob-triggered-function
and
https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cextensionv5&pivots=programming-language-csharp

**Comment by scleary1cs** [comment]
Already added to agenda for RS this Friday 05/10/2024.

**Comment by scleary1cs** [comment]
Spike Lucidchart shared with Manjula and Natalie.

**Comment by scleary1cs** [comment]
MoveIt ZIP example file needed @jorg3lopez

**Comment by scleary1cs** [comment]
https://miro.com/app/board/uXjVKJkUVrs=/
