### ISSUE TITLE
Fix ReportStream ORM Warnings

### ISSUE THREAD

**Issue by JohnNKing** [CDCgov/trusted-intermediary#998]
# DevEx/OpEx

While adding OML support to ReportStream, we found a place where supported message types are listed. However, ORM is not included. It turns out warnings are being logged when ORMs are submitted, presumably because of this. 

For more context, see https://github.com/CDCgov/prime-reportstream/pull/13766#discussion_r1539874990

## Tasks

- [x] Add ORM to list of supported message types
- [ ] Fix broken test (prime-router/src/test/kotlin/fhirengine/utils/FHIRBundleHelpersTests.kt => Test enhance bundle metadata 2-7)
  - This is a challenge; adding support for ORM to HL7Reader.kt => getMessageModelClasses causes very different logic in HL7Reader.kt => getMessages to execute. This uses an HL7 v2.7 ORM message (prime-reportstream/prime-router/src/test/resources/fhirengine/engine/hl7_2.7.hl7); my understanding is **ORM is not supported in v2.7**, so there's no HAPI model to use to make the test work.

## Additional Context

Add any other context or screenshots about the work here.

**Comment by luis-pabon-tf** [comment]
I was giving this a look and it can be done by adding a means to access the message version during the `getMessages` method call on `HL7Reader`.

**Comment by pluckyswan** [comment]
Closing this issue as neither partners need ORMs and RS is moving away from HAPI models
